### ISSUE TITLE
marco definitions require space before ";"

### ISSUE THREAD

**Issue by Xohwie1i** [newsboat/newsboat#1018]
Not sure if this is the appropriate place to report this, so please feel free to delete/move is necessary. Anyway, the documentation should be explicit about spaces being required in some macro definitions, for example, the following marco definition works:

    macro y set browser "<some cmd>" ; open-in-browser-and-mark-read ; set browser "<some cmd>"

while this one fails 

    macro y set browser "<some cmd>"; open-in-browser-and-mark-read ; set browser "<some cmd>"

The only difference is the additional space " ;" vs ";"

**Comment by Minoru** [comment]
Hi! Yep, this is the correct place to report this; thanks for doing so!

This is a bug in Newsboat 2.20. I'll release 2.20.1 in a few days that fixes this. For now, please always put a space before the semicolon in macros.

This problem is already reported in #1013, so please subscribe there if you want to stay up-to-date with that.
