### ISSUE TITLE
europeandataportal.eu feed not parsed correctly

### ISSUE THREAD

**Issue by ibispi** [newsboat/newsboat#1086]
Posting this for a friend who doesn't have a github account:

"I placed [this feed](https://www.europeandataportal.eu/data/search/en/feeds/datasets.rss?locale=en&country=&catalog=&categories=&keywords=&format=&licence=&query=food&page=1) in my newsboat `urls` file.
When I load/reload the feed, 0 items are fetched even though I see 10 `<item>`s when opening the URL in a browser.
Is this a newsboat’s problem or should I notify this with europeandataportal.eu?
newsboat version: 2.13.0"

**Comment by Minoru** [comment]
I reproduced this with current HEAD, https://github.com/newsboat/newsboat/commit/9813f9141a38f07c13c6778e9f477f74266b45ed.

There is a problem with the feed: it starts as if it's an RSS 2.0 document, but uses http://www.w3.org/2005/Atom as the default namespace. As a result, `rss`, `item` and other tags are ignored by the parser, since they aren't "RSS tags". All it takes for the publisher to fix this is replace `xmlns` with `xmlns:atom` or something like that.

The best thing, of course, is to get in contact with europeandataportal.eu and point them at [W3C's validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.europeandataportal.eu%2Fdata%2Fsearch%2Fen%2Ffeeds%2Fdatasets.rss%3Flocale%3Den%26country%3D%26catalog%3D%26categories%3D%26keywords%3D%26format%3D%26licence%3D%26query%3Dfood%26page%3D1) that clearly explains every error in the feed.

The second best thing is for Newsboat to ignore any declarations of default namespaces in RSS feeds. RSS elements are defined outside of any namespaces, so having a default namespace is obviously an error on the publisher's part. Ignoring the default namespace should be a safe thing to do, then. I'd like to have that implemented, so I'll keep this issue open.

Thanks for the report, @ibispi!

**Comment by ibispi** [comment]
Posting for my friend again:

"uropeandataportal.eu fixed their feed, thanks!

Cheers
