### ISSUE TITLE
Query feed based on content fails

### ISSUE THREAD

**Issue by ghost** [newsboat/newsboat#111]
So, I've been trying to set up a query feed which filters by content. I would like something similar to the results available by searching within newsboat. Unfortunately,  I haven't been able to get it to work. 

This query feed returns nothing.
"query:Example:content =~ \"example\""	

However, the negation does return results.
"query:Example:content !~ \"example\""	

Is there something I'm getting wrong here?

**Comment by Minoru** [comment]
Reproduced. I don't know what's going there; postponing this till the weekend.

**Comment by ancailliau** [comment]
No update on this one?

**Comment by ancailliau** [comment]
Do you have any clue on where I could look for, I can try to search and fix the bug? This bug really kills the tool for me :(

**Comment by Minoru** [comment]
@ancailliau I would start with adding logs to our Matcher class (src/matcher.cpp), to see why the regex fails to match. You can run Newsboat with `--log-file=newsboat.log --log-level=6` to write all debug messages to newsboat.log. Not sure where to proceed from there; that would depend on what you find with logging.

You'll probably want to use a separate cache (`--cache-file=whatever`) and just one feed, to limit the amount of logging. You might also want to create your own feed (copy an example from test directory) and edit descriptions there to make them shorter (so logs are easier to read). You can use `file:///home/ancailliau/feed.atom` as a URL in the urls file, so you don't even need a webserver for all that.

**Comment by ancailliau** [comment]
Awesome suggestions. I'll dive into it during winter break. I'll keep you
posted!

**Comment by Minoru** [comment]
Just as I feared, the attribute is empty. This is kinda intentional: Newsboat removes item descriptions from RAM when user leaves the feed, to save memory. If I modify the code to load descriptions before applying the regex, everything works as desired (albeit slowly).

I can't commit that code, though, because it will leave all descriptions in memory. We currently don't have any way to indicate if the description is needed by someone else (e.g. an ArticleFormAction that  displays that particular article).

I don't have any immediate solution, or even a workaround. The whole thing seems broken.

**Comment by meain** [comment]
Any update on this?

**Comment by Minoru** [comment]
@meain, sorry, nothing yet. I'm busy with #232 and #631, so it's unlikely I'll get to this anytime soon. I'm not sure how to fix this either, so I can't write up guidelines for someone else to follow and code. :(

**Comment by bouleusis** [comment]
Any new about this?

**Comment by Minoru** [comment]
@bouleusis This bug was fixed in Newsboat 2.21. (Although I somehow forgot to add it to the corresponding milestone. Fixed that now.)
