### ISSUE TITLE
Newsboat snap - having problems with playing podcasts

### ISSUE THREAD

**Issue by iandstanley** [newsboat/newsboat#1112]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.13.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat 2.13.0
System: Linux 5.4.51-v7l+ (armv7l)
Compiler: g++ 8.3.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.64.0)
SQLite: 3.27.2 (compiled with 3.27.2)
libxml2: compiled with 2.9.4
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
podcast-auto-enqueue   no
browser     lynx
auto-reload yes

# podboat config items
download-path "~/podcasts/%n"
download-retries    1
max-downloads   1
player  "mp3blaster"

```
# Reasons why I'm using snap

I'm running latest version of raspbian  on my pi but unfortunately as it's debian based that leaves me stuck with newsboat v2.13

Certain of my podcasts I subscribe to use libsyn and other services that are badly behaved and add optional %^&% to the end of the mp3 url which was fixed in version 2.14 of newsboat (thanks) 

Unfortunately, I'm forced to use snap to get a later version as newsboat relies on libraries that are newer than are shipped with debian 10 

This leaves me in the situation where I can read and download using the snap version of newsboat
/snap/bin/newsboat

But I cannot play files with /snap/bin/podboat (v2.20)

But I am able to play files in /usr/bin/podboat (v2.13) that was installed through the debian repository 

-----

Steps to reproduce the issue:

1. install snap in raspbian (latest update)

2. add urls to urls

3. enqueue, download and 'p' a podcast which just returns and 

**Other info you think is relevant**:

1. Podboat downloads the podcasts fine 
2. I can manually play the podcast with mp3blaster
3. I can play already downloaded files with /usr/bin/podboat (debian repo apt installed version)
4. I cannot play *any* file with /snap/bin/podboat
5. all the time using the same config file 

Is there any config option to allow the execution of mp3blaster I am missing?  Should I be prefixing it with another command 

Or is it a fixed limitation of the snap subsystem that cannot execute binaries outside of itself?

It doesn't appear to be a bug in the code as all hell would have broken loose - I'm guessing it's either a limitation of the snap system OR the build of the snap

**Comment by Minoru** [comment]
Hi!

> Unfortunately, I'm forced to use snap to get a later version as newsboat relies on libraries that are newer than are shipped with debian 10

What libraries do you mean? Newsboat 2.20 might not build on Debian 10 because the Rust compiler is too old there, but some of the earlier releases should, e.g. 2.14 requires Rust 1.25+ whereas Debian 10 ships 1.34.

> Or is it a fixed limitation of the snap subsystem that cannot execute binaries outside of itself?

It's how our Snap is built. Snapcraft lets us pick between "classic" and "strict" confinement. "Classic" means that the snap can invoke any program, whereas "strict" puts limits on what the snap can do. We're using "strict" confinement mainly because it's how it was initially done. Ideally we should add "Snap interfaces" to give our snap access to some specific facilities, but that hasn't happened yet.

In your situation, I'd either install a newer Debian package (if it doesn't pull too many new dependencies) or just build from source (we have instructions in the README).

**Comment by Minoru** [comment]
@iandstanley, was my comment above of any help?

**Comment by Minoru** [comment]
I consider this resolved, so closing the issue. Please comment or open a new one if something is unclear!

**Comment by tjbronx92** [comment]
Any update on adding "SNAP Interfaces" or using "Classic" mode? Installing the dependencies is causing headaches. 

`Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... not found

You need package stfl in order to compile this program.
Please make sure it is installed.
Checking for command asciidoctor... found
Checking for command cargo... found
Checking for package json... not found
Checking for package json-c... not found`
