### ISSUE TITLE
quit/open ignores selected, opens hidden feed instead

### ISSUE THREAD

**Issue by rpolve** [newsboat/newsboat#1126]
**newsboat 2.20.1**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
show-read-feeds no
```

Steps to reproduce the issue:

1. have at least two feed "A" and "B", both with unread items

2. `open` feed "A" and mark read all items

3. `quit`, feed "A" will correctly disappear (as per the instructions in the above config file)

4. now `open` next feed "B", which will have been automatically selected. Feed "A" will open instead

**Comment by dennisschagt** [comment]
Reminds me of https://github.com/newsboat/newsboat/issues/72 which was caused by a bug in a library we use (stfl).

Which version of (lib)stfl are you using?

**Comment by rpolve** [comment]
I believe you're right, looks like it's the same bug. Sorry for duplicating the issue, I must have not searched thoroughly enough.

I'm usind stfl version 0.24

**Comment by dennisschagt** [comment]
> Sorry for duplicating the issue, I must have not searched thoroughly enough.

No problem, especially because the referenced bug is closed (so you won't find it unless you also search through closed issues).

I created [a patch for stfl](https://patch-diff.githubusercontent.com/raw/dennisschagt/stfl/pull/4.patch) which fixes this issue.
I'm not sure it will ever get included in the official stfl svn repository (no reaction at all on the stfl mailing list. I've created [a fork on github](https://github.com/dennisschagt/stfl/tree/tmp/compile-on-arch-linux) to keep track of my own patches).

We might be able to create a fix in Newsboat itself to work around the stfl bug.
However, I don't think it is worth it.
It will probably be a lot of work and we are planning to get rid of the dependency on stfl anyway (https://github.com/newsboat/newsboat/issues/232).

**Comment by dennisschagt** [comment]
> We might be able to create a fix in Newsboat itself to work around the stfl bug.
> However, I don't think it is worth it.
> It will probably be a lot of work and we are planning to get rid of the dependency on stfl anyway (#232).

Thinking about this a bit more, I realized that our future stfl replacement probably won't have a feature like stfl's "pos_name" anyway.
For that reason, I removed our usage of it in PR https://github.com/newsboat/newsboat/pull/1132.
I expect that will fix this bug (I still need to verify).
