### ISSUE TITLE
How can I download link field locally?

### ISSUE THREAD

**Issue by kutsan** [newsboat/newsboat#114]
<details>
 <summary>newsboat -v</summary>

```
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Darwin 16.7.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.54.0 SecureTransport zlib/1.2.8 (compiled with 7.51.0)
SQLite: 3.16.0 (compiled with 3.16.0)
libxml2: compiled with 2.9.4
```

</details>
<br>

I have this and how can I download the URL in the `Link:` field? I know, `open-in-browser` would download via browser but I want to pass the URL to something like `curl` or `wget`.

![](https://i.imgur.com/uWhJhnK.png)

**Comment by Minoru** [comment]
There are three options:

1. a macro that'll temporarily change your `browser` setting, like this: `macro i set browser "wget %u"; open-in-browser ; set browser "firefox %u"`;
2. a bookmark script, which will also let you enter a description for the link;
3. you can write a script or something and use it instead of your browser in Newsboat. That script will take a look at the URL that's passed to it and, depending on the file extension, will open it either with your web browser or wget.

Mailcap support, if it ever gets implemented (see #112), will also make it possible to use different programs for different MIME types.

**Comment by kutsan** [comment]
Thanks @Minoru! I really appreciate it. I also have two more questions if you don't mind, could you please answer those too? I didn't want to create minor issues but if it's needed I can make it so.

1. I want to unbind all keys and redefine them. Currently, I am [unbinding all keys](https://github.com/kutsan/dotfiles/blob/885120c44962b7e7e1d403f4815bf43b262e43ae/.newsboat/config#L20-L85) that I don't have use but this becomes rather a mess. It would be better if we can unbind all keys with one line, something like `unbind-key --all`.
1. How can I define custom location of the history files (`history.search`, `history.cmdline`). Seems like there is no way.

**Comment by kutsan** [comment]
And for the others, I went with option 2. Here is my script to download torrent and pass to `transmission-daemon`.

```
bookmark-cmd "/path/to/script.zsh"
```

```sh
#!/usr/bin/env zsh

setopt ERR_EXIT PIPE_FAIL WARN_CREATE_GLOBAL WARN_NESTED_VAR

function handle_mime() {
	local mimetype="$1"

	case "$mimetype" {
		'application/x-bittorrent')
			command transmission-remote --add "$target_location/$filename" && \
			command rm $target_location/$filename

			return 0
		;;

		*)
			# Do nothing special.
			return 0
		;;
	}
}

function main() {
	typeset -g link="$1"
	typeset -g filename="$(basename $1)"
	typeset -g target_location="$HOME/Downloads"

	# Download file to target location.
	wget "$link" --timestamping --directory-prefix="$target_location"

	# Perform operations based on media type.
	handle_mime "$(file --dereference --brief --mime-type -- "$target_location/$filename")"
}
main "$@"
```

**Comment by Minoru** [comment]
Generally, I prefer separate issues for everything, even if it's a one-sentence question with similarly short answer. It's far easier to find, link to, and manage that way. But since you've already asked yours, it would be simply rude not to answer, so here goes :)

> I want to unbind all keys and redefine them. Currently, I am unbinding all defaults keys but this becomes rather a mess. It would be better if we can unbind all keys with one line, something like unbind-key --all.

Is your goal *really* to unbind all default keys? (If so, why?) Or do you do it just because `bind-key`  doesn't work if something is already bound to a key? In the latter case, I think it's more logical to make `bind-key A B` implicitly do `unbind-key A`. What do you think of that?

> How can I define custom location of the history files (history.search, history.cmdline). Seems like there is no way.

There is no way indeed, but there's an issue to add options for that: #57. It's rather simple, so if you badly want it and have a friend who codes, give them a link. I think even C programmers without C++ experience will be able to deal with it (basically: update `getopt` call, thread the result to places where history files are written).

> How can I use more than one urls file? I want to keep some of my RSS feed URLs in a separate file. Is there any way to do that?

Currently, there is no way, and If we're talking of fetching some feeds through remote API (TT-RSS etc.) and others natively, there won't be—it's just too complicated. Otherwise please open an issue and describe your use-case in more detail; specifically, why do you need that, and how do you expect `edit-urls` command to behave if there are multiple urls files?


And thank you for sharing the script. It's nice to see the old tradition of posting the final solution lives on :)

**Comment by kutsan** [comment]
> Generally, I prefer separate issues for everything, even if it's a one-sentence question with similarly short answer. It's far easier to find, link to, and manage that way.

I'll keep that in my mind for future issues. I wasn't sure what do to before.

> But since you've already asked yours, it would be simply rude not to answer, so here goes :)

Thank you so much!

> Is your goal really to unbind all default keys? (If so, why?) Or do you do it just because bind-key doesn't work if something is already bound to a key? In the latter case, I think it's more logical to make bind-key A B implicitly do unbind-key A. What do you think of that?

It's not like that. I don't like default key mappings and I rather prefer get rid off and redefine them from scratch. That way I can clearly see within my configuration what is my key bindings, without thinking what was the default ones that I didn't override. This keeps me and my configuration sane. tmux provides `-a` flag for their `unbind-key` command for the same problem.

> There is no way indeed, but there's an issue to add options for that: #57. It's rather simple, so if you badly want it and have a friend who codes, give them a link. I think even C programmers without C++ experience will be able to deal with it (basically: update getopt call, thread the result to places where history files are written).

It would be good to have but I don't want that, that badly though. Plus, I don't have any friend. Although, I prefer learning C++ from scratch and creating my own pull request.

> Currently, there is no way, and If we're talking of fetching some feeds through remote API (TT-RSS etc.) and others natively, there won't be—it's just too complicated. Otherwise please open an issue and describe your use-case in more detail; specifically, why do you need that, and how do you expect edit-urls command to behave if there are multiple urls files?

I was talking about something like `include` command for `urls` file. There is nothing about remote API calls.

```
include "~/.newsboat/urls.local"

https://feeds.feedburner.com/2ality "~Axel Rauschmayer" "Blog"
http://javascriptweekly.com/rss "~JavaScript Weekly" "Blog"
https://dmitripavlutin.com/rss "~Dmitri Pavlutin" "Blog"
```

That way `include` line should replace with content of `urls.local` file as if they were written there in the first place. There are some of my RSS feeds that I want to keep it private but I can't make it so. That's the problem I am having. Should I create an issue for that?

`edit-urls` should still open main `urls` file. Since we are using `include` command there too, there shouldn't be any further problem about how that command should behave.

> And thank you for sharing the script. It's nice to see the old tradition of posting the final solution lives on :)

Honestly, you are very welcome.  Thanks for everything and spending your time to answer my questions. I am really glad and can't give much to you other than my words to explain how grateful I am.

**Comment by Minoru** [comment]
I've created new issues for "include" and "unbind-key -a" features. You can subscribe to them to keep on top of things. Thanks for the suggestions, @kutsan!

**Comment by kutsan** [comment]
@Minoru Thanks again!
