### ISSUE TITLE
Add space after url before number on the link list

### ISSUE THREAD

**Issue by roman-holovin** [newsboat/newsboat#1156]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.20.1

I have a terminal emulator that can parse urls, unfortunately in cases `http://url[1]`, it thinks that `[1]` is a part of the url. 

<details>
   <summary>Example</summary>

```
newsboat 2.20.1 - Article 'D3 6.0' (57 unread, 98 total)
Feed: Hacker News: Newest
Title: D3 6.0
Author: catacombs
Date: Wed, 26 Aug 2020 23:29:47 +0000
Link: https://github.com/d3/d3/blob/master/CHANGES.md

Article URL: https://github.com/d3/d3/blob/master/CHANGES.md[1]

Comments URL: https://news.ycombinator.com/item?id=24288497[2]

Points: 249

# Comments: 63

Links:
[1]: https://github.com/d3/d3/blob/master/CHANGES.md (link)
[2]: https://news.ycombinator.com/item?id=24288497 (link)
```
</details>

If I'm to click on either `Article URL` or `Comments URL` from an example above, it will open the browser with `[1]` or `[2]` appended which most likely are going to be 404.

Suggested solution is to add a single space after url.

**Comment by Minoru** [comment]
Hi! Sorry for the delayed response, I was on a break.

I'm not completely against this change, but it feels like I'll be doing a disfavour to you by implementing it :) Instead of reaching for the mouse/trackball/trackpoint/trackpad, use Newsboat's built-in capabilities:
* for links from first to ninth, you can just press a corresponding number key;
* for the tenth link you can press 0l
* for other URLs you can do any of the following:
    * press `#` (`goto-url`) and type the number;
    * press `u` (`show-urls`), select the URL there and press Enter.

If you insist on adding a space, feel free to submit a PR, but please make sure that word-wrapping doesn't put the link number on the next line, i.e. we don't get texts like this:

```
Comments URL: https://example.com/item?id=123
[2]
```

**Comment by roman-holovin** [comment]
No problem, thanks for the detailed reply and suggestions.

I know about those hotkeys, thing is I use Newsboat over ssh and any "open in browser" command will try to open browser on the remote machine (at least to my knowledge). Handling URLs in terminal emulator works locally and opens local browser and this is what I want.

Can you point out relevant part of the code base, so I can dig in?

**Comment by Minoru** [comment]
Got it! Yeah, I don't think it's possible to run a local command from a program that runs on the other side of an SSH; the best you can do is X forwarding, which doesn't really suit the use-case.

Take a look at src/itemrenderer.cpp and test/itemrenderer.cpp. You should change `to_plain_text` and `to_stfl_list` methods. Since word-wrapping doesn't know where the square brackets come from (were they added by the HTML renderer, or were they in the RSS item itself?), it might make sense to use a non-breaking space before the bracket in the HTML renderer.

**Comment by roman-holovin** [comment]
Turns out using newsboat over ssh from the phone is not a pinnacle of the user experience :) I wrote my own web frontend (with very thin backend) around newsboat's `cache.db` and therefore this issue is no longer relevant to me. Sorry for taking your time.

**Comment by Minoru** [comment]
Yeah, I doubt it's possible to make a useable TUI for mobile: the screen is tiny, the keyboard is subpar.

Please note that we don't provide any guarantees about our database scheme; it's an implementation detail. Don't forget to make backups ;)

And thanks for filing the issue in the first place! It's hard to know what people need unless they come forward to talk about it, so reports are appreciated even if they can't really be fixed.
