### ISSUE TITLE
Losing library when '~/.config/newsboat/urls' changes

### ISSUE THREAD

**Issue by n0542344** [newsboat/newsboat#1181]
Thanks a lot for the awesome `newsboat`-tool - I'm using it on a daily basis.  In most cases it works flawlessly, but I have experienced sometimes a major issue which led to me lose all my library.

I'm using the following version of `newsboat` on my `Debian Stable` system:

    newsboat 2.13.0
    System: Linux 4.19.0-9-amd64 (x86_64)
    Compiler: g++ 8.3.0
    ncurses: ncurses 6.1.20181013 (compiled with 6.1)
    libcurl: libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.64.0)
    SQLite: 3.27.2 (compiled with 3.27.2)
    libxml2: compiled with 2.9.4

My `~/.config/newsboat/urls`-file is a symlink (since I'm using `rcm` as a dotfile managing tool which creates symlinks for config files and stores the actual files in a separate folder to be used as a vc-repository like `git`).  When it is available, everything works fine.  But when my  `~/.config/newsboat/urls` is missing some content (e.g. because I'm commenting some parts out for testing or because I'm symlinking a different file) it will use this one to get the feeds - which is expected behaviour.  In this case I'm only able to see the parts I had written in the new `urls`-file.

But as soon as I use my original file again I realize that everything, which was formerly stored in the `SQLite`-database included in `newsboat`, is lost, including all my old feeds, the flags, the downloaded data, everything.  

Since my library is (was) huge and I invested quite some time in tuning it to my needs, this is a major issue for me.

So my questions are as follows:

1) why is this happening?

2) is there a way to recover that data?

3) is there a way to prevent `newsboat` to delete my old data in the future?

**Comment by Minoru** [comment]
Hi! Sorry you lost some data ._.

> 1. why is this happening?

Because Newsboat removes data that is no longer reachable. From Newsboat's point of view, you removed a feed from the urls file, which means you're no longer interested in that feed; this means you don't need the related data any more. Thus, it is removed from the database.

> 2. is there a way to recover that data?

Restoring your cache.db from a backup is the only way to get the data back.

> 3. is there a way to prevent newsboat to delete my old data in the future?

Yes, add `cleanup-on-quit no` to your config.

Does that answer your questions?

**Comment by n0542344** [comment]
Thanks @Minoru for your swift reply!

> add `cleanup-on-quit no` to your config

Awesome, that solves my issue, thanks a lot!

> From Newsboat's point of view, you removed a feed from the urls file, which means you're no longer interested...

Well, that makes sense - but is that a good choice for the default behavior?  This way it's relatively easy to lose data.  If it would be the other way round (cleanup is only performed manually except if specified so on the `config`-file) the downside would only be a larger db - but if that bothers anyone a manual cleanup could be performed.

**Comment by Minoru** [comment]
> This way it's relatively easy to lose data.

I was going to say that this is like complaining that removing a name from the file system makes it easy to lose data, but then I realized that people already ran into *that* problem, and solved it with the "waste-basket" metaphor. So now I think you're right.

I can't change the default in a minor release, so that will have to wait until 3.0. But the manual cleanup can be added earlier, to the benefit of those who already disable `cleanup-on-quit`. I'll file separate issues about that.
