### ISSUE TITLE
ocnews sync issues

### ISSUE THREAD

**Issue by aleprovencio** [newsboat/newsboat#122]
Hello, this is Newsboat version 2.10.2

I have `urls-source "ocnews"` working for my nextcloud news instance, but I've  realized syncing is not fully correct. Although the majority of feed sources have unread items matched with NC, some have not. On those problematic ones, a manual refresh will get them to sync fine. I've already tried the vacuum option and even deleting the actual cache file.

In addiction to that, I find refreshing all feeds very slow compared to the official app I run on my android phone.  I have the options `reload-threads 20` set, which seems to be already a big number.

**Comment by Minoru** [comment]
@dirb, are you still using ownCloud News? Do you have any insight into what might be going on here?

@aleprovencio, `reload-threads` is only used with local urls-source, so it shouldn't affect this at all. (But you'd better check this bit :)

Run Newsboat with debug logging and look for lines saying "ocnews_api::query: connection error code":

```
$ newsboat --log-level=6 --log-file=newsboat.log
```

**Comment by aleprovencio** [comment]
@Minoru, yes lots of these lines on the logs, all showing `error 28`. The `reload-threads` seem to make a difference, as I just tested with htop.

**Comment by Minoru** [comment]
Error 28 [means timeout](https://curl.haxx.se/libcurl/c/libcurl-errors.html). The default for Newsboat is [30 seconds](https://newsboat.org/releases/2.10.2/docs/newsboat.html#download-timeout).

I'm actually glad I was mistaken about `reload-threads` thing; does it help if you set it to a lower value, maybe just 1? Otherwise (but separately) try tweaking `download-timeout` to see if larger values help.

How many feeds have you got, by the way?

Last but not least, you might take a look at the logs at your nextCloud instance to see if there's any traces of timeout there.

**Comment by aleprovencio** [comment]
@Minoru thanks for figuring that out.

I increased `reload-threads` in the past to maybe improve syncing speed which is still slow, but setting it to 1 as suggested doesn't get me unread feeds mismatch or "connection errros" on the newsboat logs. NC logs are also clean.

I'll keep an eye on it and maybe tweak timeout.

My feed subscriptions totals 55.

**Comment by Minoru** [comment]
Cool, so that issue's resolved, then! I'll open a separate one for slowdown compared to the official app. I'm also adding some code that'll convert numeric error codes to text, to make debugging easier.
