### ISSUE TITLE
ItemView: Scrolling is reset when resizing terminal

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#1298]
**Newsboat version**: newsboat r2.21-185-g2cdd7

Config file:

```
# Empty
```

Urls file:
```
http://antirez.com/rss
```

Steps to reproduce the issue:

1. Open an article with enough text to fill all lines of the terminal

2. Scroll down a few lines

3. Resize the terminal

**Expected behaviour**: The same line should be kept at the top of the screen

**Actual behaviour**: The textview scrolls to the top of the article

**Other info you think is relevant**:
git bisect points to https://github.com/newsboat/newsboat/commit/8b674f81aec5fc47aa716f11f6447f25d6ad9ffe.
This issue only seems to affect the ItemViewFormAction.
I'm not sure why other `TextviewWidget`s are not affected.

**Comment by dennisschagt** [comment]
Apparently the ItemViewFormAction always resets the scroll offset to 0 if `do_redraw == true`:
https://github.com/newsboat/newsboat/blob/7efb55f908d81b971c2bdfa2c37fd9c0e16aa8e5/src/itemviewformaction.cpp#L144

**Comment by Minoru** [comment]
The history of this line is a bit weird:

- introduced for no apparent reason in https://github.com/newsboat/newsboat/commit/805a249ba75b21a0abb0c3849e9381ca1f9d98b0 — but note that it's run *once*, because Newsbeuter didn't have redraws at that point;
- later moved to where it is today: https://github.com/newsboat/newsboat/commit/ea818e24a73a13577f8125e031b76f4bd3f83399 Here it actually makes some sense: if we switched between source and rendered views, it makes sense to reset the position, since the views (might) contain different amount of text.

If I guessed the purpose right, then we should change this line to only reset the offset if the view type changed.

**Comment by dennisschagt** [comment]
> If I guessed the purpose right, then we should change this line to only reset the offset if the view type changed.

It looks like there are more reasons to let the textview move to the first line again.
For example, with OP_NEXT, the same FormAction instance will show a different article.
When changing to a different article, it seems natural to change to the top of the article again.

Some other operations which change the selected article:
https://github.com/newsboat/newsboat/blob/ef2531d7cc17f74e427c436b95330415c69a8368/src/itemviewformaction.cpp#L340-L390

**Comment by Minoru** [comment]
Yeah, makes sense when switching between articles.

Also, for resizing it makes sense because the number of lines might have changed after a re-flow. Line 20 at width 160 will probably become line 40 at width 80 (depends on actual text of course). Just resetting the position is an easy way out. Coming up with a more intelligent algorithm sounds like a pretty interesting problem, actually :)
