### ISSUE TITLE
Support for multiple authors per Atom feed entry

### ISSUE THREAD

**Issue by herrsimon** [newsboat/newsboat#1309]
Hello, 

the Atom 1.0 specification allows multiple <author> nodes per entry and it would be nice if newsboat would become aware of this (currently only the first encountered author node is parsed). In particular:  

- support aggregation of multiple authors in article lists, so that for example "Author A, Author B, Author C" can be displayed in the author column of a multi-author entry. This could for example be achieved by introducing an 'A' flag for articlelist-format (while 'a' continues to only display the first author)
- display all authors on separate lines in article view
- take into account all <author> nodes when filtering per author, i.e. the expression is first matched against all <author> nodes separately and then aggregated by OR ("positive" matching, i.e. =, =~, # etc.) or AND ("negative" matching, i.e. !=, !~, !#)

**Comment by Minoru** [comment]
Hi! What version of Newsboat are you running?

> support aggregation of multiple authors in article lists, so that for example "Author A, Author B, Author C" can be displayed in the author column of a multi-author entry

This [has been done](https://github.com/newsboat/newsboat/pull/846) in Newsboat 2.20.

> display all authors on separate lines in article view

People highlight the article header and rely on the "Author: " prefix, so I'm hesitant to introduce such a change. Do you have an argument for it?

> take into account all nodes when filtering per author

Well, we already packed all the authors into the "author" attribute, so the best you can do is use regular expressions instead of equality, something along the lines of `(^|, )Author name(, |$)` (untested!) Would that be sufficient for your needs?

**Comment by herrsimon** [comment]
My apologies, I'm actually on Newsboat 2.21 but my "test" feed was fetched a long time ago with a version before support for multiple authors. So a simple feed refresh made all authors appear (and my problems disappear). 

Also, keeping all authors on a single line as currently done is actually much better than adding them on separate lines (each line prepended by "Author: ") .

Sorry again!
