### ISSUE TITLE
Run Multiple copies at the same time?

### ISSUE THREAD

**Issue by racingdevtech** [newsboat/newsboat#132]
newsboat 2.10.2
Steps to reproduce the issue:
1. open new shell
2. newsboat

**Comment by Minoru** [comment]
Hi! You can run many copies of Newsboat as long as they're using different cache files (though you'll probably want different urls files as well). Run each copy like this:

```
$ newsboat --cache-file=/path/to/the/cache.db --url-file=/path/to/your/urls/file
```

You can also specify a separate config file with `--config-file`, if you need that.

There is no plans to make it possible to run multiple copies with the same cache, because it'll need synchronization, notifications, conflict resolution and whatnot—I'd rather have that effort spent on something closer to the current feature set.
