### ISSUE TITLE
Date format in article list as "X days ago"

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#1323]
Is it possible to display the article list with the dates like `X days ago`?

**Comment by Minoru** [comment]
It's not currently possible, but I think it makes sense to support this.

The format is configured by [`datetime-format`](https://newsboat.org/releases/2.21/docs/newsboat.html#datetime-format), which `ItemListFormAction::item2formatted_line()` [feeds](https://github.com/newsboat/newsboat/blob/de06ef817efe90c3868be3f79f40faaccdb29df4/src/itemlistformaction.cpp#L1043-L1046) into `strftime()` [via `utils::mt_strf_localtime()`](https://github.com/newsboat/newsboat/blob/de06ef817efe90c3868be3f79f40faaccdb29df4/src/utils.cpp#L1031-L1049). To add a new formatter, one has to:

1. pick a letter for it. Read through strftime manpages for as many Unix-likes as you can (at a minimum: Linux, FreeBSD, macOS) and figure out which letters aren't taken yet;
2. in `item2formatted_line()`, add `FmtStrFormatter` that turns the letter you picked into "X days ago" value. The string itself should be marked for translation: `_("%u days ago")`;
3. update the the docs for `datetime-format` ;)

I'd say this is pretty easy to do, so I'll mark this feature request as such. Please drop a comment if you need any assistance in implementing this!

**Comment by amritbrar** [comment]
> 1. pick a letter for it. Read through strftime manpages for as many Unix-likes as you can (at a minimum: Linux, FreeBSD, macOS) and figure out which letters aren't taken yet;

%L, %o, %N, %K and %f are some of the few that are available. I've checked Linux, FreeBSD, macOS, and OpenBSD. Windows Subsystem for Linux installs Ubuntu by default, so it's also covered.

> 2. in `item2formatted_line()`, add `FmtStrFormatter` that turns the letter you picked into "X days ago" value. The string itself should be marked for translation: `_("%u days ago")`;

Would you search `const std::string& datetime_format` for the letter (say %L), and if it's found, compute time difference in days, otherwise, do `utils::mt_strf_localtime(datetime_format, item.first->pubDate_timestamp()))` as normal?

e.g.
```c++
const auto is_found = datetime_format.find("%L");
if (is_found != std::string::npos) {
        // calculate difference in days between article publish date and current date(using std::chrono)
        // std::difftime takes two time_t arguments as dates
        // can calculate epoch time for both dates(using std::chrono), get difference (in seconds), and convert to days?
        // std::round(std::difftime(pub_date_epoch, current_date_epoch)/86400) ?

        const auto days = std::round(std::difftime(pub_date_epoch, current_date_epoch)/86400);
        fmt.register_fmt('D', strprintf::fmt(_("%u days ago", days))
}
// Otherwise, do the normal operation
fmt.register_fmt('D', utils::mt_strf_localtime(datetime_format, item.first->pubDate_timestamp()));
```

**Comment by Minoru** [comment]
Thanks for looking into it! There are even fewer spare letters than I imagined :)

My idea was to *supplement* `strftime`: replace %L first, then use the result as a format for `strftime`.

Also, `FmtStrFormatter` is a wrong tool for this, because it expands formats like `%>[char]`. It's better to use `utils::replace_all`. (This is funny: I just pointed this out during a review in one of the PRs a few days ago, and now I'm falling into the same trap myself.)

@amritbrar, looks like you've done half the work already — would you please submit a PR with a complete fix?

**Comment by amritbrar** [comment]
I'll submit a draft PR shortly, we can discuss the rest there.
