### ISSUE TITLE
mark-feed-read when filter is applied should only mark visible items read

### ISSUE THREAD

**Issue by tonycpsu** [newsboat/newsboat#1364]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

`r2.21-362-g80f1`

Steps to reproduce the issue:

1. Apply a filter by pressing `F` and type in `title =~ "(string that's only in a subset of articles)"`

2. Press `A` to mark all read.

Expected: only visible articles are read, similar to if one had used `/` (`open-search`) to do the filtering instead of a filter.

Actual: all articles in the feed are read.

My guess is this happens because `/` creates a temporary "feed" and marks it read, while filters work differently?  Anyway, seems like they should work the same, or perhaps a new `mark-visible-read` command could be added?

**Comment by Minoru** [comment]
Reproduced on 8880ba431012964d62c8d798191995e53a58a99f, thanks for the report!

> My guess is this happens because / creates a temporary "feed" and marks it read, while filters work differently?

Exactly. Filters are applied at "display" time, by filtering out the items that don't match: https://github.com/newsboat/newsboat/blob/8880ba431012964d62c8d798191995e53a58a99f/src/itemlistformaction.cpp#L916-L923

> seems like they should work the same

Yes, I think the expected behaviour you describe is the correct one.
