### ISSUE TITLE
Newsboat draws over urls-editor after an automatic reload

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#1369]
**Newsboat version**: 119582d72d2dd25993d06b6f809e26944827237e (current `master` branch)

Config file:
```
auto-reload yes
reload-time 1
```

Steps to reproduce the issue:

1. Start Newsboat

2. Press shift+e

3. Wait for a minute

Newsboat draws over the editor, showing "empty formaction".
After quiting the drawn-over editor, Newsboat behaves strangely.

**Other info you think is relevant**:
git bisect points to https://github.com/newsboat/newsboat/commit/8e63a31d501115a85b1b16d756681fd9a0a840f1

**Comment by Minoru** [comment]
Ugh. I'm ignoring all other emails because I'm writing a changelog for 2.22, but this issue obviously deserves some attention. Thanks for catching this so early, I think you saved us all from 2.22.1 :)

Okay, so the problem is that `EmptyFormAction` has some STFL elements that Newsboat can update, and thus make STFL draw something. I don't know how to fix this systematically, the best I can suggest is:
1. change `View::set_status` to ignore `EmptyFormAction`;
2. release 2.22 with that fix;
3. now relax and figure out a way to fix this properly :)

Do you have other ideas, @dennisschagt?

**Comment by dennisschagt** [comment]
> Thanks for catching this so early

I just noticed it by accident so I'm happy it is still in time.

> I don't know how to fix this systematically, the best I can suggest is: …

Sounds good.
I'm just checking if there are other places where this should be checked, e.g.:
https://github.com/newsboat/newsboat/blob/119582d72d2dd25993d06b6f809e26944827237e/src/view.cpp#L924-L932
