### ISSUE TITLE
Performance regression bisected to 65f6f99a4220d81785fb31a0f64feca02265e106

### ISSUE THREAD

**Issue by polyzen** [newsboat/newsboat#1372]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

https://github.com/polyzen/dotfiles/blob/master/workstation/.config/newsboat/config

Steps to reproduce the issue:

1. Have feed with ridiculous amount of articles (eg. 4282 articles)

2. Hold down key to scroll

3. newsboat lags and pegs out a core until it's done scrolling

**Other info you think is relevant**:

Bisected: "65f6f99a4220d81785fb31a0f64feca02265e106 is the first bad commit"
https://github.com/newsboat/newsboat/commit/65f6f99a4220d81785fb31a0f64feca02265e106

**Comment by polyzen** [comment]
cc @dennisschagt

**Comment by Minoru** [comment]
Thank you for the report! I bisected to the same commit with an empty config. I don't yet understand how this commit causes the regression, but I'm looking into it.

**Comment by Minoru** [comment]
I traced this down to `ItemListFormAction::do_redraw` being constantly `true`, which makes the following `if` call `invalidate_list()` on each iteration, which in turns means Newsboat has to go through all items in the list and "format" them:

https://github.com/newsboat/newsboat/blob/fad9cc0b58fd257c9422bd2f8e5aab2e55acdf20/src/itemlistformaction.cpp#L1006-L1009

This is fixed by #1374.

I don't feel like this is quite catastrophic enough to warrant a bugfix release. @polyzen, do you agree? Does your workflow rely heavily on fast-scrolling through the item list?

**Comment by polyzen** [comment]
Just normal scrolling, though I should definitely clean out my articles. This is on a desktop with an i5-3570k, so it may affect users on slower systems with smaller article counts.

Before:

https://user-images.githubusercontent.com/3533182/102935315-d04a0c00-449d-11eb-999e-698751983cb0.mp4

After:

https://user-images.githubusercontent.com/3533182/102934934-0aff7480-449d-11eb-8f61-a46edee1ceb0.mp4

**Comment by Minoru** [comment]
Okay, okay, I'll release 2.22.1, say, on the 9th January 2021 — I'd like to wait a bit for 2.22 to get into distros and for people to report any more critical bugs.
