### ISSUE TITLE
Building v2.22 fails on Debian Stretch

### ISSUE THREAD

**Issue by mglh** [newsboat/newsboat#1378]
**Newsboat version: Source from newsboat-2.22.tar.xz**

Output of build process:

- [Coloring converted to HTML](https://paste2.org/v3PpcHNA)
- [Coloring stripped](https://paste2.org/8pFvsN9A)

"Progress bars" are missing in the latter.

I assume it's a problem on my system here, since its an older version of Debian.

Versions:

```
gcc             4:6.3.0-4
rustc           1.41.1+dfsg1-1~deb9u1
libstfl-dev     0.22-1.3+b4
sqlite3         3.16.2-5+deb9u3
libcurl3        7.52.1-5+deb9u13
libssl1.0.2     1.0.2u-1~deb9u3
libcurl3-gnutls 7.52.1-5+deb9u13
gettext         0.19.8.1-2+deb9u1
libsqlite3-0    3.16.2-5+deb9u3
libsqlite3-dev  3.16.2-5+deb9u3
pkg-config      0.29-4+b1
libxml2-dev     2.9.4+dfsg1-2.2+deb9u3
libjson-c-dev   0.12.1-1.1+deb9u1
asciidoctor     1.5.4-2
```

**Comment by Minoru** [comment]
Hi!

> rustc           1.41.1+dfsg1-1~deb9u1

This is too old, we only guarantee 1.44 or newer to work. I forgot to include that in the changelog — sorry about it! You can install a newer version via rustup, or from Debian testing.

We also bump the requirement on each minor release, so e.g. Newsboat 2.22 will require Rust 1.46 or newer.

**Comment by mglh** [comment]
Thank you for your answer, and the hint pointing to `rustup`.
After installing rustc this way building succeeded flawlessly.

**Comment by Minoru** [comment]
Awesome! I'll close the issue then.

**Comment by mglh** [comment]
I would suggest to add a check of the rustc version in `config.sh`, 
and to add a recommendation  to run `config.sh` before running `make` 
in `README.md`, if this appropriate.

**Comment by Minoru** [comment]
I doubt that adding anything to the README will help, since the Rust version is already listed there and you missed it ;) Also, we provide a *guarantee* of which version works, not a *requirement* of what version is needed — the difference is that an older version *might* work, we just don't know because we didn't check. So the best we would be able to do is a warning, which will quickly scroll off as the build starts.

Perhaps I should rename `config.sh`? It seems like people quite often take it for an autoconf-style `configure` script, whereas in fact it's just a helper to get some info from `pkg-config`.

**Comment by mglh** [comment]
> the Rust version is already listed there and you missed it ;)

Indeed, I did =:)

> Perhaps I should rename config.sh?

Perhaps something like `check_versions.sh`?

**Comment by Minoru** [comment]
That'd be misleading, because that script doesn't check versions. (Well, okay, it asks for at least libjson-c 0.11, but that's it). And I don't want to turn it into an autoconf-style `configure` because, as you probably know, autoconf got born out of people's frustration with writing those scripts by hand.
