### ISSUE TITLE
Is there a way to apply "random" filter in our querry feed?

### ISSUE THREAD

**Issue by therajat08** [newsboat/newsboat#1384]
for example for "all unread" feed we use:
`"query:Unread Articles:unread = \"yes\""`

But can we write expression for random sorting also?

**Comment by Minoru** [comment]
This is not possible because filters' job is to decide what items to display. They can't affect the order of items.

Instead, you should sort the list when it is displayed. In case of a query feed, that'd be an article list. Take a look at keys `g` (`sort` operation) and `G` (`rev-sort`), and also the setting [`article-sort-order`](https://newsboat.org/releases/2.22/docs/newsboat.html#article-sort-order).

Does that answer your question, @therajat08?

**Comment by therajat08** [comment]
yeah i think g will do. thanks
