### ISSUE TITLE
articlelist title not updated when moving to next unread feed

### ISSUE THREAD

**Issue by szigetva** [newsboat/newsboat#1385]
**Newsboat version**: newsboat 2.22.0

```
[…]
articlelist-title-format "%T %u/%t %L"
[…]
```

Steps to reproduce the issue:

1. All articles in feed are read, move to next article in next feed using `n`

2. Articlelist title remains that of old feed.

3. Moving out to feed list and back to unread feed shows correct title.

**Other info you think is relevant**: correct behaviour in version 2.21.

**Comment by Minoru** [comment]
Thank you for the report! I reproduced this with an empty config, and git-bisect tells me this bug was introduced in 74886578de8cd6c1f3f50a315f273ca47d5005e5 — which is weird since that commit is not in 2.22. Did you build Newsboat from Git, @szigetva?

It's still a bug, of course, and would have to be fixed. Just curious what's going on.

(By the way, `%L` is only available in `datetime-format`, and doesn't work in `articlelist-title-format`.)

**Comment by szigetva** [comment]
It was updated from the Arch community repo by regular update.
(Indeed, I was wondering what `%L` did in my config, since it did not show up.  I deleted it, thx.)
