### ISSUE TITLE
"age" not working when setting filter

### ISSUE THREAD

**Issue by bobicino** [newsboat/newsboat#1397]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.22.0

Steps to reproduce the issue:

1. Open newsboat

2. Press "F" to set a filter

3. Write `age between 0:10`

**Other info you think is relevant**:
The "age" keyword does not work when setting filter. I get the following error:
*Error: applying the filter failed: attribute `age' is not available.*

However, "age" works with queries in the `urls` file.

**Comment by Minoru** [comment]
Hi! [`age`](https://newsboat.org/releases/2.22/docs/newsboat.html#attr-age) is only available for articles, but you're trying to apply it to feeds. Query feeds apply the expression to articles, that's why `age` works there.

What were you trying to achieve with that filter? Perhaps I would be able to suggest an alternative solution.

**Comment by bobicino** [comment]
Oh, I thought I could apply it also to the feed list and it would automatically remove the feeds which had articles with age less than 10.
I was trying to replace a query feed with a filter, to have it not listed in the feed list.
Specifically, I was trying to find recent read articles.
However, I have seen you added the "enhancement" label to my other issue on "article read history". So I hope that feature will come in the future and just keep the query for now :)
