### ISSUE TITLE
Is it possible to send article link in notification?

### ISSUE THREAD

**Issue by daftz** [newsboat/newsboat#1398]
Hi, I'm using newsboat to monitor a (filtered) feed and I receive a notification on Telegram when the feed contains a certain keyword.

Is it possible to include a direct link to the article in the notification? Now I just include a text containing the address of the website.

Thanks!

**Comment by Minoru** [comment]
Hi! Newsboat notifications report aggregate values like total number of new articles — guess it's not obvious if you only have a single, rarely updated feed, so each notification effectively corresponds to a single article. I understand this is a pretty limited interface; perhaps https://github.com/newsboat/newsboat/issues/1155 could extend it sufficiently that your use-case becomes possible.

Overall, I get a feeling that Newsboat is not the right tool for the job: Newsboat is geared towards being used by a person rather than being a part of some automated process. If I were you, I'd use rsstail or wrote a Python script with `feedparser` library.

I don't think there's anything to do about this issue for us, so I'm closing this.
