### ISSUE TITLE
Snownews extensions examples link dead (manpage) 

### ISSUE THREAD

**Issue by mjb-v9-5-2** [newsboat/newsboat#1414]
**Newsboat version newsboat 2.10.2 System: Linux 5.4.0-58-generic (x86_64) **:

```
manpage points to a page of examples of snownews extensions. link is now dead. quick search produced no alternative:

https://kiza.eu/software/snownews/snowscripts/extensions/
```

**Comment by Minoru** [comment]
This has been fixed by https://github.com/newsboat/newsboat/commit/70f2c580ba926d1296539fa8fcb71e77d77e5124 in Newsboat 2.19. The link now points to https://github.com/kouya/snownews/tree/master/contrib. It's probably not the exact replacement — I believe kiza.eu contained more scripts than that — but it's the best replacement I found.

Thanks for taking the time to report this! I obviously don't click through all the links every day, so it's nice when people tell me what links rotted while I was looking the other way.
