### ISSUE TITLE
Getting `ocnews_api::query: connection error code 60` when connecting to a nextcloud instance over http*s* only

### ISSUE THREAD

**Issue by doronbehar** [newsboat/newsboat#149]
### Newsboat version (copy from `newsboat -v`):
```
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Linux 4.15.9-1-ARCH (x86_64)
Compiler: g++ 7.2.1 20171215
ncurses: ncurses 6.1.20180127 (compiled with 6.0)
libcurl: libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.20.0 (+libidn2/2.0.4) nghttp2/1.30.0 (compiled with 7.57.0)
SQLite: 3.22.0 (compiled with 3.21.0)
libxml2: compiled with 2.9.7
```

### Steps to reproduce the issue:

1. Just try to connect to a Nextcloud instance (untested with owncloud) over `https`.
2. Add the flags `--log-level 6 --log-file /dev/stdout`.
3. Watch the debug messages and see there is the error message:
```
Loading URLs from ownCloud News...[2018-03-21 20:26:46] CRITICAL: ocnews_api::query: connection error code 60
```
4. Replace the `ocnews-url` with the same url only with `http` instead of `https` and see you can authenticate just fine.

### Other info you think is relevant:

My Nextcloud instance sits on a VPS with an SSL certificate issued by [Lets Encrypt](https://letsencrypt.org). I'm not sure but I think it could be because the certificate is not trusted according to the certificates installed on my machine although I have it issued for a long time now. perhaps it has to do something with the way the certificates are update on my distro (Arch Linux).

**Comment by Minoru** [comment]
Thanks for a nice report! Error code 60 [means](https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLESSLCACERT) the certificate couldn't be verified. (Newer versions of Newsboat would turn numeric codes into explanations automatically.)

First of all, try unsetting [`ssl_verifypeer`](https://newsboat.org/releases/2.10.2/docs/newsboat.html#ssl-verifypeer).

To ensure the problem is really with your system at large, try `curl https://your_nextcloud_instance_address`. It should fail with the same code 60. If it does, you need to update your certificates package (probably named "ca-certificates").

If it doesn't fail, there is something weird going on—re-run `curl` with `--verbose` and post the output, I'll try to come up with some more ideas :)

**Comment by doronbehar** [comment]
It behaved just as you expected, unsetting [`ssl_verifypeer`](https://newsboat.org/releases/2.10.2/docs/newsboat.html#ssl-verifypeer) made the authentication succeed and curl also exited with error code 60.

Well I understand the problem is not related to Newsboat specifically but to my system as a whole. I'll contact the Arch Linux community on the matter because I have this certificate issued for almost 3 months now. Thanks for your guidance!

**Comment by Minoru** [comment]
Cool! When you find out what package to update, maybe mention it here for the next person who stumbles onto this.

Also, Let's Encrypt certificates are only valid for about 3 months, so don't forget to re-issue soon ;)
