### ISSUE TITLE
setlocale error when installed from Homebrew

### ISSUE THREAD

**Issue by GustavMarwin** [newsboat/newsboat#156]
**Newsboat version (copy from `newsboat -v`)**:
homebrew/Cellar/newsboat/2.11 (33 files, 3.2MB) *
  Built from source on 2018-03-29 at 19:53:14

Steps to reproduce the issue:

1. brew install newsboat

2. run newsboy

3. setlocale failed: No such file or directory

**Comment by Minoru** [comment]
Hello!

Did you have Newsboat or Newsbeuter installed and working before?

If it's the first installation, show the output of `echo $LANG`. See akrennmair/newsbeuter#483 for details.

If you've upgraded, please tell me what version (and what program :) you had before.

**Comment by GustavMarwin** [comment]
LANG=en_US.UTF-8 newsboat worked perfect, thank you!

**Comment by jacwah** [comment]
I have the same issue and can confirm that setting `LANG` is indeed a workaround, as was changing region to US. I decided to try to figure out why it was not working.

```
$ env | grep LC
LC_CTYPE=UTF-8
$ echo $LANG

$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

This configuration seems fine to me. `LC_*` defaults to `LANG`, which according to `man locale` defaults to `C`.

According to my man page on `setlocale`, *"An argument of `""` will determine the name of the new locale taking into account the environment variables `LANG` and `LC_*`"* and *"The `setlocale()` function returns `NULL` and fails to change the locale if the given combination of category and locale makes no sense"*. I wrote a small program to see if I could reproduce the `NULL`:

**tl.cpp**
```c++
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <locale.h>

int main()
{
    printf("At init:\n");

    char *plc = setlocale(LC_CTYPE,NULL);
    printf("LC_CTYPE: %s\n", plc);
    perror("LC_CTYPE");
    errno = 0;

    char *plm = setlocale(LC_MESSAGES,NULL);
    printf("LC_MESSAGES: %s\n", plm);
    perror("LC_MESSAGES");
    errno = 0;

    char *pla = setlocale(LC_ALL,NULL);
    printf("LC_ALL: %s\n", pla);
    perror("LC_ALL");
    errno = 0;

    char *lang = getenv("LANG");
    printf("LANG: %s\n", lang);

    printf("\nSetting to native:\n");

    char *nlc = setlocale(LC_CTYPE,"");
    printf("LC_CTYPE: %s\n", nlc);
    perror("LC_CTYPE");
    errno = 0;

    char *nlm = setlocale(LC_MESSAGES,"");
    printf("LC_MESSAGES: %s\n", nlm);
    perror("LC_MESSAGES");
    errno = 0;


}
```

**Testing it**
```
$ c++ tl.cpp -o tl
$ ./tl
At init:
LC_CTYPE: C
LC_CTYPE: Undefined error: 0
LC_MESSAGES: C
LC_MESSAGES: Undefined error: 0
LC_ALL: C
LC_ALL: Undefined error: 0
LANG: (null)

Setting to native:
LC_CTYPE: UTF-8
LC_CTYPE: Undefined error: 0
LC_MESSAGES: C
LC_MESSAGES: Undefined error: 0
```

My test program succeeds in setting the locale. I get similar results on my Linux machine as well.

So what differs between the test program and newboat? I started to suspect `gettext` and `libintl`... Sure enough, `libintl` exports a `setlocale` symbol, and tracing the program showed that version was called. The gettext sources actually have a helpful comment regarding this "feature": *"Override setlocale() and newlocale() so that when the default locale is requested (locale = "") and no relevant environment variable is set, the locale chosen by the user is used. This matters on MacOS X 10 and Windows."*

It appears the gettext version of `setlocale`, when faced with an unset `LC_` and `LANG,` decides to go looking in exotic places for the native locale and promptly fails without fallback if the Language/Region settings in macOS do not have a matching locale defined. This seems like an upstream bug.

---

Taking this into account, maybe newsboat should not exit when `setlocale` fails, at least on macOS. This causes problems for many users in the default setup. The point of using gettext in the first place is to accommodate users from non English speaking regions of the world.

I've tried to survey how other applications on Homebrew using gettext are handling `setlocale`, and the two I looked at (Gedit and httping) are both ignoring the return value.

**Comment by Minoru** [comment]
Wow, thanks for such a thorough analysis, @jacwah! At your prompt, I went and looked at some TUI programs I use—[mcabber](https://github.com/McKael/mcabber/blob/e2c4cac7f9d0319973fc5414563664859e231e1f/mcabber/mcabber/screen.c#L772), [irssi](https://github.com/irssi/irssi/blob/0c1db8f2aee4aa5040a16518adb71f57dc953985/src/fe-text/irssi.c#L320), [vim](https://github.com/vim/vim/blob/6f4700233fd925fe122b851f937929fb5e5da707/src/main.c#L1543), [mutt](https://gitlab.com/muttmua/mutt/blob/master/main.c#L618). They all ignore the return value. (NeoMutt and NeoVim do, too). I'll push the same change in a moment. Thank you once again!
