### ISSUE TITLE
boomkark-cmd passes characters after last / in url to bookmark script (as $2) instead of feeds article title when bookmarking non-main urls

### ISSUE THREAD

**Issue by BombchuLink** [newsboat/newsboat#1563]
Self explanatory title is self explanatory.

I'm fairly certain this was a design choice originally (Because someone would have to have passed something (or nothing!) to it originally.) But it is at the very least, misleading.

Also if you want the data after the last / you can just use ``sed`` or ``cut`` and save as $file_name or something.

```bash
url="$1"
title="$2"
description="$3"
feed_title="$4"
file_name="$( echo $1 | sed 's/^.*\///' )"
```

With this, I kindly ask for all urls in a article to pull the article title when bookmarking, instead of just the main url.

**Comment by Minoru** [comment]
> But it is at the very least, misleading.

Hmm. [The docs](https://newsboat.org/releases/2.23/docs/newsboat.html#_bookmarking) talk about "the title of the current selection", so I can see that you could've understood "selection" as "article", not "the currently highlighted line in the URLs list". I don't see what can be misleading here, but I can certainly understand why the behaviour might be surprising if you only bookmarked articles before and got used to having *their* title as a second parameter.

As for the design choices behind this: I dug up the history. [Originally](https://github.com/newsboat/newsboat/commit/2fee54c4ebb3faf23c408b4942ff59011c5678ff) bookmarks in URL view had no title. [Much later](https://github.com/akrennmair/newsbeuter/pull/21) the current "guessing" logic was added. Since then, this parameter didn't change. So it appears that from the start, the idea was that all the parameters passed to the script are about the specific URL, not its context.

I guess we broke that when, much later, we added a feed title as a fourth parameter.

I wouldn't dare change the meaning of an *existing* field, though. Instead, I'd lump this issue into #1554: instead of changing existing fields, let's just provide *all* the info we can via a file, and let the bookmark-cmd pick whatever it needs from there.

I'll close this issue now. Let's continue in #1554.
