### ISSUE TITLE
New filter parser

### ISSUE THREAD

**Issue by jacwah** [newsboat/newsboat#162]
There has been some issues with Coco/R (#43, #159) and it is not actively maintained any more. The filter code should be ported to another framework. This has been discussed before: akrennmair/newsbeuter#299. 

The most common lexer and parser generators are bison and flex, and they are probably the best supported cross platforms (aside from POSIX yacc and lex). That is at least what I have used before. I'll be glad to hear other suggestions as well!

**Required features:**
* Parse from string
* Interface with C++
* Well supported across platforms
* Actively maintained
* Thread-safe?

**Comment by Minoru** [comment]
Don't forget the Unicode support! :)

My experience with parsers is limited to parser combinators (not in C++, though) and hand-crafted stuff (which I'd rather avoid because it's harder to get right and maintain). I'd pick parser combinators if at all possible, but it seems that C++ world doesn't have a maintained implementation at the moment.

I took a brief look at Boost.Spirit and [PEGTL](https://github.com/taocpp/PEGTL), but they both obscure the grammar by C++ noise. This will require some creative indentation to be readable, which conflicts with my wish to have an automatic code formatting at one point. Boost also represents a massive dependency, which is bad.

I guess bison and flex are the only viable alternative, then. I'm not familiar with them, and looking at examples in the docs, I'm not looking forward to making an acquaintance, but I'll manage—we don't change the parser very often. Would you like to implement it?

**Comment by jacwah** [comment]
Yeah I've started experimenting a bit. Bison and flex code is not exactly elegant, but they are very well supported and used. I'll report back when I've got something running.

**Comment by jacwah** [comment]
I started doing some research, but have now realized I won't have time to do this, at least in the foreseeable future. Hopefully some one else wants to pick it up instead.

After looking more at the available solutions, perhaps the easiest path is to just hand write a parser. The filter language is not very complicated so I don't think it would be much more code than using a framework really.

**Comment by Minoru** [comment]
No problem; thanks for keeping me in the loop!

I'm slightly worried about maintainability of handwritten parsers, but it's hard to argue in abstract. Let's wait and discuss that again when someone decides to work on an implementation.

**Comment by Minoru** [comment]
This has been superseded by #631, which will be fixed by #701, so closing.
