### ISSUE TITLE
How to toggle source view everytime you enter an article

### ISSUE THREAD

**Issue by pal-wal** [newsboat/newsboat#1670]
Some feeds like youtube feeds look better in source view so how does one configure newsboat to display the source of an article by default.

**Comment by Minoru** [comment]
You can't. YouTube looks better that way because it uses plain-text, which Newsboat didn't support. It's now fixed, and starting with 2.24 plain-text will be supported; this release comes out this weekend.

As a workaround, if all your feeds are YouTube, you can set `html-renderer cat`.

Does that resolve the issue?

**Comment by pal-wal** [comment]
oh yes it does.
thanks!
