### ISSUE TITLE
Does `print-unread` have to respect the cache.db.lock?

### ISSUE THREAD

**Issue by szigetva** [newsboat/newsboat#1702]
Does `newsboat -x print-unread` have to respect the lock on the database?  I guess it's just reading, not writing it.  (My i3 bar displays the result of this command, but stops when newsboat itself is running.)

**Comment by Minoru** [comment]
That's a good question. I can imagine two situations in which the lock is important for `print-unread`:

1. some remote APIs require the user to set `cookie-cache`, which is just a file. If two processes edit that file simultaneously, the result will be unpredictable, and can break both processes;
2. if you start Newsboat, then install a newer version, and then run `newsboat -x print-unread`. the newer version might try to upgrade the database, again leading to unpredictable results and breakage.

Both of these are pretty niche though. On the other hand, there can be more that I didn't think of. If we do away with the lock, it'd scare me a bit because for each line in `main()`, I'd have to think if it's okay to run it from two processes simultaneously — not an easy task.

Perhaps we should adopt a limited version of #471 where `print-unread` connected to a running process and asks it for the number.
