### ISSUE TITLE
Newsboat doesn't read $XDG_CONFIG_HOME unless a newsboat folder exists inside it

### ISSUE THREAD

**Issue by ifohancroft** [newsboat/newsboat#1706]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: Newsboat 2.24.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
None
```

Steps to reproduce the issue:

1. Set $XDG_CONFIG_HOME to a directory in your home directly that exists and is readable and writable by you (preferably the .config directory in your home directory)

2. Make sure the env is readable in the terminal your are going to execute `newsboat` AND a folder `newsboat` does NOT exist in $XDG_CONFIG_HOME AND that there is no urls file under ~/.newsboat/

3. Execute `newsboat`

I am opening an issue instead of a PR as I believe it's not the documentation that's wrong but newsboat. What the documentation says, that if $XDG_CONFIG_HOME exists, newsboat will make its own folder there, I believe should be the actual behavior.

**Comment by ifohancroft** [comment]
This is not the same issue, but still related to newsboat's XDG Dir usage: According to the documentation, newsboat would place the cache file under $XDG_DATA_HOME. It should utilize $XDG_CACHE_HOME for that instead.

**Comment by Minoru** [comment]
Ah, I see. Docs are wrong. When I say "XDG config directory" here:

> If the XDG config directory exists, Newsboat will use XDG directories, creating the data directory if necessary. Otherwise, it will default to ~/.newsboat.

I mean `$XDG_CONFIG_HOME/newsboat`, not `$XDG_CONFIG_HOME`. I'll update that sentence. Thanks for drawing my attention to it!

> According to the documentation, newsboat would place the cache file under $XDG_DATA_HOME. It should utilize $XDG_CACHE_HOME for that instead.

"cache.db" is badly named; terribly! Some users even remove it to "clean up", not realizing that all their articles are in that file. So no, it should absolutely not be in `$XDG_CACHE_HOME`, it's *data*. But I should rename it in Newsboat 3, to avoid confusion.

> shouldn't the lock file use $XDG_RUNTIME_DIR instead of the cache folder?

Perhaps. It locks a specific cache file, so it makes sense to place the lock right next to the file. If we placed the lock elsewhere, we'd have to give it a name that depends on the location of the cache file it locks; otherwise, two Newsboat instances that use different caches will clash on the lock. It's probably easier to keep it next to the cache file.

Ditto for Podboat, although the situation there is less explicit (less clear what the lock file actually protects).

**Comment by ifohancroft** [comment]
> Ah, I see. Docs are wrong. When I say "XDG config directory" here:
> 
> > If the XDG config directory exists, Newsboat will use XDG directories, creating the data directory if necessary. Otherwise, it will default to ~/.newsboat.
> 
> I mean `$XDG_CONFIG_HOME/newsboat`, not `$XDG_CONFIG_HOME`. I'll update that sentence. Thanks for drawing my attention to it!

Ah! That makes sense. Also, you are welcome! And thank you for clarifying the documentation.

> > According to the documentation, newsboat would place the cache file under $XDG_DATA_HOME. It should utilize $XDG_CACHE_HOME for that instead.
> 
> "cache.db" is badly named; terribly! Some users even remove it to "clean up", not realizing that all their articles are in that file. So no, it should absolutely not be in `$XDG_CACHE_HOME`, it's _data_. But I should rename it in Newsboat 3, to avoid confusion.

Ah, yeah! Then it definitely belongs in the data directory.

> > shouldn't the lock file use $XDG_RUNTIME_DIR instead of the cache folder?
> 
> Perhaps. It locks a specific cache file, so it makes sense to place the lock right next to the file. If we placed the lock elsewhere, we'd have to give it a name that depends on the location of the cache file it locks; otherwise, two Newsboat instances that use different caches will clash on the lock. It's probably easier to keep it next to the cache file.
> 
> Ditto for Podboat, although the situation there is less explicit (less clear what the lock file actually protects).

To be honest, I am not entirely sure if I am correct that the lock file should be in the runtime directory, as I find the spec not as clear on that matter as for the rest of the stuff, however I don't see how the location can break anything. I am not familiar with how it is currently implemented, but I am guessing there is a variable that stores the location of the file and that variable is used for the lock file as well. With it going into $XDG_RUNTIME_DIR (again, I'm not certain if I'm correct that it should be there) the only thing that would change would be that the variable for location for creating and accessing the lock file would change to point to $XDG_RUNTIME_DIR and when accessing the cache file in relation to the lock file, two variables will used instead of one since they will be in two different directories. However, with the cache.db being actually data and being in $XDG_DATA_HOME, the lock file even if not in the runtime dir, should at least be in the cache.

**Comment by Minoru** [comment]
Okay, imagine that you have XDG directories and you start Newsboat. It uses the cache file from ~/.local/share/newsboat/cache.db. Now you run `newsboat --cache-file=/tmp/cache.db --url-file=/tmp/urls`, starting a second instance of Newsboat. This ia perfectly fine, since the caches are separate (these two instances will still share some files, like config and history, but those are updated rarely and thus don't cause problems).

With current approach, you'll have two locks: one in ~/.local/share/newsboat/cache.db.lock, the other in /tmp/cache.db.lock. So far, so good: separate caches mean separate locks.

Now imagine you have XDG_RUNTIME_DIR set to, say, /run/user/1000. If Newsboat were to put locks in that directory, the first instance would use /run/user/1000/cache.db.lock, and the second instance — well, it would try to use the same file! As a result, you won't be able to run two copies of Newsboat, even though they're working with different cache files.

To amend this, we could e.g. hash the path to the cache file and use that as a name for the lock. Then the first instance would use e.g. /run/user/1000/7b7eb2202f3a5cc9d136ed71e5526da9.lock, and the second one would use /run/user/1000/8156d84219693d915b68009aa0cb5674.lock, which are different files so everything would be fine again.

That's how the location can break something, and also how can we avoid breakage.

**Comment by ifohancroft** [comment]
> Okay, imagine that you have XDG directories and you start Newsboat. It uses the cache file from ~/.local/share/newsboat/cache.db. Now you run `newsboat --cache-file=/tmp/cache.db --url-file=/tmp/urls`, starting a second instance of Newsboat. This ia perfectly fine, since the caches are separate (these two instances will still share some files, like config and history, but those are updated rarely and thus don't cause problems).
> 
> With current approach, you'll have two locks: one in ~/.local/share/newsboat/cache.db.lock, the other in /tmp/cache.db.lock. So far, so good: separate caches mean separate locks.
> 
> Now imagine you have XDG_RUNTIME_DIR set to, say, /run/user/1000. If Newsboat were to put locks in that directory, the first instance would use /run/user/1000/cache.db.lock, and the second instance — well, it would try to use the same file! As a result, you won't be able to run two copies of Newsboat, even though they're working with different cache files.
> 
> To amend this, we could e.g. hash the path to the cache file and use that as a name for the lock. Then the first instance would use e.g. /run/user/1000/7b7eb2202f3a5cc9d136ed71e5526da9.lock, and the second one would use /run/user/1000/8156d84219693d915b68009aa0cb5674.lock, which are different files so everything would be fine again.
> 
> That's how the location can break something, and also how can we avoid breakage.

Ah! Sorry, I didn't take into account the case where you specify the cache file location yourself. Also, I didn't know starting two instances of Newsboat is accepted/allowed in that case.

Of course, the cache lock file would be in $XDG_RUNTIME_DIR only if the user hasn't specified the cache location themselves, and only if Newsboat is running using the XDG directories. I'm sorry, I should have said that. My idea was that if you specify the cache yourself, since it's not using XDG directories, you can't expect the lock file to follow the XDG dirs either.

That's a great topic of discussion though. Perhaps I should finally email the xdg mail list and ask about that as well as the questions I have about the other things I find unclear in the spec. For example, if you check the spec about the $XDG_RUNTIME_DIR, it lists its requirements, which tend to be quite specific, and it says that a directory with the same properties can be used as a backup if $XDG_RUNTIME_DIR is not set, however, it doesn't actually say what are implements of the spec supposed to do if a directory with such parameters/properties cannot be found
