### ISSUE TITLE
Automatically execute arbitrary command on new entries

### ISSUE THREAD

**Issue by azacock** [newsboat/newsboat#1724]
Just started using newsboat recently. Pretty slick, but there are a few features I just sort of expected to be there that weren't, and I think they'd be pretty useful.

One of those is the ability to automatically execute some arbitrary command when a new entry is found. For example, let's say I have some RSS feeds for Youtube channels. When newsboat updates those feeds, if there are new entries, I'd like it to automatically execute youtube-dl. I think the utility of this should be self-evident. I think this is similar, though not identical to how podboat works, though I haven't really delved into podboat yet so I can't really say for sure.

Apologies if this is something that's already possible. I know there's a lot of advanced hacking that can be done with newsboat's existing toolset.

**Comment by Minoru** [comment]
Hi! Thanks for trying Newsboat.

> When newsboat updates those feeds, if there are new entries, I'd like it to automatically execute youtube-dl.

Please use something like `rsstail URL | grep … | xargs youtube-dl` for that, or write a script. Newsboat is meant to be driven by human actions, and I don't plan to turn it into a base for automation. See also #1703 for ideas of how else to implement this.

**Comment by JrO5YRu9mr** [comment]
> Newsboat is meant to be driven by human actions, and I don't plan to turn it into a base for automation.

Hi, this is very useful for accessing content offline, for people who often have no internet or very weak connection. This applies to any content, such as images, videos, articles, etc. There is no need to store any states or records on the application side. It is enough, for example, to call some asynchronous command for each "query" entry:

`"query:Everyday:tags # \"work\" and unread = \"yes\":/usr/bin/command %u & "query"`

Title, url, content, etc.
It would be possible to use filter, but then all the useful functionality of newsboat is lost.

**Comment by Minoru** [comment]
I do not dispute the usefulness of this, I just don't think that this feature would be a good fit for Newsboat. The downloaded content can't be viewed in Newsboat itself, so this feature doesn't help Newsboat in any way; it just provides a platform for the user to automate some tasks. If that's the goal, then the user should try something simpler, maybe as simple as `rsstail`.

Yes, this does require re-implementing some of Newsboat features. Such is the life of software: it's either feature creep of a single solution, or duplication of effort between multiple overlapping solutions.

I understand that from the user perspective, it makes sense to run *just* Newsboat instead of two separate programs, but from the perspective of the maintainer, this is an unrelated feature that would be a liability without much benefit.

**Comment by tabell** [comment]
Another use-case for this would be to display a notification when a new article is found that actually includes information about the new article, instead of the generic "New articles are available"
