### ISSUE TITLE
Setting minimum feeds?

### ISSUE THREAD

**Issue by sjgdk** [newsboat/newsboat#174]
**Newsboat version (copy from `newsboat -v`)**: 2.11

**Other info you think is relevant**:

Any option to set minimum feeds to fetch instead of retaining maximum feeds (max-items)?

Like inoreader-min-items, oldreader-min-items

**Comment by Minoru** [comment]
Since you mention `max-items`, I assume you mean "minimum items in feeds". Due to the way RSS and Atom work, what you're asking for just isn't possible. The minimum is dictated by the publisher of the feed: if the site creates a feed with just 10 items, there's no way for Newsboat to fetch more than 10.

If that answers your question, please close the issue.

**Comment by wltprgm** [comment]
I see. Yes that answered my question. Maybe online RSS readers work in other ways to retrieve more feeds when scrolling down. 

I mean Inoreader and The Old Reader, which I have experienced with. 
Do you have any idea how they work?

**Comment by Minoru** [comment]
I don't actually know anything about online reader's internals, but I can guess. Since they have a lot of users on a single "instance" of the service, they are probably taking advantage of the fact that some other user subscribed to the same feed you're subscribing to. First Inoreader user to subscribe to a feed would see just a couple of items (as many as publisher retains), but all future users will have access to all the items that got posted since that first subscription.

Newsboat can't do that because each user runs their own "instance", with its own database of items. Theoretically it's possible to add peer-to-peer sharing of databases, but I believe we have to deal with some more mundane problems first.
