### ISSUE TITLE
Failed to sync with inoreader for youtube rss

### ISSUE THREAD

**Issue by wltprgm** [newsboat/newsboat#175]
**Newsboat version (copy from `newsboat -v`)**: 2.11

As title suggests, every other feeds from the same inoreader account are retrieved but not the youtube related one. 

It responded with the code below:
Error while retrieving https://inoreader.com/reader/atom/feed/https%3A//www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA?n=120: HTTP response code said error 400

**Comment by Minoru** [comment]
Seem to be totally Newsboat's fault: API implementations for [FeedHQ](https://github.com/newsboat/newsboat/blob/fa4dc3eeae22efc987230767803ce564ebe3b57c/src/feedhq_api.cpp#L132), [Inoreader](https://github.com/newsboat/newsboat/blob/fa4dc3eeae22efc987230767803ce564ebe3b57c/src/inoreader_api.cpp#L153) and [The Old Reader](https://github.com/newsboat/newsboat/blob/fa4dc3eeae22efc987230767803ce564ebe3b57c/src/inoreader_api.cpp#L153) all append GET parameters quite naively. It breaks if URL already contains some parameters. The proper way, I guess, would be to split the URL in parts, add a parameter and re-build the URL, akin to the way [`utils::censor_url`](https://github.com/newsboat/newsboat/blob/fa4dc3eeae22efc987230767803ce564ebe3b57c/src/utils.cpp#L846) operates.

**Comment by Minoru** [comment]
Marking as "good first issue" because the changes seem trivial and require little knowledge of Newsboat itself. Most of implementer's time will be spent on actually building Newsboat, and then testing the changes.

I think it's okay to test it on just one of the aforementioned APIs, then use the code in all other APIs.

**Comment by Minoru** [comment]
Oh, so I misunderstood the problem: the URL from the first post should look like `https://inoreader.com/reader/atom/feed/https%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUC2eYFnH61tmytImy1mTYvhA?n=120`. Thanks!

**Comment by justa9** [comment]
You're very welcome!

I think that this bug is of a somewhat elevated importance for newsboat users that have Inoreader subscriptions consisting of several hundreds of feeds, thus spanning multiple types of RSS web server implementations (I think Drupal RSS URLs include almost always "?" and "&", so currently these feeds should return 400 error through newsboat).

If @tsipinakis is listening, I would like to respectfully ask that if a fix is implemented for this, it be propagated to the ```bionic``` branch of Ubuntu as well.

Thank you again.

**Comment by aviofreak** [comment]
Hello,

I'm having the same error while retrieving RSS feed from Undeadly.org via Inoreader.

Is there some temporary work-around?

**Comment by Minoru** [comment]
@aviofreak, sorry, no; but see [my comment](https://github.com/newsboat/newsboat/issues/175#issuecomment-385708391) above—maybe you can fix it?

**Comment by aviofreak** [comment]
@Minoru I'm sorry, I can't fix it. I'm not a programmer :/

**Comment by Minoru** [comment]
I failed to notice that FeedHQ URL-encodes the feed ID before pasting it into the request URL, so FeedHQ should be immune to this. #297 adds the same encoding to Inoreader and The Old Reader.
