### ISSUE TITLE
Is it possible to go back to the previous search result list?

### ISSUE THREAD

**Issue by mbwgh** [newsboat/newsboat#1785]
Hopefully I haven't missed it in the documentation. When you iteratively refine a search by repeatedly querying the previous search result list, pressing `q` brings you back to the feed list you started out from, i.e. it goes back too far and I have to repeat my searches.
Is it possible to just go back one step to the result list of the previous search?

For example, if you go have a sequence like this

`start newsboat > go to [some feed] > search [some feed] > search [result list 1] > search [result list 2]`,

then I would like to go back to `[result list 1]` instead of `[some feed]`.

**Comment by Minoru** [comment]
It's not possible today; Newsboat doesn't keep the old set of results when it refines them.

The idea makes sense to me though, so I'll label this as "enhancement" rather than just a "question".

If we implement this, we should still keep the current behaviour available, maybe as a separate key. That way, if a user can skip back to the original feed-/itemlist without smashing <kbd>q</kbd>.

**Comment by bogdasar1985** [comment]
I will try to implement it. I'll write a report in a week at the most, if I don't implement it sooner.

**Comment by Minoru** [comment]
@bogdasar1985 Cool! This feels like a big-ish feature though, so please outline your solution before spending time on the implementation — I'd like to discuss and make sure that it fits nicely into Newsboat. Thanks!

**Comment by bogdasar1985** [comment]
@Minoru At the moment I try to implement through the creation of a private variable `std::vector<std::shared_ptr<RssFeed>> searchresultshistory;` inside `ItemListFormAction` class.

**Comment by Minoru** [comment]
Sounds good! What's your plan for adding this to other `FormAction`s that support search?

**Comment by bogdasar1985** [comment]
@Minoru I was wrong, the point is that when the search results are displayed, it creates a new ItemListFormAction object, and when we press q to exit, it destroys the ItemListFormAction object, so acting inside the ItemListFormAction object is pointless. We should look at higher level of abstraction (or callstack).

**Comment by Minoru** [comment]
> the point is that when the search results are displayed, it creates a new ItemListFormAction object, and when we press q to exit, it destroys the ItemListFormAction object

Only the first <kbd>/</kbd> keypress does that. Once you're looking at search results, additional searches stay in the same `ItemListFormAction`. I actually liked your idea of keeping a vector of resulting feeds, because it made it easy to exit back to the original feed with a single <kbd>q</kbd> keypress. I thought we'd have a new operation (and key) to go back to the previous search without exiting current `ItemListFormAction`.

The higher level of abstraction would be [the dialog management system](https://newsboat.org/releases/2.27/docs/newsboat.html#_advanced_dialog_management). If we created a new `ItemListFormAction` for each search, the users would have been able to navigate back and forth with <kbd>^G</kbd> and <kbd>^V</kbd>. They would also get a chance to create a "tree" of searches, instead of a list. This is quite powerful and enticing, but I don't see how to implement "close all searches and go back to the original feed" in this case.

I'd keep with your original idea.

**Comment by bogdasar1985** [comment]
> Only the first / keypress does that. Once you're looking at search results, additional searches stay in the same `ItemListFormAction`.
No, I checked this in GDB. Constructor calls after every search request(first or not, not important) and destructor call after every `q` and after every new search response, instead first.

**Comment by Minoru** [comment]
Hmm, you're right; `View::push_searchresult()` creates a new `ItemListFormAction`. It's been that way [for a long time](https://github.com/newsboat/newsboat/commit/d505c3557bb112eea534f09d04bdaf40549c09ed) too. I don't know why it's done that way; perhaps to avoid writing two slightly different implementations for feed- and itemlists?

Okay, here's an alternative idea: derive a new dialog type, `SearchResultsFormAction`, from `ItemListFormAction`. In it, implement your original `vector<shared_ptr<RssFeed>>` idea, and make `OP_SEARCH` stay in that dialog instead of creating a new one. Change `View::push_searchresult()` to create this new dialog type instead of `ItemListFormAction`. How does that sound?

**Comment by bogdasar1985** [comment]
@Minoru I also thought to create an `std::vector<std::shared_ptr<RssFeed>>* searchresultshistory` inside `ItemListFormAction` and in every new `ItemListFormAction` object transfer ownership of this pointer to it. But I will first try your idea.

**Comment by bogdasar1985** [comment]
@Minoru So, I implement a prototype of feature in special branch here https://github.com/bogdasar1985/newsboat/tree/search_results_history_feature

Existed problems:
1. Implementation of `SearchResultsFormAction` are in one header file, because when I used separate `.cpp`\`.h` implementations it consequence to linker errors.

Go, check it. 

I didn't open a Pull Request, because I think we should not merge this feature to `master` **_yet_**. Let's develop it in separate branch, in some reasons:
1. This feature is big enough for it.
2. We haven't got a fairly clear picture of how this feature should looks like.
3. There is a many different ways to improve this feature and make it better.

**Comment by Minoru** [comment]
@bogdasar1985 Thanks! I'll take a look on the weekend.

To fix the build problem, I think you have to add src/searchresultsformaction.cpp to mk/newsboat.deps.

Please create [a draft pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) so we can discuss the code. (Drafts are meant specifically for this use-case: features that aren't ready yet.)
