### ISSUE TITLE
Suggestion: Packaged Linux releases

### ISSUE THREAD

**Issue by sunjam** [newsboat/newsboat#181]
Hi, Would it be possible to offer a pre-packaged release (such as Debian) that could cut down on the number of dependencies required to build from source, which currently require over 2gb of space.   asciibook alone carries over 1gb of Tex related dependencies.  Thanks for reading.

**Comment by tsipinakis** [comment]
If I remember correctly only the basic asciidoc packages are needed. You can do `apt install asciidoc --no-install-recommends` to cut down the installation size.

**Comment by Minoru** [comment]
By "pre-packaged", you mean only pre-built documentation, or more?

Newsbeuter had tarballs like that, but I didn't carry the practice over to Newsboat since IMHO "source tarballs" should contain "source".

**Comment by sunjam** [comment]
I miss the simplicity associated with installing newsbeuter, and would love
for newsboat to be readily available for users not building directly from
source:

Debian user installing a deb package via apt-get, aptitude, or synaptic
ubuntu user installing via Ubuntu Software Center, etc.
Or, just having a .Deb package to install that resolves all dependencies.

When installing from source I found documentation here was very sparse on
describing dependencies, but [clearer information was found here (some info
here seems to not be current and commands had to be tweaked).](
http://www.linuxhostingprovider.com/how-to/newsboat-a-terminal-based-rssatom-feed-reader/
)

**Comment by Minoru** [comment]
I understand the sentiment, but this request is presented to the wrong people. We're *developing* Newsboat, not *distributing* it. We're releasing tarballs with source code, and packagers (usually maintainers in distributions) turn it into binaries that are shipped to you via `apt-get`, `pkg`, `brew` etc.

Newsboat is less than a year old, so it's only packaged for newer distro releases. [Ubuntu Bionic Beaver](https://packages.ubuntu.com/search?keywords=newsboat&searchon=names&suite=bionic&section=all) has it, while Debian only has it [in *testing* (Buster)](https://packages.debian.org/search?suite=buster&section=all&arch=any&searchon=names&keywords=newsboat). I've also heard of packages in Homebrew, MacPorts, and various BSDs. There is also a Snap package that can be installed in different distros, including pre-18.04 versions of Ubuntu and (presumably) older Debian releases.

> some info here seems to not be current and commands had to be tweaked.

This is *precisely* why our own README is so sparse on describing dependencies: had we written any commands or package names, we'd have to keep it up to date, and inevitably would have fallen short of it. There's also more distros that one can count, and listing packages for them all is a fool's errand. Since we don't even have enough manpower for development itself, I gladly circumvented the problem by not listing any packages at all.

The best course of action for you is probably to install Snap now, then migrate to a native package once you upgrade to a recent enough release of your Linux distribution (or whatever you're running).
