### ISSUE TITLE
The file explorer didn't recognize the right filetype

### ISSUE THREAD

**Issue by sebastianrakel** [newsboat/newsboat#184]
**Newsboat version (copy from `newsboat -v`)**: b59ef97d

The file explorer didn't recognize the right filetype, regular file and directory is working, but nothing else.

**Comment by Minoru** [comment]
Some reproduction steps would've helped; I only understood what the issue was about once I read the code in #185.

Anyway, I came up with these while checking #185:

1. make sure you have a directory with at least one of each: a regular file, a directory, a symlink;
2. make sure you have at least one article in Newsboat;
3. open an article and press `s` to save it;
4. in filebrowser dialog that opens, note the leftmost column: it starts with `-` for regular files, and with `d` for everything else, *including symlinks*.

The expected behaviour is that for symlinks, the leftmost column starts with `l`.
