### ISSUE TITLE
Ability to snooze feed

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#1844]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Newsboat 2.25.0
System: Linux 5.4.0-88-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.79.1 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 librtmp/2.3 OpenLDAP/2.5.8 (compiled with 7.79.0)
SQLite: 3.36.0 (compiled with 3.36.0)
libxml2: compiled with 2.9.12

# Feature Description

- May be we can snooze a particular RSS feed for a number of days (that could be defined in config file), by executing a shortcut from the TUI (terminal user interface). 
- May be the shortcut, could write the date till which the RSS field should be snoozed in URL file. 
- And when the newsboat is started it could filter out snoozed feeds.

**Comment by Minoru** [comment]
Let's start with a use-case :) Can you describe the situation that made you desire such a feature?

**Comment by anishmittal2020** [comment]
# Use Case

This channel [Geography Now - YouTube](https://www.youtube.com/c/GeographyNow/videos) used to make meaningful videos about geography of various countries. Recently, they have been posting a lot of random travel videos. I would like to snooze it for some days (may be 30 days) because the new videos are annoying. If they keep on doing the same thing after the snooze period, I would remove them from my url list or may be consider snoozing again

**Comment by Minoru** [comment]
Got it, so it works exactly as if I tagged a feed with a hidden tag. I wonder if this is worth the implementation effort then. Can't one just add a tag and set oneself a periodic reminder to look through hidden feeds and unsubscribe from the ones that aren't interesting anymore?
