### ISSUE TITLE
Special handler for images/video on Links: section

### ISSUE THREAD

**Issue by duarm** [newsboat/newsboat#1954]
Newsboat r2.26-11-g8805d

Hello!

## Problem
I make extensive use of the `Links:` section in articles from certain feeds. Lots of `<image>` and `<video>` tags,  I set the `browser` to a script which interprets the links and opens with the appropriate program if it ends with jpg or mp4 for example. 

This works almost well, but I have lots of feeds which output urls in tags with no strict pattern, they for example place an image link in the `<image>` with the url _site.com/qwve8rq9_. There's no pattern here to conclude it's an image. A more concrete and common example:
https://nitter.net/pic/card_img%2F1485949394088509449%2FY59WrsOs%3Fformat%3Djpg%26name%3D800x320_1
(sites usually serve the encoded filename of the file)

I would like to open these with the appropriate program depending on the tag.

## Solution
The solution I found is: A special handler for handling links depending on the rss tag. We have a `browser` handler which handles all links. This is nice and mostly works, but because it's an `<image>` or `<video>` tag, I would like to send it directly to an image-viewer/video-player handler to cover these exceptions.

the config would have:
```
browser link_handler.sh
image-viewer feh
video-player mpv
```

if image-viewer or video-player s not set, it falls back to browser to preserve current configs, a browser is also a nice fallback since it can handle everything.

**Comment by Minoru** [comment]
Sorry about the delayed response! Took me a while to find enough energy to think through this.

I don't think that the "viewer" should depend only on the type of the link. Consider a YouTube URL: most likely you'd want it to be opened in mpv, even if it was in an `<a>` tag rather than a `<video>` tag. I don't want to bake that decision into Newsboat though, because it's also possible that one really does want it to open in the browser if it's a hyperlink.

How about adding a new placeholder into the `browser` setting, say `%t`? It would expand to the type of the link. The browser is then free to decide how to display it. Compared to your proposed solution, this requires a more advanced configuration (as it involves scripting), but OTOH we don't have to provide settings to account for all the corner cases.

Do you see any downsides to this approach?

**Comment by duarm** [comment]
>  don't want to bake that decision

fair enough, not sure why I didn't thought about a new placeholder

%t is a better solution.

I'll probably find time to help with this next week, if it's not already done by then, thanks @Minoru.
