### ISSUE TITLE
Newsboat doesn't detect some enclosures

### ISSUE THREAD

**Issue by 9948aa9a** [newsboat/newsboat#2050]
**Newsboat version 2.27.0**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
No config
```

Steps to reproduce the issue:

1. Add https://www.whatbitcoindid.com/podcast?format=RSS to urls.

2. Reload newsboat and enter into an article.

3. You can't find the MP3 enclosure at the end, on the URL's list. Also, if you press U, you can't find it. 

**Other info you think is relevant**:
Maybe it happens because the enclosure doesn't have a type. Example:
```html
<enclosure url="https://chtbl.com/track/282487/traffic.libsyn.com/secure/whatbitcoindid/WBD495_-_Dan_Held.mp3" length="62,447,386"/>
```

**Comment by Minoru** [comment]
You're right, it's ignored because there is no `type` attribute:

https://github.com/newsboat/newsboat/blob/78506f2fbb5c1c6af8ff8405781a79d7c645d703/rss/rss09xparser.cpp#L115-L120

It's also curious that the feed says it's RSS 1.0, but [RSS 1.0 spec](https://web.resource.org/rss/1.0/spec) doesn't actually mention `<enclosure>`. This tag was only added in RSS 2.0, and [all three of `url`, `length`, and `type` are required(https://validator.w3.org/feed/docs/rss2.html#ltenclosuregtSubelementOfLtitemgt).

So Newsboat is *technically* correct, but I still think it could do better :) Current algorithm is to pick the last enclosure of the supported type. I guess it could be changed to pick the last enclosure (regardless of the type) if the existing algorithm hasn't picked anything. This can obviously lead to suboptimal results, e.g. if the MP3 enclosure is followed by JPEG cover art, but it resolves at least *some* situations, including this particular feed.

It would be good to also contact the site administrator and tell them that their RSS feed is malformed. They can validate the feed over at https://validator.w3.org/feed/

**Comment by 9948aa9a** [comment]
> You're right, it's ignored because there is no `type` attribute:
> 
> https://github.com/newsboat/newsboat/blob/78506f2fbb5c1c6af8ff8405781a79d7c645d703/rss/rss09xparser.cpp#L115-L120
> 
> It's also curious that the feed says it's RSS 1.0, but [RSS 1.0 spec](https://web.resource.org/rss/1.0/spec) doesn't actually mention `<enclosure>`. This tag was only added in RSS 2.0, and [all three of `url`, `length`, and `type` are required(https://validator.w3.org/feed/docs/rss2.html#ltenclosuregtSubelementOfLtitemgt).
> 
> So Newsboat is _technically_ correct, but I still think it could do better :) Current algorithm is to pick the last enclosure of the supported type. I guess it could be changed to pick the last enclosure (regardless of the type) if the existing algorithm hasn't picked anything. This can obviously lead to suboptimal results, e.g. if the MP3 enclosure is followed by JPEG cover art, but it resolves at least _some_ situations, including this particular feed.
> 
> It would be good to also contact the site administrator and tell them that their RSS feed is malformed. They can validate the feed over at https://validator.w3.org/feed/

I didn't know those details. I'll contact the site administrator. Thank you!
