### ISSUE TITLE
Old article marked as new

### ISSUE THREAD

**Issue by ffaf1** [newsboat/newsboat#2051]
**newsboat 2.21.0 - https://newsboat.org/**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# delete old articles
max-items 50

# delete old searches
history-limit 20

# needed to trick google (forbidden wget)
user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:6.0.1) Gecko/20110831 conkeror/0.9.3"

# set error log
error-log "~/.newsboat/error.log"

# enviroment vars
# feed-sort-order firsttag

show-read-feeds no

auto-reload yes
reload-time 1000
reload-threads 3
download-timeout 60

cookie-cache ~/cfg/newsbeuter/cookies.txt
```

Steps to reproduce the issue:

1. add this feed to your `urls` http://joeyh.name/blog/index.rss

2. reload it

3. wait a bit (24h?) the top article will be marked again as “new”. 

**Other info you think is relevant**:

if you `wget http://joeyh.name/blog/index.rss` at two different times and `diff` them, they are the same.

**Comment by Minoru** [comment]
I'm subscribed to the same feed and I haven't noticed this problem. But I'm subscribed via HTTPS, running difference Newsboat version and obviously have a different config. Interesting!

I built 2.21 and fetched the feed just now. Will do that again tomorrow to see if I can reproduce this.

Thanks for the report!

**Comment by Minoru** [comment]
I haven't managed to reproduce this over the last month. I had a suspicion that this might be due to me having less than 50 items, so I copied them from my own database, but that didn't help.

One thing you could do to help track this down is to run Newsboat with flags `--log-file=newsboat.log --log-level=6`. There is a lot of output, so your Newsboat will be a tad slower, and the file will get quite big. Just remove it from time to time, and restart Newsboat. Once you've observed the bug, please post the log, or at least the portions that mention joeyh.name. The log includes the responses that Newsboat got, and hopefully it'll show why Newsboat is getting confused.

**Comment by Minoru** [comment]
I might have been unclear: you have to run `newsboat --log-file=newsboat.log --log-level=6` *all the time*. Otherwise when you observe the bug, there will be no log to study.

Also, did you observe the bug this past month?

**Comment by Minoru** [comment]
Hey @ffaf1, how it's going? Did you observe the bug lately?

**Comment by ffaf1** [comment]
Unfortunately no! I mean, I use newboat daily but did not observe the bug, weird! Please close this, I will reopen if it happens again. Thanks for your help!

Il 09 luglio 2022 alle 03:05 Alexander Batischev ha scritto:

**Comment by ffaf1** [comment]
I did *not* observe it again unfortunately (or: fortunately).

Il 09 giugno 2022 alle 11:50 Alexander Batischev ha scritto:
