### ISSUE TITLE
"content" in ignore-article rule doesn't work

### ISSUE THREAD

**Issue by unam3** [newsboat/newsboat#218]
newsboat 2.11.1

Steps to reproduce the issue:

- Put next lines into config :
```
ignore-article "*" "content =~ \".*foo.*\""
ignore-mode "display"
```

- Start newsboat

- Articles with `foo` in content still in the feeds

**Comment by kmws** [comment]
Perhaps somewhat connected to #111?

**Comment by Minoru** [comment]
Reproduced. Judging by the log, `content` field simply doesn't get populated before ignores are checked. A few solutions come to mind:

* just read `content`s on startup. Don't like this idea because it'll force us to read the whole DB into memory on startup. We've got enough performance problems already;
* arrange it so that `rss_item` loads its contents automatically if matcher rule requests that field. I foresee some problems with resource management here, because we won't know when it's safe to drop the content—it might still be needed by some dialog after rule is matched.

Sorry, @unam3, I don't know when I'll be able to fix that. As a workaround, you can either:
* use `ignore-mode "download"` (but that'll kill the articles for good); or
* use query feeds to filter out the stuff you don't see (but that won't scale if you have a lot of feeds or a lot of stuff you don't want to see).

**Comment by unam3** [comment]
@minoru, It's seems like second proposed workaround deosn't work too:
```
ignore-article "*" "content =~ \".*foo.*\""
ignore-mode "download"
```
After updating feeds articles with `foo` still will be downloaded.

**Comment by Minoru** [comment]
I just checked with an empty cache, and it does work. Note that `ignore-mode "download"` doesn't affect things that are already in your cache.db—only *new* articles will be put through the filter.

You can verify that by creating an Atom or RSS file somewhere on your disk and adding it to Newsboat with a URL like `file:///home/unam3/feed.atom`. You update it in Newsboat and observe how many articles you got. Then you add another entry to the file—an entry that matches the filter—and update in Newsboat again. Since it matches, you *shouldn't* see the entry in Newsboat.
