### ISSUE TITLE
Possibility to block youtube shorts

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2248]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.29.0
System: Linux 5.17.0-1019-oem (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.50.0 librtmp/2.3 (compiled with 7.85.0)
SQLite: 3.39.4 (compiled with 3.39.4)
libxml2: compiled with 2.10.3

---

Is it possible to block youtube shorts or filter out from RSS feeds  video with certain defined length (such as less than 2 minutes)?

May be its possible to have a special treatment of youtube video feeds? youtube-dl could be used to extract the duration of the video and that can be displayed in the feed. This can be helpful to remove the shorts. May be this can be done while loading the feed  and the output of the youtube-dl can be stored in the cache of newsboat?

**Comment by der-lyse** [comment]
If you're using the original YouTube feeds, then you're out of luck, since the feeds do not contain the video lengths. I create my own feeds based on the original ones. Coincidentally, [I've written an article last week on how that works](https://lyse.isobeef.org/online-video-setup/) in a bit more detail. It's a manual process though, but it could be automated to drop videos from the rewritten feed automatically if they are too short. Hope that gives you some kind of inspiration.

**Comment by hiltjo** [comment]
It is not always the case, but many Youtube channel feeds with shorts have the text "#shorts" in the description.
You could maybe filter them using the newsboat filter: functions.

https://newsboat.org/releases/2.21/docs/newsboat.html#_scripts_and_filters_snownews_extensions

Hope this helps,

**Comment by Minoru** [comment]
I'd prefer not to put site-specific hacks into Newsboat. Please use [`filter:`](https://newsboat.org/releases/2.29/docs/newsboat.html#_scripts_and_filters_snownews_extensions) for this. Lyse's article has some useful bits, like using a cache to avoid fetching the durations over and over again. Finally, if you do create such a filter, consider submitting a pull request to add it to the contrib/ directory so other users can use it too.

**Comment by lvgrr** [comment]
Hey, I noticed that recently Youtube has started using a different URL for shorts inside RSS feeds. Specifically the path of the URL begins with `shorts` instead of `watch`.

To filter out shorts, one can thus use a rule like the following
```
ignore-article "*" "link =~ \"youtube\.com/shorts\""
```

However this won't affect shorts that were published prior to the change in URL format.
