### ISSUE TITLE
$-delimited LaTeX to unicode

### ISSUE THREAD

**Issue by casparvitch** [newsboat/newsboat#2253]
Feeds from scientific journals commonly use dollar sign delimited LaTeX strings in the title field.
How possible do you think it would be to implement a LaTeX math -> unicode parser in newsboat?

Example title:
```
Unusual dimerization and magnetization plateaus in $S$ = 1 skew chain ${\mathrm{Ni}}_{2}{\mathrm{V}}_{2}{\mathrm{O}}_{7}$ observed at 120 T
```

**Comment by Minoru** [comment]
Please use [`filter:`](https://newsboat.org/releases/2.29/docs/newsboat.html#_scripts_and_filters_snownews_extensions) for this. If you do create such a filter, please submit a pull request to add it to the contrib/ directory so other users can benefit from it too.

I don't want to put this into Newsboat proper because: 1) RSS standards don't even agree if HTML is allowed in titles. Auto-detecting LaTeX markup would be a chore or resource hog; 2) this is a fairly niche feature which would require depending on some LaTeX implementation, which just seems absurd.
