### ISSUE TITLE
bug: pressing o to open an article in browser prints weird error and breaks newsboat

### ISSUE THREAD

**Issue by codymikol** [newsboat/newsboat#2274]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.21.0
System: Linux 5.15.0-56-generic (x86_64)
Compiler: g++ 10.2.1 20201207
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13 (compiled with 7.72.0)
SQLite: 3.37.2 (compiled with 3.34.0)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

Neither of these exist, is this something that only exists if you add it?

```
If you try to open articles from some sites using the o keyword, and error is printed inline and you then need to press q to recover.
```

Before pressing o

![image](https://user-images.githubusercontent.com/13606342/205508038-78b1f80d-3900-44fb-ab19-ab49cfc63cff.png)

After

![image](https://user-images.githubusercontent.com/13606342/205508049-8b264b27-3600-419b-bad4-98cd2ab7bb85.png)

Steps to reproduce the issue:
 
1. try to open this xkcd article with o

2. Borked

**Other info you think is relevant**:

Default browser is chrome, on ubuntu - jammy jellyfish

**Comment by dennisschagt** [comment]
Oops, overlooked this issue.
Instead of pressing q, you can press Ctrl+L to force a full redraw of the Newsboat UI.

> > Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

> Neither of these exist, is this something that only exists if you add it?

Yes, newsboat does not create a config file automatically.
Running `newsboat -h` will show you where it is looking for the urls/config file and where it stores the cache file.

Regarding the text written on top of newsboat, that is probably written by Chrome.
As mentioned, you can use Ctrl+L to force a redraw of the screen.

Alternatively, you could try to redirect chrome's output to /dev/null.
For some example browser configuration, see https://newsboat.org/releases/2.30.1/docs/newsboat.html#_separating_browser_from_newsboat (note that the `open-in-browser-noninteractively` command is only available since newsboat v2.23, but the other options still might make sense)

I'm closing this issue now as I believe this issue either doesn't exist in newer versions of Newsboat, or it is more of an issue with Chrome printing to the terminal after returning control to Newsboat.
However, if anything is unclear, feel free to reply and/or reopen.
