### ISSUE TITLE
Data loss observed in importing data from Mastodon RSS Feeds

### ISSUE THREAD

**Issue by sgharms** [newsboat/newsboat#2305]
Hello, I'm seeing the following data loss for subscriptions to RSS publications of Mastodon users' feeds. My goal is to make newsboat my primary interface into Mastodon. Here's a Mastodon page:

Behold, the adoable Latin-language account for the mouse Minimus:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/50019/210044671-25f0f48d-eb57-4f64-a209-0d527f0bf6b1.png">

For copy/paste ease, the URL is: https://archaeo.social/@Minimus/109597925165056089

This article shows up in Newsboat like:

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/50019/210044747-ce5e8ad8-6da0-45d1-972d-0ac29a4e4728.png">

Note, there's no hint of the `<img>` payload 😢 

Viewing the source with `^U` just shows the same text content but with the wrapping `<p>` tags. Using the `show-urls` function does not see a URL that points to the image.

Checking the cache database:

```sql
sqlite> SELECT * FROM rss_item WHERE url='https://archaeo.social/@Minimus/109597925165056089';
10329|https://archaeo.social/@Minimus/109597925165056089|109597925165056089||https://archaeo.social/@Minimus/109597925165056089|https://archaeo.social/@Minimus.rss|1672331621|<p>Time to start writing those thank you letters, Minimus!</p>|0|||0||0||
```

OK, so in the cache there is clearly no mention of the image. However, if I go to:

https://archaeo.social/@Minimus.rss and extract the raw XML for this post:

```xml
    <item>
      <guid isPermaLink="true">https://archaeo.social/@Minimus/109597925165056089</guid>
      <link>https://archaeo.social/@Minimus/109597925165056089</link>
      <pubDate>Thu, 29 Dec 2022 16:33:41 +0000</pubDate>
      <description>&lt;p&gt;Time to start writing those thank you letters, Minimus!&lt;/p&gt;</description>
      <media:content url="https://mstdn.archaeo.social/media_attachments/files/109/597/921/900/998/086/original/fe1c399c59936269.jpeg" type="image/jpeg" fileSize="376093" medium="image">
        <media:rating scheme="urn:simple">nonadult</media:rating>
        <media:description type="plain">Minimus, the Latin mouse, writing on a wax tablet</media:description>
      </media:content>
    </item>
```

Following the `<media:content>` tag's `url` attribute leads to the sought image, https://mstdn.archaeo.social/media_attachments/files/109/597/921/900/998/086/original/fe1c399c59936269.jpeg

So this leads to the questions:

1. Should Newsboat pull and integrate this content?
2. (_OR_) Is this an aberration in the RSS feed Mastodon is publishing?
3. (_OR_) Is there a configuration error / use error on my part?

*Update* Attempted to diagnose. C++ is not a language I know, but here's the best I can trace:

1. Item parsing is done here: https://github.com/newsboat/newsboat/blob/master/rss/rss09xparser.cpp#L55 with the 2.0 parser being a thin wrapper over the 09 parser.
2. The node parser looks for nodes within `<item>` like `description`, `title`, `link`, etc. but it's certainly not looking for a `<media:content>` tag
3. It appears while iterating through the tags, `<media:content>`  is dropped. It seems like it _should_ be detected as part of the [call](https://github.com/newsboat/newsboat/blob/master/rss/rss09xparser.cpp#L124-L126): `else if (is_media_node(node)`

**Comment by sgharms** [comment]
Working through the test cases, I see:

```xml
<item>
    <comments>http://example.com/blog/this_is_an_item.html#comments</comments>
    <author>blog@synflood.at (Andreas Krennmair)</author>
    <pubDate>Fri, 12 Dec 2008 02:36:10 +0100</pubDate>
    <guid isPermaLink="false">http://example.com/blog/this_is_an_item.html</guid>

    <media:description type="html">media html content</media:description>
    <media:title>using multiple media tags</media:title>
    <media:player url="http://example.com/player.html"/>
</item>
```

which is exercised by https://github.com/newsboat/newsboat/blob/master/test/rsspp_parser.cpp#L282-L285, it's clear that the pattern used by Mastodon is different than what the tests exercise. The test case assumes that the data in the media tags clobber outer data. I think this argues for a new test case coming into existence that mirrors the expectations around a Mastodon-generated `<item>`.

Compare:

```xml
    <item>
      <guid isPermaLink="true">https://archaeo.social/@Minimus/109597925165056089</guid>
      <link>https://archaeo.social/@Minimus/109597925165056089</link>
      <pubDate>Thu, 29 Dec 2022 16:33:41 +0000</pubDate>
      <description>&lt;p&gt;Time to start writing those thank you letters, Minimus!&lt;/p&gt;</description>
      <media:content url="https://mstdn.archaeo.social/media_attachments/files/109/597/921/900/998/086/original/fe1c399c59936269.jpeg" type="image/jpeg" fileSize="376093" medium="image">
        <media:rating scheme="urn:simple">nonadult</media:rating>
        <media:description type="plain">Minimus, the Latin mouse, writing on a wax tablet</media:description>
      </media:content>
    </item>
 ```
 
 The test case would contend that the `items[0].description' would be `"Minimus, the Latin mouse, writing on a wax tablet"`, but that would lose the XML node's _actual_ description, `"Time to start writing those thank you letters, Minimus"`. I'm still getting to know the codebase, but I believe `rsspp::Parser` is doing the wrong thing.

**Comment by txgk** [comment]
Media RSS is a tricky thing for sure, according to its own standard, it allows you to do very similar things in many different ways so it's really easy to get confused in this to such an extent that not a single feedreader will implement all its functionality. [A behavior you mention seems to be reproduced in Newsraft](https://codeberg.org/grisha/newsraft/src/branch/main/src/update_feed/parse_xml/xml-handler-mediarss.c) though and you can see how such a content-description construction can be implemented, but in that project I use a streaming parser, but in general I think that the idea is traceable :)

**Comment by hiltjo** [comment]
Different RSS feeds use media:content differently. For example some news sites have a media:content with some image of the post.

Youtube uses media:content to set the URL of some Shockwave Flash player (probably for compatibility), like so:
<media:content url="https://www.youtube.com/v/m-FUIZiRN5o?version=3" type="application/x-shockwave-flash" width="640" height="390"/>

The site DeviantArt uses it to point to the direct image URL of the art.

On Mastadon the media:description seems to be the alt attribute of the image.

In my opinion Mastadon could set the image also as a RSS <enclosure> or add the <img> in the description/content and in my opinion it would be nice if Mastadon would set a <title> without the HTML content, although in RSS a <title> used to be optional and HTML is allowed too in titles sadly.

Imho in newsreaders the <media:description> should not have more priority than a <description> when both are set because <media:description> describes the description of the media, not the post itself.

Hope this helps,

**Comment by txgk** [comment]
> Imho in newsreaders the media:description should not have more priority than a when both are set because media:description describes the description of the media, not the post itself.

Well, and what about the cases when `media:description` content is much longer than post content? I think the ideal here would be getting the biggest chunk of data and presenting it as the post content.

**Comment by dennisschagt** [comment]
It looks like we currently handle the images from Mastodon as an enclosure.
Previously, we ignored image enclosures, but since Newsboat 2.30 we do show it  (accidentally, via PR https://github.com/newsboat/newsboat/pull/2218).
It looks like we currently only use/show the `media:description` within a `media:content` if there is no regular text content given for the rss entry.

Current output:
![image](https://user-images.githubusercontent.com/4629607/229372059-83e6b911-f6cc-43f6-bed9-4f37cbef2b7e.png)

I think it would be nice to show any enclosures with an image mime-type directly above the regular text, rendering the description as a link (and then not showing it as an enclosure).
