### ISSUE TITLE
`bind-key BACKSPACE quit` trigger bug in search mode

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2336]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat r2.30.1-36-g75c4

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
bind-key BACKSPACE quit
```

Steps to reproduce the issue:

1. Use keybinding `bind-key BACKSPACE quit` in config

2. Open newsboat, press `/` to enter search mode

3. Press `BACKSPACE` (When the search string is empty)

4. Cannot leave the search mode in this stage no matter what I type, have to use `pkill newsboat` to kill it

**Comment by dennisschagt** [comment]
Is that your complete config?
With just the config `bind-key BACKSPACE quit`, I cannot reproduce the issue.

However, if I extend the config with `confirm-exit yes`, I can reproduce the issue.

**Comment by amalgame21** [comment]
sorry, my config:
```
use-proxy yes
proxy localhost:9050
proxy-type socks5h
confirm-exit yes
wrap-scroll no
feedlist-format "%-30t %-15u %-4i %n %S %L"
articlelist-format "%D%y%?T?|%-16T?| %-90t|%4i %f"
datetime-format "%d%b%Y %R"
reload-threads 100
bind-key ; set-tag
bind-key j down
bind-key k up
bind-key h quit
bind-key BACKSPACE quit
bind-key SPACE open
bind-key l open
bind-key G end
bind-key g home
bind-key ' sort
bind-key S rev-sort
```

**Comment by dennisschagt** [comment]
Thanks!
Apparently, the search box allowed some characters to pass into the regular keypress handling (e.g. backspace if the search box was empty, or CTRL+<letter> key combinations at any time).
With your config, the backspace would result in a "confirm on quit".
The text asking if you wanted to quit (`Do you really want to quit (y:Yes n:No)?`) was set, but invisible because the search box was still on top of it.
Regular keys (including the `y` and `n`) where getting consumed by the search box and special keys (Enter, Esc, etc.) where rewritten by our input framework because of our search box setup, causing you to get stuck on the search box with an invisible "confirm on quit".

I've created a fix in https://github.com/newsboat/newsboat/pull/2337.

**Comment by amalgame21** [comment]
Thanks! Seems very complicated issue, so many code change.
