### ISSUE TITLE
newsboat is ignoring configuration with nextcloud

### ISSUE THREAD

**Issue by nedson** [newsboat/newsboat#2344]
I installed newsboat via snap. I have been using an older version that was packaged with Debian Bullseye (newsboat 2.21.0) so I know my config is setup correctly. When trying to load newsboat r2.30.1, I get the following error:

Starting Newsboat r2.30.1...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/user/snap/newsboat/6539/.newsboat/urls...done.
Error: no URLs configured. Please fill the file /home/user/snap/newsboat/6539/.newsboat/urls with RSS feed URLs or import an OPML file.

Since I am using nextcloud, I shouldn't need to create a 'urls' file. Nonetheless, I created the file by running 'touch urls'. This doesn't work. Next a loaded an rss feed into the urls file, and it loaded that file and ignored my config file.

Note: I adjusted the config locations for snap (/home/user/.newsboat/.config etc.).

The reason I'd like to upgrade to r2.30.1 is because 2.21.0 crashes with a segmentation fault. I have read that this is associated with loading nextcloud urls. 

****Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:**
```
Newsboat r2.30.1

Files:
	- configuration:  /home/user/snap/newsboat/6539/.newsboat/config
	- feed URLs:      /home/user/snap/newsboat/6539/.newsboat/urls
	- cache:          /home/user/snap/newsboat/6539/.newsboat/cache.db
```

**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):**
```
# set browser
#set source: nextcloud
urls-source "ocnews"
ocnews-url "https://myserver/nextcloud"
ocnews-login "user"
ocnews-password "password"
ocnews-flag-star "s"
#
# jk - move up/down
unbind-key j
unbind-key k
bind-key j down
bind-key k up

# hl - move in/out of feeds/articles
bind-key h quit
bind-key l open

# q quits the program
unbind-key q
bind-key q hard-quit

# g/G to go to top/bottom
unbind-key g
unbind-key G
bind-key g home
bind-key G end
```

**Comment by dennisschagt** [comment]
Hi, just a wild guess, but does newsboat/snap have permission to read the config file? (might not be the case if the file is owned by a different user or has the read permissions cleared)
The reason I'm asking is because I just found out that Newsboat ignores any config files it cannot read (while making it look like there was no problem).

If you don't see any obvious access issues, it might be useful to capture the log file created by Newsboat, e.g. using:
```
snap run newsboat --log-level=6 --log-file=/home/user/snap/newsboat/6539/log.txt
```
 (don't forget to update the "user" part of the path)

If I make the config file unreadable, the log contains the following warnings (between a bunch of debug/info statements):
```
[2023-02-15 22:05:48] WARNING: ConfigParser::parse_file: file /etc/newsboat/config couldn't be opened
[2023-02-15 22:05:48] WARNING: ConfigParser::parse_file: file /home/dennis/snap/newsboat/6539/.newsboat/config couldn't be opened
```

**Comment by nedson** [comment]
Thanks for the suggestion. You were correct newsboat doesn't seem to have permission to access the config file:

[2023-02-16 07:49:27] WARNING: ConfigParser::parse_file: file /etc/newsboat/config couldn't be opened
[2023-02-16 07:49:27] WARNING: ConfigParser::parse_file: file /home/user/snap/newsboat/6539/.newsboat/config couldn't be opened

Do you have a recommendation for fixing this? I tried changing permissions of the config file but am still getting the error in the log.

**Comment by dennisschagt** [comment]
Could you show the output of `ls -l /home/user/snap/newsboat/6539/.newsboat/config`?

If it is not the file read permissions (which I assume you set on the file), I can only think of 3 more possible issues:
1. You only gave read permissions to the file owner, while the file is owned by something a different account than the account used for running newsboat
2. One of the parent directories (recursively) of the config file misses the execute bit (needed to open anything within the directory)
3. Snap blocks access to the file (would be strange, because this is specifically the place which Snap programs are given access to by default)
4. ... (there might be other causes, but those are the few I can come up with given the current information)

**Comment by nedson** [comment]
Thank you! Finally figured out what was going wrong. Looking at the permissions for the config file...turns out I symlinked the config file from /home/user/.newsboat/config -> /home/snap/newsboat/6539/config. Permissions were set for my user...I totally forgot that I symlinked this file. 

Thank you for your suggestions and helping me solve my problem.
