### ISSUE TITLE
Scrolling the page without moving the cursor

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2369]
Is `newsboat` capable of scrolling up or down without moving the cursor like the behaviour of vim's `Ctrl-E` `Ctrl-Y` or `zz` `zt` `zb` ?

**Comment by amalgame21** [comment]
Just discovered the `scrolloff` function that's work fine for me.

**Comment by dennisschagt** [comment]
We don't support any of those ones at the moment, but we do support scrolling by half a page since [PR 2279](https://github.com/newsboat/newsboat/pull/2279) (will be available starting in the upcoming 2.31 release)

If anyone is interested in supporting the other movement commands, the `ListMovementControl.h` file might be a good place to start:
https://github.com/newsboat/newsboat/blob/62d547b671ed0c3f60967766c9d74adc5e162fa6/include/listmovementcontrol.h#L29-L156

A somewhat similar issue: https://github.com/newsboat/newsboat/issues/215
