### ISSUE TITLE
Regex Issue with beginning of line in feedlist/articlelist

### ISSUE THREAD

**Issue by mrjpaxton** [newsboat/newsboat#242]
Hey,

So I tried using this line in my config file: `highlight feedlist "^[0-9 ]+ N " white color8 bold underline`

And it won't match the new/unread feeds. Same thing happens with `highlight articlelist`. However this line: `highlight feedlist "[0-9 ]{4,} N " white color8 bold underline`

matches perfectly fine. So what's the issue here? I've tested it with https://www.regexpal.com/, so try the first one there with your article/feed line. It should work!

This problem has existed in newsbeuter before, but finally got around to reporting it.

**Newsboat version (copy from `newsboat -v`)**:

newsboat 2.12.0
System: Linux 4.17.0-1-amd64 (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180714 (compiled with 6.1)
libcurl: libcurl/7.60.0 GnuTLS/3.5.19 zlib/1.2.11 libidn2/2.0.4 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.32.0 librtmp/2.3 (compiled with 7.60.0)
SQLite: 3.24.0 (compiled with 3.24.0)
libxml2: compiled with 2.9.4

**Comment by Minoru** [comment]
Hi! There are many more regex syntaxes than Javascript and PCRE presented on regexpal.com. In this instance, Newsboat uses POSIX Extended ones (like `grep --extended`).

Both your regular expressions are valid, but the first one doesn't match because Newsboat puts a special tag at the beginning of lines that contain unread feeds. Looks like this:

```
    1   (0/23)  Some feed
    2   (0/100) Another feed
<unread>    3 N (1/13) Unread feed
```

Naturally, the first regex doesn't match the last line.

This is more of an architectural error, and I don't know offhand how best to fix it. So there won't be an immediate patch. But we'll get to it eventually.

Thank you for the report! If you have any other long-standing issues that you never came around to report, please do so—we're currently in the process of reworking Newsboat's internals, and it would be nice to know of as many bugs as possible so we can do things right^Wbetter this time around.
