### ISSUE TITLE
Short-circuit evaluation for query feeds

### ISSUE THREAD

**Issue by DefectiveClub** [newsboat/newsboat#2427]
Some of my query feeds take an extraordinary time to run (200 feeds, 200 max items per feed), in particular when searching the contents for strings.
Does newsboat currently use short-circuit bool operators, and/or would this be difficult to implement?

**Comment by dennisschagt** [comment]
It looks like Newsboat already applies short-circuiting to and/or in filter expressions:

**Comment by dennisschagt** [comment]
It looks like Newsboat already applies short-circuiting to and/or in filter expressions:
https://github.com/newsboat/newsboat/blob/c0ed70475ddf50ade51479d16fd3395d42231144/src/matcher.cpp#L188-L195

I think a big part of the time taken is caused by repeatedly loading articles from the database.
There is already a proposed fix for that in https://github.com/newsboat/newsboat/issues/581, but that might take quite a bit of effort/time to implement.
