### ISSUE TITLE
bookmark-autopilot is ignored in search results

### ISSUE THREAD

**Issue by audiofool** [newsboat/newsboat#243]
**Newsboat version (copy from `newsboat -v`)**:
newsboat 2.12.0
System: Linux 4.17.10-1-ARCH (x86_64)
Compiler: g++ 8.1.1 20180531
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.32.0 (compiled with 7.60.0)
SQLite: 3.24.0 (compiled with 3.24.0)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. edit the config

2. bookmark-autopilot yes

3. bookmarking an article from within  'search results' ignores the bookmark-autopilot setting and prompts for url, description, etc...

**Other info you think is relevant**:

**Comment by Minoru** [comment]
Reproduced; thank you for the report!

**Comment by dennisschagt** [comment]
The search result list uses a pseudo-feed which does not have a title.
Autopilot bookmarking currently requires that a non-empty feed-title is provided (in the `default_feed_title` field:
https://github.com/newsboat/newsboat/blob/a5a721cc3b3ada0008ee51fbaec43e8f23abf55f/src/formaction.cpp#L461-L465

One solution would be to accept an empty feed title when bookmarking on autopilot.
Another option is to pass the title of the feed which an item belongs to (instead of the title of the search/query feed which is used to access the item)

**Comment by Minoru** [comment]
> Another option is to pass the title of the feed which an item belongs to (instead of the title of the search/query feed which is used to access the item)

This would affect how non-autopilot bookmarking works, right? I guess the best solution would be to try the current feed, and if it doesn't have the title, then look at the feed to which the item belongs. But that's probably a separate issue, let's wait for actual users to ask about this.
