### ISSUE TITLE
 Mastodon feed articles have no titles at all 

### ISSUE THREAD

**Issue by dorsiflexion** [newsboat/newsboat#2573]
**Newsboat version**:

```
Newsboat 2.33.0
System: Linux 6.5.5-hardened1-1-hardened (x86_64)
Compiler: g++ 13.2.1 20230801
ncurses: ncurses 6.4.20230520 (compiled with 6.4)
libcurl: libcurl/8.3.0 OpenSSL/3.1.3 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.56.0 (compiled with 8.3.0)
SQLite: 3.43.1 (compiled with 3.43.1)
libxml2: compiled with 2.11.5
```

**Config file**:

Doesn't matter, but here is one it happens with anyway:

```
urls-source "ocnews"
ocnews-url ***
ocnews-login ***
ocnews-password ***
```

**Steps to reproduce the issue**:

1. Subscribe to a mastodon feed (e. g. `https://social.tchncs.de/@kuketzblog.rss`) via nextcloud news.
2. Retrieve nextcloud news via newsboat

**Other info you think is relevant**:

Probably related: #2530 #2531

No Errors in log, just:
```
[2023-10-07 11:34:24] INFO: Reloader::reload: parsing feed
[2023-10-07 11:34:24] INFO: RssParser::parse: added article title = `' link = `https://social.tchncs.de/@kuketzblog/111192088490735640' ign = 0x74b83a27cda0
```

**Comment by dennisschagt** [comment]
I can reproduce this, and git bisect indeed points to https://github.com/newsboat/newsboat/commit/9b386432d903c92d9b100879154ca96867a48ff1.

It looks like the item descriptions from nextcloud (and the other external APIs) are placed in the `RssItem::content_encoded` field instead of the `RssItem::description`.
That field is currently ignored when trying to create a fallback title.
