### ISSUE TITLE
Question: any plans for adding a sidebar to newsboat?

### ISSUE THREAD

**Issue by stefanos82** [newsboat/newsboat#265]
Coming from liferea that offered me a sidebar, was way too convenient for me to have organized links according to their category.

Are there any plans to have a sidebar? It would be really cool to add it.

**Comment by tsipinakis** [comment]
There's been some discussion on this in akrennmair/newsbeuter#461.

 > was way too convenient for me to have organized links according to their category.

While it doesn't have a sidebar, newsboat does feed organization via [tags](https://newsboat.org/releases/2.12/docs/newsboat.html#_tagging). Perhaps that's what you're after?

**Comment by stefanos82** [comment]
@tsipinakis I know about tags, but to be honest with you, I would prefer to have a left sidebar.

From an aesthetic point of view, it helps reduce the links' size in the main window, thanks to the folder tree.

This way I could, for example, choose to read just my Tech News folder without polluting my main window with hundreds of links.

It gets annoying scrolling all the way down check every time possible missing links.

**Comment by Minoru** [comment]
Hi! My position regarding this hasn't changed since Newsbeuter issue that @tsipinakis linked: I'd accept a patch, but I'm not interested in working on this myself.

@stefanos82, I'm not sure I understand what you mean by "links" and "missing links". Do you mean articles and unread articles, respectively? You can avoid scrolling in a number of ways:
- `n` key will jump to the next unread article. Works both inside feeds and in article view: you can simulate an old Google Reader approach by opening some article and then just pressing `n` all the time to jump to the next one;
- change sorting order or criteria with `g` and `G`, so that the articles you're interested in are at the top of the list;
- hide read articles by pressing `l`, so it's easier to pick out of unread ones.

If you describe the annoyances you have in more detail (some screenshots or Asciinema, maybe?), perhaps we'll be able to recommend some more solutions.

**Comment by stefanos82** [comment]
@Minoru It's alright. All I asked was a question and you were quite clear about not interested in such feature.

I will see what I can do.

Cheers.
