### ISSUE TITLE
Question: Make bash script macro run in background

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2742]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat 2.35.0
System: Linux 6.8.7-300.fc40.x86_64 (x86_64)
Compiler: g++ 11.4.0
ncurses: ncurses 6.4.20221231 (compiled with 6.4)
libcurl: libcurl/8.7.1 OpenSSL/3.3.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libssh2/1.11.0 nghttp2/1.61.0 librtmp/2.3 OpenLDAP/2.6.7 (compiled with 8.6.0)
SQLite: 3.45.3 (compiled with 3.45.2)
libxml2: compiled with 2.12.6
```

# ~/.config/newsboat/config

```
macro y set browser "nohup Youtube --play %u &"; open-in-browser ; set browser "firefox %u"
macro m set browser "nohup mpv %u > /dev/null 2>&1 &"; open-in-browser ; set browser "firefox %u"
```

# Note

- `Youtube` is a bash script that downloads the video into a folder and then plays it with mpv

# Issue

When I press `,` +` m`: mpv starts in background and I can still browse the newsboat interface while te video is playing. This is fine and as per expectation.

But when I press `,` + `y`, the Youtube bash script takes over Newsboat interface till it is finished downloading contents. How can I make an external bash script to run in background without interfering with newsboat interface?

**Comment by dennisschagt** [comment]
I think this can be fixed by using `open-in-browser-noninteractively` instead of `open-in-browser` (see [open-in-browser-noninteractively in documentation](https://newsboat.org/releases/2.35/docs/newsboat.html#open-in-browser-noninteractively) and the [Separating Browser from Newsboat section](https://newsboat.org/releases/2.35/docs/newsboat.html#_separating_browser_from_newsboat))
