### ISSUE TITLE
License of tests/data/1300_reproducer.html

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#2748]
While packaging newsboat 2.35 for Debian the file `tests/data/1300_reproducer.html` was flagged as potentially source missing - it looks like it contains actual content from a website. Since this is included in the tarball I'm wondering what's the license of that file? Is it free to distribute?

**Comment by dennisschagt** [comment]
I'm not sure about the license of that data. It was introduced quite a while back (in https://github.com/newsboat/newsboat/pull/1302).
Just to be sure, I guess we can just replace it with a minimal reproducer.

I've submitted a PR. I will wait for a few days to give some time for reviews and otherwise I will just merge the PR as-is.
