### ISSUE TITLE
[Feature Request] Github as hosting provider.

### ISSUE THREAD

**Issue by darkseid-is** [newsboat/newsboat#2803]
Use github to store cache.db file. So that multiple newsboat instances from multiple devices can access the same db.
This could remove the need for middlemen and allow users to host their own feeds.

A wrapper script to fetch from github before starting newsboat, run newsboat and push to github can be used. Looking for some native support or add feature run scripts in startup and exit. 

Thank you for a great app.

**Comment by Minoru** [comment]
If two Newsboat processes run concurrently and then each commits its own version of cache.db into Git, then at some point a merge conflict will arise. Since cache.db is partially a binary file, it'd be extremely difficult to resolve this conflict manually. The only realistic approach would be to choose one version of the file over the other, obviously losing some data. This doesn't sound like a good solution at all, so we won't support this in Newsboat proper.

However, you correctly point out that it's possible to write a wrapper script to do this. No need to teach Newsboat to run scripts on startup and exit; a wrapper would do something along the lines of `git pull -X theirs && newsboat && git commit -am'Update database' && git push`.
