### ISSUE TITLE
close operation?

### ISSUE THREAD

**Issue by 2084x** [newsboat/newsboat#2808]
maybe I've completely missed it in the manual, but there appears to be no operation to only close a dialog or feed list and do nothing more.   

the closest you can get is quit, which does close dialogs but it also quits if you're viewing the main feed list. why does it do this? shouldn't closing and quitting be separate operations and key binds?

if a close operation doesn't exist, I would greatly appreciate one being added to newsboat.

**Comment by juntuu** [comment]
## Background on the model:
The Newsboat views are like a stack, where the bottom one is always the main feedlist. The quit operation closes the current view, returning to the previous on the stack. When quitting the main feed list, the stack becomes empty, so the application exits. (There can be multiple stacks at once, but one is shown at a time.)

## To your question:
No, I don't think there is separate `close` operation. _But_, `quit` is context dependent operation and works like the `close` you described in any other view than the main feedlist.

Also, what would `close` do in the main feedlist? There is no other view left on the stack at that point. (Other stacks might have something, though.)

## Possible solutions:
However, there are ways to achieve at least close to what you ask for. Two ways come to mind.

1. Bind a different key to `quit` from feedlist and other views. Only quitting from feedlist will exit the application. This reflects the context dependent nature of the `quit` operation, separating the different cases to different keys.
2. Set [`confirm-exit yes`](https://newsboat.org/releases/2.36/docs/newsboat.html#confirm-exit), and Newsboat will prompt before exiting. You can still use hard-quit to exit without prompt and from any depth.

I personally use option 1. and also bind `hard-quit` to same key as `quit` on feedlist, so that key exits the application.

In the following configuration I have bound <kbd>h</kbd> to close the current view (but not exit), and <kbd>q</kbd> to exit:

```
bind-key q hard-quit
bind-key h quit

unbind-key h feedlist
bind-key q quit feedlist
```

**Comment by 2084x** [comment]
thanks for the detailed explanation. I better understand how the views work now and I guess a close operation isn't totally necessary.

> Also, what would close do in the main feedlist? 

presumably nothing. just like how nothing happens when you're at the bottom of your feed list and you hit the down key, for example. 

> In the following configuration I have bound h to close the current view (but not exit), and q to exit:

awesome!! those bindings achieve exactly what I wanted. I'm annoyed I didn't think about just unmapping `h` in the feedlist myself haha...
