### ISSUE TITLE
colour config from newsbeuter is not recognised

### ISSUE THREAD

**Issue by cirrusUK** [newsboat/newsboat#29]
Hi & thanks for the code

  My minor issue is that the color config from my ~/.newsbeuter/[config](http://ix.io/Bzb) migrated to ~/.newsboat/[config](http://ix.io/Bzb)  is not recognised,  the macros etc defined in [config](http://ix.io/Bzb) all work well, only the colour issue, sadly i have had to add newsbeuter to pacman ignore until i figure it out

 please advise.
regards
cirrus

**Comment by Minoru** [comment]
Hi, thanks for reporting this! I don't see anything suspicious in your config and my Newsboat launched fine with it, so not sure what "not recognized" means. Can you provide screenshots of how it looks in Newsbeuter and how it looks in Newsboat for you?

**Comment by cirrusUK** [comment]
Thanks for prompt response, both scrots taken from same terminal emulator
[newsbeuter.png](https://i.imgur.com/Bg0Tik5.png)
[newsboat.png](https://i.imgur.com/oOueSNn.png)

**Comment by Minoru** [comment]
There was a bug in Newsbeuter: `listnormal_unread` and `listfocus_unread` didn't apply to feedlist. It has been fixed in akrennmair/newsbeuter#222 and released with Newsboat 2.10.

Unfortunately, your config relied on that bug: your `listfocus` setting was applied to feeds with unread items. Newsboat 2.10 broke that by applying `listfocus_unread` instead.

Given you have set `show-read-feeds` to `no`, you can just rename your `listfocus` setting to `listfocus_unread` and be done with it.

**Comment by cirrusUK** [comment]
@Minoru  Thank you kindly for helping me debug this, i doubt i would have managed on my own,  now i can go remove newsbeuter from pacman ignore, thanks again
regards
