### ISSUE TITLE
Colon appearing at the end of feed url

### ISSUE THREAD

**Issue by mikaelz** [newsboat/newsboat#2922]
**Newsboat version**: 2.37

`urls` file contents:
```
https://hu.usembassy.gov/feed/ "Travel"
https://sk.usembassy.gov/feed/ "Travel"
https://cz.usembassy.gov/feed/ "Travel"
```

`error.log`
```
[2024-11-22 13:22:24] Error while retrieving https://cz.usembassy.gov/feed/: unsupported feed format
[2024-11-22 13:22:25] Error while retrieving https://sk.usembassy.gov/feed/: unsupported feed format
[2024-11-22 13:22:26] Error while retrieving https://hu.usembassy.gov/feed/: unsupported feed format
```

**Comment by dennisschagt** [comment]
It looks like the colon is part of the error message.
It prints the url, directly followed by a colon and some error message:
https://github.com/newsboat/newsboat/blob/a04d48a87168d2eb46e5ee44a642e37dd984d767/src/reloader.cpp#L129
https://github.com/newsboat/newsboat/blob/a04d48a87168d2eb46e5ee44a642e37dd984d767/rss/rssparserfactory.cpp#L31

I've tried to access the feeds in a browser and with Curl.
In the browser it is showing a valid feed but with Curl I get a Cloudfront error.
This looks similar to https://github.com/newsboat/newsboat/issues/2889 and is probably caused by the webserver of usembassy.gov accepting/rejecting requests based on user agent (see for example https://github.com/newsboat/newsboat/issues/2889#issuecomment-2395052881)

**Comment by mikaelz** [comment]
Thanks, adding `user-agent` to config solved the issue
