### ISSUE TITLE
Should unresolved newsbeuter issues be reposted here?

### ISSUE THREAD

**Issue by Markus00000** [newsboat/newsboat#31]
Should unresolved newsbeuter issues be reposted as newsboat issues or will you somehow migrate them?

**Comment by Minoru** [comment]
I decided against migration because I have no way of disabling the Newsbeuter issue tracker. Issues will be posted both here and there, and the trackers will diverge. I can fight it by reposting every issue, or I can embrace it by treating Newsbeuter tracker as an extension of Newsboat's. That's one point.

Another point: Newsboat development should happen on Newsboat turf, so discussions should happen *here* even if the bug originated in Newsbeuter.

Thus, the guideline is:
* if you have something new to say, open an issue here and reference Newsbeuter one (use `akrennmair/newsbeuter#123` syntax, GitHub will turn it into a link);
* if you're fixing a bug that has an issue in Newsbeuter but not in Newsboat, don't bother filing it—just reference the Newsbeuter issue. I'd also drop a comment in that Newsbeuter issue saying the issue has been fixed in Newsboat; this will send notifications to everyone who subscribed.

I didn't actually discuss this with anyone, so if you see any flaws, please point them out!

**Comment by Markus00000** [comment]
Considering that newsbeuter has 200 open issues, how would you keep track of the one’s not affecting newsboat and those fixed in newsboat?

How about creating a newsboat meta-issue containing a list of newsbeuter issues (just their titles as links) and then tag these issues as *fixed*, *invalid*, *to do*, etc.?

* Users and developers could see the state of any old issue (doing this in the newsbeuter tracker without the ability to close issues might become difficult)
* Developers could easily find old bug reports and feature requests to work on
* Discussions could proceed to take place in their original newsbeuter issues where relevant comments might already have been posted (if a discussion becomes irrelevant to newsbeuter, it can still be migrated to a new newsboat issue)
* Should anyone continue developing newsbeuter, they could easily see what has been done and issue discussions would not be split across two projects (unless necessary)

**Comment by Minoru** [comment]
Rather than reply to each of your points separately, I'll attack your assumptions, of which I see two:

1. there are developers who look through old issues in search of something to fix; and
2. all bugs will be fixed.

The first assumption runs counter to what I've seen while maintaining Newsbeuter: there were *zero* PRs fixing issues reported to our Google Code tracker. Issues were fixed because:

* a developer ran into them him-/herself; or
* there was some discussion where an old issue was mentioned and this somehow sparkled developer's enthusiasm; or
* BountySource offered a reward for fixing it; or
* the issue was new and easy and I fixed it during triage or shortly afterwards.

The second assumption I agree with in principle, but disagree with in context of Newsboat and Newsbeuter as they are today. There are more new issues than commits fixing them. There are only a handful of "serial contributors", none of them very active. (That includes me.) Even though Newsbeuter is 10 years old, it's still in a bootstrapping stage where code-writing activities haven't yet reached sustainable levels. While that is the case, we don't need a perfect system where every bug is up-to-date—developers are so few that imperfections are easily resolved by talking to each other.

(My view on first assumption is based on my memory—I didn't do an actual numeric analysis of PRs. My view on second assumption is biased—I like programming and am not very interested in management.)

Does that stance make sense to you?

**Comment by Markus00000** [comment]
Yes, your stance makes sense to me.

(As a side note, I did not make any assumptions as I am not familiar enough with the development of newsbeuter. I only listed a few points that would be made possible by the meta-issue approach. You can certainly judge much better than I whether it would make sense.)

The reason I created this issue in the first place is simple. As a user I was wondering how I could make it as easy as possible for developers to discover, prioritize and fix the issues I (and others) previously created.

**Comment by Minoru** [comment]
Ah; sorry for going full analytical and preachy on you, then.

For a user, the situation is quite grim: one writes a detailed report, answers whatever questions I might ask during triage, and then waits for someone to decide to work on the issue. Developers are few ⇒ no organization ⇒ no leverage to influence them to work on a particular thing.

Regarding your points: the first and fourth are already possible because we'll reference Newsbeuter issues from here, and GitHub will display "backlinks" in the other tracker. The second point I addressed as a first assumption; third point is complicated because relevancy is subjective, off-topic creeps in slowly not suddenly, and even technical discussions rarely are about a single thing. So the situations isn't as bad as you might've thought (we have some of your points), but far from perfect (if only we could make the other tracker read-only...)

I guess we're done with this issue, so I'm going to close it. Thank you for your concern, and sorry about my answers being as dissatisfying as they are. I'm not deliberately making Newsboat development harder to get into than it should be, I promise!

**Comment by Minoru** [comment]
I end up [breaking my own rules](https://github.com/akrennmair/newsbeuter/issues/604#issuecomment-340283537) now: instead of dragging all discussions to *this* tracker, I had a little chat in Newsbeuter's. I think it's okay because the problem was small and the fix quite obvious; though if the person wanted to select what URL to enqueue, I'd ask them to discuss it here because it's a lengthier and more Newsboat-specific discussion.

**Comment by Minoru** [comment]
Newsbeuter repo is now archived. We can be sure no new issues or comments will appear there.

If you're still affected by an old, unresolved Newsbeuter issue, please re-report it on this issue tracker.
