### ISSUE TITLE
License header and content discrepancy

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#34]
While preparing the `debian/copyright` file for newsboat I discovered a small discrepancy: The license header says that it's the MIT/X Consortium license but the content is actually the MIT Expat license.

See [here](https://en.wikipedia.org/wiki/MIT_License#License_terms) for the difference.

**Comment by Minoru** [comment]
Thanks for reporting this, and sorry it took me so long to take a look at it. I decided to keep the text of the license and change the title because at the end of the day, it's the terms that define the license, not its name ("BSD License" is a good example of a name that became ambiguous because it was used for different sets of terms).
