### ISSUE TITLE
Better support for Vim-like key bindings

### ISSUE THREAD

**Issue by Teyras** [newsboat/newsboat#36]
I prefer to use vim-style keybindings in most programs. One thing that I find missing from newsboat is fast navigation using g/G (go to first/last item in list) and ^d/^u (scroll half a page down/up). Would it be possible to add actions that I could bind to those keys?

**Comment by Minoru** [comment]
g and G are already possible:
```
unbind-key g # bound to `sort` by default
bind-key g home
unbind-key G # bound to `rev-sort` by default
bind-key G end
```

`home` and `end` weren't documented, I fixed this.

Scrolling by half a page is impossible at the moment, though—only by a single screen (see `pageup` and `pagedown` key commands.) Adding those is a bit tricky because the ones we already have (home/end/pgup/pgdown) are handled by STFL, our UI library; AFAIK it doesn't provide anything for half-a-page scrolls, so we'll have to implement it on our end, and I'm not sure how much control we got there.

Won't promise anything yet, but thanks for filing the issue!

**Comment by Teyras** [comment]
g/G is perfect for now, thanks a lot!

**Comment by hhiru** [comment]
Can't you just edit the bindings for navigation in the config file?

```
unbind-key h
unbind-key j
unbind-key k
unbind-key l

bind-key h quit
bind-key j down
bind-key k up
bind-key l open
```

**Comment by Minoru** [comment]
@hhiru that's tangential to the question, which is about specific operations, some of which aren't even implemented in Newsboat (yet).

**Comment by kmws** [comment]
For me, Jump up/down (C-d, C-u in vim) and go to first/last item (something like g/G that doesn't feel like a hack) would be perfect.

**Comment by oblitum** [comment]
Really missing vi-mode here...
