### ISSUE TITLE
UrlViewFormaction.init() throws SIGSEV

### ISSUE THREAD

**Issue by zaowen** [newsboat/newsboat#379]
newsboat r2.13-278-gf3bab-dirty - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

1. Add any feed that has articles with urls in it. (e.g. http://rss.slashdot.org/Slashdot/slashdot )

2. go to any article with urls.

3. attempt to go to url view, and newsboat will crash.

After a bit of snooping it looks like the config container is crashing after a call to `get_configvalue()` looking for value urlview-title-format. my config file does not contain an override of the default value. 
I think it may have to do with the .value call on the ConfigData item.

**Comment by Minoru** [comment]
Hi! I'm going to sleep, so it will be another 20 hours or so before I take
a look at this. In the meantime, can you please run git bisect to see which
commit introduced the crash?

Also, "-dirty" in the version string indicate that you have done local
uncommitted changes, or at least didn't do a clean rebuild since you had
them. (Our git version handling is clunky and might misreport things
slightly). Can you run make distclean && make to get a clean rebuild?

>

**Comment by zaowen** [comment]
git bisecting leads to 05fbbab67737a79a56258af314b3fd1ddad26695

**Comment by kmws** [comment]
Looks like my refactoring change did this... I will try to take a look in a few hours.
