### ISSUE TITLE
Error compiling: xmllint validation error

### ISSUE THREAD

**Issue by philippkeller** [newsboat/newsboat#396]
**Newsboat**: cloned from github

Steps to reproduce the issue:

Run `make`

**Other info you think is relevant**:
I'm on OSX, rust version 1.29

When running make I see:

```bash
a2x -f manpage doc/manpage-newsboat.txt
a2x: ERROR: "xmllint" --nonet --noout --valid "/private/var/tmp/newsboat/doc/manpage-newsboat.xml" returned non-zero exit status 4
make: *** [doc/newsboat.1] Error 1
```

when running the xmllint command by hand:

```bash
> "xmllint" --nonet --noout --valid "/private/var/tmp/newsboat/doc/manpage-newsboat.xml"
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/private/var/tmp/newsboat/doc/manpage-newsboat.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
/private/var/tmp/newsboat/doc/manpage-newsboat.xml:5: validity error : Validation failed: no DTD found !
<refentry lang="en">
```

I'm not sure why I get this error, because curl works with this url:

```bash
> curl -I  http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd 
HTTP/1.1 200 OK
Server: Apache
Content-Type: application/xml-dtd
Date: Sat, 29 Dec 2018 11:50:27 GMT
Accept-Ranges: bytes
ETag: "13ae45-169f-578c679826640"
Via: 1.1 www.oasis-open.org
Connection: Keep-Alive
Set-Cookie: ROUTEID=.1; path=/
Last-Modified: Mon, 22 Oct 2018 00:38:41 GMT
Content-Length: 5791
```

**Comment by Minoru** [comment]
Hi! `--nonet` option instructs `xmllint` to fail all network requests. The option is added by `a2x` which we invoke; we can't control that.

What we do on Travis CI is [set `XML_CATALOG_FILES` environment variable](https://github.com/newsboat/newsboat/blob/90a9f9398b3af38fd6aa4e1a8e74d296a639b9d2/.travis.yml#L238). Instead of plain `make`, run `XML_CATALOG_FILES=/usr/local/etc/xml/catalog make`. That should fix the problem (but you need to `brew install docbook-xsl` if you haven't already).

A sidenote: please mention the commit ID if you've cloned from GitHub. It didn't matter in this case, but sometimes the behaviour will differ between commits, and that information would be essential to resolve the issue. I'll add `git show` as an alternative to `newsboat -v` in the issue template, too.

**Comment by philippkeller** [comment]
Yes, that fixes the issue, thanks! And insanely fast reaction.
And: yes, I'll include the commit id next time
