### ISSUE TITLE
SQLite version 3.5 does not exist

### ISSUE THREAD

**Issue by gmarmstrong** [newsboat/newsboat#40]
[Newsboat requires SQLite version 3.5](https://github.com/newsboat/newsboat#dependencies), but [the most recent version of SQLite is 3.21.0](http://www.sqlite.org/download.html).

**Comment by Minoru** [comment]
Here's [a changelog from 3.4.2 to 3.5.0](https://www.sqlite.org/34to35.html), and here's [a 3.5.9 branch](https://www.sqlite.org/src/timeline?n=100&r=branch-3.5.9) in the upstream repo. I'm pretty sure 3.5 did exist and is still available from the repo (but not tagged, apparently).

Our README says "3.5 or newer", and 3.21.0 is newer than 3.5; what is the problem here?

**Comment by gmarmstrong** [comment]
Oh, wow. I completely forgot how to read version numbers.
