### ISSUE TITLE
Highlighting the "Link" field messes up colors

### ISSUE THREAD

**Issue by ghost** [newsboat/newsboat#401]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.14.0
System: Linux 4.20.0-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.35.1 (compiled with 7.63.0)
SQLite: 3.26.0 (compiled with 3.26.0)
libxml2: compiled with 2.9.8
Terminal: st (also tried xterm, and inside tmux, with no changes)

**Steps to reproduce the issue:**

1. Empty your config, then add the following lines:
```
highlight article "^L" red
highlight article "http" blue
```

2. Open any article

**Other info you think is relevant**:

To be more specific, highlighting just the first letter "L" of the "Link:" field at the top (more than just the first letter can be included though), with another highlight anywhere in the same line will cause the color of the "L" to be applied to all text after the second highlight, until a third highlight is found. This sounds confusing but the screenshot explains it better.

Here, the second highlight is "archlinux" instead:
![screenshot](https://i.imgur.com/r455NHA.png)

The colors or attributes used for the highlight don't matter. The same thing happens even when the second highlight is just "default" with no attributes.

**Comment by zaowen** [comment]
Hello m3tax, thank you for this bug report.
I've found the source of the problem. I'll have a PR in to fix it right away as soon as I can ensure I didn't break anything else.

The maintainer should be back from the holidays soon and I would guess this bug will be fixed in master by Friday.
Thanks again.

**Comment by Minoru** [comment]
@zaowen, thanks for stepping up to do issue triage! I see you did it for a couple issues already, so I've invited you to become a collaborator. This will let you tag issues, amongst [other things](https://help.github.com/articles/permission-levels-for-a-user-account-repository/).

A few guidelines:
* Please *do* keep submitting your changes through PRs rather than committing them directly to `master`.
* Please *do* lock a conversation if you see someone spamming it (and *do* report the spammer to GitHub).
* Please *don't* rename or delete existing tags or milestones. You can add new ones, though, if you see a need for them.
* Please *don't* touch milestones. You shouldn't have a need for them since they're only used for milestones.
* Please *don't* delete others comments.
* Please *don't* merge or close pull requests. If you're interested in that "line of work", start reviewing them, and eventually I'll trust you to do the whole cycle without supervision.

**Comment by zaowen** [comment]
Thank you @Minoru, for the vote of confidence. I hope to continue to be an asset to this project.
