### ISSUE TITLE
No space between attribute Type of video and URL

### ISSUE THREAD

**Issue by Busyvar** [newsboat/newsboat#425]
Hi,
I has an issue recently when trying to follow urls rendered in article view.
For this kind of RSS line to parse
```
    <media:content url="https://url.video.mp4" type="video/mp4" width="640" height="360" />

```
This line is rendered
https://url.com/video.mp4type : video/mp4

When i use external tools like url-select to follow this link it fails to parse correctly.

This problem doesn't happen ~2 month ago, is some space has been missed when processing Type attribute?

Best Regards.

**Comment by zaowen** [comment]
Thanks  for the bug report Busyvar.

Would you mind giving us a bit more information so we can solve this issue more easily? namely:
1. The ouput of `newsboat -v`
2. A feed url where this occurs 
With this it will be easier to solve your issue. Thanks again.

**Comment by Minoru** [comment]
Reproduced with current HEAD (faea3381ead66b9f31e3405739662d0bda5bf48b)
 and this podcast: https://feeds.feedburner.com/SoftSkillsEngineering.

I introduced this bug for external pagers in aadba031ab6f5607946735a7fcf5ce299fb527d5, and extended it to internal pagers in 75622130f42a5686b58651860f3063072b22b62f. Even though we do have tests for that part of the code, the buggy line [wasn't covered](https://coveralls.io/builds/21236787/source?filename=src/itemrenderer.cpp#L61). I'm not entirely sure how I missed that; it was probably masked by otherwise increased coverage (stuff that used to be untesteable was moved to `ItemRenderer` class and covered with tests).

I fixed this in bugfix/425-separate-podcast-url-and-podcast-mime-type branch, which I'll merge once Travis is done checking it.

@zaowen, in addition to "bug" label, please use "to-check" for issues you didn't try to reproduce yet, and "cannot-reproduce" for the ones that you tried and failed to reproduce. Otherwise good job on the triage :+1:
