### ISSUE TITLE
How can I mark all my feeds as Read every night automatically?

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#438]
How can I mark all my feeds as Read every night automatically?

**Comment by Minoru** [comment]
Newsboat is not meant to be scripted, so technically the answer is "you can't".

However, since it's a console application, you can pipe keystrokes into its standard input and make it do things: `echo Cq | newsboat` will start Newsboat, "press" C to mark everything as read, and "press" q to quit. You can run this from your user cron. `echo`'s argument will require adjusting if you change your keybindings (or you can force the defaults with `--config-file=/dev/null`, but then the `cache-file` setting won't work). The cron job might fail if there is another copy of Newsboat is already running.
