### ISSUE TITLE
Option to ignore hidden feeds when using notifications (for queried feeds)

### ISSUE THREAD

**Issue by Aicaya** [newsboat/newsboat#444]
**Newsboat version**: 2.14.1

Steps to reproduce the issue:

1. Create query to group hidden feeds into a single one:

```
https://somepodcast.com/feed "!Feed A" podcasts
https://anotherpodcast.com/rss "!Feed B" podcasts
"query:Podcasts:tags # \"podcasts\""
```

2. Use `notify-program` and `notify-format` to send notifications whenever feeds update. Method used in my config:

```
notify-program "nb-notify"
notify-format "New articles: %d\nTotal unread: %n article(s), %f feed(s)"
```

(`nb-notify` is a custom script for a prettier `notify-send` command—code is [here](https://notabug.org/Aicaya/dotfiles/src/master/newsboat/nb-notify) for the sake of reference)

3. Update feeds.

With the above steps (and assuming just one new article in each of the hidden feeds), `notify-format` sends the following:

> New articles: 4
> Total unread: 4 article(s), 3 feed(s)

Two articles from two hidden feeds, plus two articles within the query feed containing both hidden feeds. So basically, the number of unread articles is doubled and the hidden feeds are added to the count.

I started using query feeds a lot more ever since [the last issue I posted was worked on](https://github.com/newsboat/newsboat/issues/428) (many thanks for that, btw) and quickly noticed this behavior. I usually have Newsboat running in the background from within a tmux session and rely on notifications to find out when a feed updated, so it's kind of confusing when this happens.

**Comment by polyzen** [comment]
For me it would be preferable if it worked the other way around and didn't count query feeds. I use one to aggregate all unread articles (so the notification count is always double), and I do not have any hidden feeds.

**Comment by Minoru** [comment]
I think counting hidden feeds is plain wrong. If they're hidden, the user probably doesn't care about their flags/counts/status. So I'm tagging this with "bug".

@polyzen, I see your point too, but since it's a slightly different request, let's move to another issue. I created #446 for that.

**Comment by Minoru** [comment]
Thinking of an extended reply to #446 made me realize that these two issues are more intertwined than I originally thought.

Separately, it's all clear:
* articles in hidden feeds shouldn't be counted, because user took an action to hide the feed and apparently wants its articles to be out of the way;
* query feeds never have articles of their own—they always borrow some from other feeds. So it makes sense not to count their contents towards "total" and "unread" counts, since it will leave to double accounting.

The solution is to ignore both kinds of feeds.

However, this will lead to a count of zero in @Aicaya's example, which is even more wrong than double-accounting :)

So what's the *correct* solution? I think we need to take a different approach to counting. Right now, "total" and "unread" are just sums of "total" and "unread" counts over all feeds. That's where duplicates come from: in @Aicaya's example, when Newsboat puts 2 and 2 together, it doesn't know that the first two articles are the same as the other two. For correct accounting, we need to compile a list of all the articles there are in non-hidden feeds, then count their number and how many of them aren't read yet. Luckily each article is uniquely identifiable by its GUID, preventing us from counting the same article twice.

We count articles for two purposes: notifications and the title line. Feedlist [counts them itself](https://github.com/newsboat/newsboat/blob/bd05df7a122d386554c7b1b38cd460ba630ab402/src/feedlistformaction.cpp#L543-L555), while Reloader (where notifications come from) [defers to FeedContainer](https://github.com/newsboat/newsboat/blob/bd05df7a122d386554c7b1b38cd460ba630ab402/src/reloader.cpp#L223-L226), which [implements](https://github.com/newsboat/newsboat/blob/bd05df7a122d386554c7b1b38cd460ba630ab402/src/feedcontainer.cpp#L227-L244) "sum over feeds" formula. To move this issue forward, the following needs to be done:
- [ ] make feedlist use FeedContainer's methods just like Reloader does
- [ ] tweak FeedContainer's methods to use "a list of articles" approach I mentioned above.
