### ISSUE TITLE
Mark feed as read older than some hours automatically?

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#452]
Is it possible to mark feed as read automatically older than certain number of hours? I could use cron for making it automatic. But is there a command to check if feeds are older than x hours then make it read. 

I think its a good feature, as the number of feeds have become more than that can be managed.

**Comment by Minoru** [comment]
No, this isn't possible. Newsboat doesn't even have anything that operates on the scale of hours, it's days and more:
* you can set [`keep-articles-days`](https://newsboat.org/releases/2.14.1/docs/newsboat.html#keep-articles-days) so older articles get deleted. Removal occurs when you close Newsboat;
* [hide](https://newsboat.org/releases/2.14.1/docs/newsboat.html#_tagging) the original feed and create a [query feed](https://newsboat.org/releases/2.14.1/docs/newsboat.html#_query_feeds) with a filter like `age < 1` ([docs on age](https://newsboat.org/releases/2.14.1/docs/newsboat.html#attr-age));
* simply use `age < 1` as a filter.

I can't agree that marking something a user didn't read as read is correct, so I'm slightly against such a feature. (But I'm keeping this open for now because I want to sleep on it.)

Try [killfiles](https://newsboat.org/releases/2.14.1/docs/newsboat.html#_killfiles) to filter out some of the stuff you aren't interested in.

**Comment by anishmittal2020** [comment]
Actually it might be useful for this use case :

I have a separate url file for all the news related stuff. So I would like to do the above only for this case.

**Comment by Minoru** [comment]
That use case is already covered by tags and query feeds:
1. tag all the news-related feeds with a hidden tag, say "!news";
2. add a query feed that selects news that are fresh: `tags # "news" and age < 1`.

This pulls all the feeds into one, so not strictly equivalent to what you suggest, but I believe it is close enough.

Once we implement per-feed settings (#83), it will be possible to set `keep-articles-days` for each feed, which is even closer to what you propose. But automatically marking something without user's command—sorry, but probably won't happen ever.
