### ISSUE TITLE
Failure to Authenticate using the oldreader-passwordeval option

### ISSUE THREAD

**Issue by GeorgeHJ** [newsboat/newsboat#455]
newsboat 2.14.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html
newsboat 2.14.1
System: Linux 4.20.11-1-MANJARO (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.0 nghttp2/1.36.0 (compiled with 7.64.0)
SQLite: 3.27.1 (compiled with 3.26.0)
libxml2: compiled with 2.9.9

Steps to reproduce the issue:

1. Use `gpg` to encrypt the password in the file oldreader.pw.gpg

2. Use the option `oldreader-passwordeval "gpg -d ~/.config/newsboat/oldreader.pw.gpg"` in the config file.

3. Run Newsboat and receive the message:

> Loading URLs from The Old Reader...Authentication failed.

**Other info**:

When I review the log, I see this:
>[2019-02-24 21:25:51] DEBUG: OldReaderApi::authenticate: Auth =
[newsboat.log](https://github.com/newsboat/newsboat/files/2901511/newsboat.log)

This suggests to me a regression in how authentication with the Old Reader API is handled. The fix has been to use `oldreader-password` in my conf file again. This is unfortunate as I was trying to avoid having my password in plain text.

**Comment by Minoru** [comment]
Sorry, I couldn't reproduce this. I encrypted my password like this:

```shell
$ echo 'password' | gpg -e > oldreader.pw.gpg
```

(had to enter the recipient name and press Enter to enter an empty line). Then I used a config with this option:

```
oldreader-passwordeval "gpg -d ~/src/newsboat/oldreader.pw.gpg"
```

And it worked fine.

I have two suggestions:
1. double-check that `gpg -d` *does* print out the password you want;
2. replace GPG invocation with `echo YOUR_PASSWORD` to check if it's Newsboat's fault or GPG's. If it still fails, there is something wrong with Newsboat; if it works, there is something wrong with GPG or how it is invoked.

I also redacted your email and password out of the log you provided. Please be more careful with your credentials. (And no, Newsboat can't strip your password from the log because it is in a commented line).

**Comment by GeorgeHJ** [comment]
Thanks for catching that rookie error.

I have a working fix in place. I think it is down to gnupg configuration. Something seems to have changed recently.

I remedied the issue by appending `2>/dev/null`. Seems that there has been a change to I/O that broke my previous config. `gpg` is transmitting credentials to `stderr` which seems to have been the cause of my problems judging by the fix.

It works now, and I changed my password.

**Comment by GeorgeHJ** [comment]
No, that's not it.

I was configured to use the pinentry-curses program. It seems that that has started to cause issues as things work fine with the gtk pinentry app. It used to work, but it's no great hardship to change.

This is starting to all whoosh over my head to be honest. Here's what I think may have happened:

1. Having decrypted the file manually, Newsboat was able to eval the password.

2. Without prior decryption, I was no longer able to access pintentry-curses program through Newsboat. When pinentry-curses failed, so did Newsboat's attempt to authenticate.

**Comment by Minoru** [comment]
We recently rewrote functions that run external programs; perhaps we changed the behaviour slightly, and broke pinentry-curses as a result?

Can you post a minimal complete configuration which I can use to recreate the bug? Just tell me what to install and how to configure it. I already have GPG and a key I can use for testing.

**Comment by GeorgeHJ** [comment]
My GPG configuration is all stock except for `~/.gnupg/gpg-agent.conf`. To replicate it, you need to add: `pinentry-program /usr/bin/pinentry-curses` . Putting this parameter back in the file re-broke newsboat just now.

Because the `gpg` program automatically chooses a context-appropriate pinentry program, I was able to replicate the failure by dropping to a TTY (which I'm pretty sure also uses it) on my laptop. So I think we can isolate pinentry-curses as a definite factor.
 
> \# General RSS settings
> max-items 100
> auto-reload "yes"
> reload-time "10"
> 
> \# The Old Reader Integration
> urls-source "oldreader"
> oldreader-login "$MYEMAIL"
> oldreader-passwordeval "gpg -d /home/$MYUSER/.config/newsboat/oldreader.pw.gpg"
> oldreader-show-special-feeds "no"

Let me know if you need anything else.

**Comment by Minoru** [comment]
Reproduced with current master (f03cd8d8b3cb4d5f4ed718cc48ea329b2c934baa). Couldn't reproduce on r2.12 tag (c83c4047a086cd8859e9b21857e1a8837062e555), which predates Rust code; this means that this bug is a regression caused by the rewrite. Apparently the old `utils::get_command_output` didn't prevent the command from taking over the terminal, while the new one does (or maybe the new one clears the environment or something and confuses pinentry-curses).

I'll dive deeper into this tomorrow. Thank you for the clear instructions, @GeorgeHJ!

**Comment by GeorgeHJ** [comment]
Phew, we got there in the end. Glad to be of assistance.

**Comment by Minoru** [comment]
@GeorgeHJ, I believe I fixed this in the bugfix/455-get_command_output-inherit-stdin branch. If you can compile Newsboat from source, please compile that and confirm that the bug is fixed. If you can't compile, just wait for the 2.15 release at the end of March, and test it then.

**Comment by GeorgeHJ** [comment]
I will clone and compile manually when I have some time off next week.

Had a quick go with the AUR git package but it wouldn't work—that was just me being lazy though. I need some quality time with git before I can report back properly.

**Comment by GeorgeHJ** [comment]
OK, having cloned, switched branch and checked out commit `0a260de8b859ba68a728cfeba808d4c1007d7933`, I can say that `newsboat` is back to working with `pinentry-curses` both in X and in the TTY.

Thank you for the swift fix! I am going to revert my configs again and track the releases. I'll be keen to play with 2.15 when it's out.

Here's my git status:
>HEAD detached at 0a260de8
>nothing to commit, working tree clean

**Comment by Minoru** [comment]
Thanks for testing it, @GeorgeHJ! I merged that PR to master, it will be released with Newsboat 2.15 at the end of this month.

**Comment by Knusper** [comment]
Sorry for digging out an old bug report, but I have the same problem with the newest version. Not for oldreader, but for Nextcloud. 

I do  `echo 'password' > gpg -e ~/.newsboat/password.gpg` and 
have `ocnews-passwordeval "gpg --decrypt ~/.newsboat/password.gpg"` in my configuration.   If I do `echo 'password'` in the configuration it works fine.   Strangely the password entry dialog  does not even show up (pinentry)..

**Comment by Minoru** [comment]
@Knusper, what Newsboat version are you running exactly? Just to make sure we're on the same page?

Can you run `newsboat --log-level=6 --log-file=newsboat.log`, grep the log for any confidential info like passwords or domain names, and post the log?

**Comment by Knusper** [comment]
Sorry, I already deinstalled the snap and installed it via apt on debian
oldatable.
The snap was the latest version - in debian oldatable I have 2.13 - but it
works fine now.

**Comment by dennisschagt** [comment]
I think @Knusper's issue was caused by the Snap strict confinement configuration.
Due to our use of strict confinement, the Newsboat application is not allowed to start executables on the host system (except for a few whitelisted executables like `xdg-open` and maybe `echo`).

We already know this is an issue when configuring a browser ([FAQ entry](https://newsboat.org/releases/2.25/docs/faq.html#_cant_start_browser_im_using_newsboats_snap_package)) but that does not mention the other places where this limitation can occur (like the `...-passwordeval` options).

Somewhat related (explaining why we use strict confinement)
- https://github.com/newsboat/newsboat/issues/1112#issuecomment-665737771
- https://github.com/newsboat/newsboat/issues/599#issuecomment-602599496

**Comment by Knusper** [comment]
Ok, thanks for the clarification.  I figured it out after I had issues with
the browser as well, and read the related Faq.
