### ISSUE TITLE
Purge appears not to work with query feeds

### ISSUE THREAD

**Issue by gleachkr** [newsboat/newsboat#456]
Newsboat version 2.14.1:

Steps to reproduce the issue:

1. enter a query feed

2. press ^D and then $ to delete all and purge. Purged items disappear.

3. exit and reenter the feed. The purged items are back.

**Other info you think is relevant**:

Deleted and purged items also remain after exiting and reentering newsboat. The
query feeds are aggreating items from hidden feeds.

**Comment by Minoru** [comment]
Reproduced on f03cd8d8b3cb4d5f4ed718cc48ea329b2c934baa. Will look deeper into this later; want to finish #455 first.

Thank you for the report, @gleachkr!

**Comment by Minoru** [comment]
@gleachkr, I believe I fixed this in the bugfix/456-purge-in-query-feeds branch. If you're able to build from Git, please do so and verify that the bug is gone. Otherwise just wait for the 2.15 release at the end of March—the fix will be included there.

(I'll close the issue when I merge the fix into master branch.)
