### ISSUE TITLE
Makefile should install "contrib" directory alongside documentation

### ISSUE THREAD

**Issue by m040601** [newsboat/newsboat#474]
First of all thank you for your work and dedication to this project. Long time user that really admires the maintanance you've been doing on github.

Background
----

There is a ton of interesting and **extremelly**  usefull stuff in the "contrib" folder. This stuff may also keep improving with added fresh, curated and updated material from external contributors. These examples of scripts, configurations and others provide:
- a ready to use practical template of what is being more theoretically described in the in the docs/manual
 - ideas for doing stuff you hadn't even thought of yourself, just by reading the docs
 - stuff that might seem "obvious" to the developers, but not for the users. Even advanced ones
 - an invaluable help with more advanced and difficult stuff, example filtering/scripts (snownews)

The "problem"
----
Although this "contrib" folder is available in the "source" release or git, it is not available in the the installed newsboat documentation folders. For example, on ArchLinux, the installation packager reads this on the currently shipped Makefile:

```
install-docs: doc
	$(MKDIR) $(DESTDIR)$(docdir)
	$(INSTALL) -m 644 doc/xhtml/* $(DESTDIR)$(docdir) || true

install-examples: doc/example-config
	$(MKDIR) $(DESTDIR)$(docdir)/examples
	$(INSTALL) -m 644 doc/example-config $(DESTDIR)$(docdir)/examples/config 
```

and you end up with a usr/share/doc/newsboat/ folder:

```
├── docbook-xsl.css
├── examples
│   └── config
├── faq.html
└── newsboat.html
```

That is you do get all the generated html documentation. But you end up missing the "contrib" folder. You also do not get the CHANGELOG file, nor  the "example-bookmark-plugin.sh" shipped. That may be "obvious" for long time users, but not for first time users.

Even I, my self a long time user, have to come back to the repo to peak at the "contrib" folder. Sometimes it's how to correctly do scripting, use quoting, use variables, "include" files,  or technical stuff that I'm in doubt. Some times I even find recent fresh updated stuff in there that I hadn't even thought off . Crazy new ideas for scripts, pipes, integrations etc.

Solution
---
Change the Makefile to make that "contrib" folder available on the user docs folder.
Change the Makefile to ship a separate txt "CHANGELOG"  as well. The change log should mention things like "Added new example script by Joe in the contrib folder" etc

Additional improvements: 
---

### What more could be in the "contrib" folder ? how to curate it better ?
- ask more actively for contributions
- collect more "crazy" macro ideas, bookmark, script ideas.
- separate in "advaced", "basic", "quickstart" folders
- name the files by author (like tmux and others), example, "joe.config" , "ben.bookmars.sh"
- tips on how to better organize your "config" file
- remove outdated/obsolete scripts/examples 
- folder for technical advanced "hacking" ? sql database etc ...

### Special attention to the "scripts_and_filters_snownews_extensions" case.

I find this a killer function that doesnt get the attention it deserves. The old UNIX way of combining simple things/scripts to compose/pipe/integrate to much more exponentialy useful ones. Nowadays I even see technically"competent people that have kind of "abandoned" RSS miss this.

Newsbeuter and Snow news are already more than 12 years old.
The Internet has changed, new services appeared, others disappeard. New scripting techiques evolved etc. Some examples in the "contrib" folder are already 10 years old. Some services, ex: "bookmark-delicious.sh" dont exist anymore. Some others use obsolete scripting techniques with outdated dependencies.

A lot of this originated in snownews. We currently have this on the documentation:

> If you need to write your own extension, see this short guide for an introduction. A collection of existing scripts might also help.

This currently points to stuff that was last updated 10 years ago. 
https://archive.kiza.eu/software/snownews/snowscripts/extensions/
https://web.archive.org/web/20090724045314/http://kiza.kcore.de/software/snownews/snowscripts/writing

Current project page is https://github.com/kouya/snownews.

Although there is still a ton of valuable stuff in there to learn, I find it insufficient.

Some times I pick up something fresh and interesting from a Reddit post, usually on https://www.reddit.com/r/commandline. Some times a twitter post. Some times I'm lucky to find someone's dotfiles, with a "newsboat scripts" . It's the fragmentation of the Internet ? On github code and repos search, I also find it extremely difficult to search and find examples of these kind of (up to date) snownews style scripts in github and others. 

I'm thinking that just like Firefox/Greasemonkey has a place to collect user extensions/addons, we could use something like that for Newsboat. There is no "central" place to collect this valuable knowledge.

Some suggestions:
- maybe actively ask the current newsboat users "what cool things have you been doing with filters lately ?"
- include a special folder in contribs with some curated scripts ?
- open up a wiki page on the repo ?
- create a repo, "newsboat/newsboat-extensions" accepting contributions ?
- Github has a lot to offer, try not to fragmentize to much the discussions and tips about Newsboat,
  -  on other websites, example reddit etc, always refer back to the github repo (https://www.reddit.com/r/rust/comments/9j2702/newsboat_is_rewriting_from_c_to_rust/) 
  - on the mailing list, if there was some interesting question posted and answered or some other "hidden gem tip", put it on the "contrib" folder. Or on the FAQ section

### Youtube videos

There's also some interesting recent videos or youtube from guys doing tutorials with cli apps and Newsboat. Luke Smith, gotbletu etc.

Some, are more for beginner cli users, some are realy cool advaced ones. Again this some times is stuff that might seem "obvious" for developers or long time users of Newsboat, but it has an increduble "AHWW" effect on beginners. Even more advanced cli users. It's the "It had never occurred to me, I could do that with Newsboat" effect. (I'm one of them)

podboat - Download Manager (podqueue) - Linux TUI - YouTube
https://www.youtube.com/watch?v=1ylYBDfqyPY

Newsboat Filtered Query Feeds - Linux TUI - YouTube
https://www.youtube.com/watch?v=PUxPUdyCy_U

Newsboat Starred Articles - Linux TUI - YouTube
https://www.youtube.com/watch?v=z359lWo3eQA

Luke Smith - YouTube
https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA/videos

**Comment by Minoru** [comment]
Hi! That's a lot to digest; thank you for the write-up, @m040601.

I'll implement your proposed solution. 2.16 will copy the `contrib` directory alongside the docs.

As for your other suggestions:

> ask more actively for contributions

I'll see how I can re-word the docs to make users aware of the contrib directory, and ask them to contribute.

> separate in "advaced", "basic", "quickstart" folders

This optimizes for "learning" use-case, not "using it" use-case. It's also subjective and complicated: is a script that implements OAuth2 and sends a link to Pocket "advanced", or is it "basic"? Finally, we don't have that many scripts to warrant much categorization at all. I don't think there is need for separate directories just yet.

> name the files by author (like tmux and others), example, "joe.config" , "ben.bookmars.sh"

As far as I understand, this is done to show how multiple scripts are used together to implement a particular work-flow. We only have one such "collection", and it's in getpocket.com directory. The rest of the scripts are independent. So again, I don't think there is need to change naming.

Same goes for "advanced hacking"—we only have one example of that; it's described in the docs; I don't think there is a compelling reason to do anything about it.

> tips on how to better organize your "config" file

I haven't read that many configs, and the only "best practice" I can recall is to group settings by purpose—e.g. list all `*-format` settings in sequence. Do you have any other tips in mind? Overall, I think this can be implemented as a new section in the docs.

> remove outdated/obsolete scripts/examples

Please don't expect developers to keep track of all the services that are mentioned in the contrib directory. If you notice that something went out of date, please submit a pull request fixing it, or at least open an issue to notify us.

> maybe actively ask the current newsboat users "what cool things have you been doing with filters lately ?"

There is no realistic way to do that. I solicited translations (through our mailing list) a few times, with lukewarm response. I also asked about some changes (through our issue tracker), with few responses (but all from people who actively track the project). I don't think there is a reliable way to reach people who just use the program and don't take much interest in how it's developed.

A single go-to place for extensions does sound nice, and it worked very well for e.g. Irssi. But given how many submissions to `contrib` we get, I don't see a reason to spend time developing such a service—it'll just sit unused.

Not sure what the point was regarding YouTube. Do you suggest to promote channels that describe Newsboat? I don't want to do that because that implies curation, which in turn means I have to keep up-to-date with new videos to see if there are better ones available.

In general, I don't support the idea that there should be a single definitive resource about Newsboat, and that it should be maintained by us. I'm pretty happy maintaining documentation that describes all the details, and then let others rehash and reiterate it in other words and from different angles, to better serve different users.
