### ISSUE TITLE
Promote "contrib" directory in the docs

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#475]
An idea from #474: make is more explicit that we do have a "contrib" directory, and that users can submit their own scripts and colorschemes to be included there.

**Comment by Minoru** [comment]
Git has a nice /usr/share/doc/git/contrib/README which explains that:
- scripts in "contrib" are experimental;
- scripts in "contrib" are not maintained by Git maintainer;
- patches to scripts should be sent to the script's author first. Author may ACK it, and forward to Git maintainer;
- old and obsolete scripts might be removed from time to time.

I think we should say the same in our docs, and put the very same words in the README in the contrib directory.

**Comment by amritbrar** [comment]
@Minoru Here was my idea for the `contrib/README.md`:

Contributed Software
----------------------------

`contrib/` contains interesting or useful software that has been contributed by
the community.  The intention is to keep them all in one place which is easily
accessible for users looking to extend `Newsboat`.

Important things to note about `contrib/`:
* Scripts are considered to be experimental and many not work.
* Scripts are not maintained by the Newsboat team.
* Any fixes to scripts should be sent to the original author if available.
  Otherwise, send a pull request.
* Old and obsolete scripts may be removed from time to time.

- - - - -

A few questions:
- Should there be a reference to `contrib/` in the main README? Users may have a hard time finding it. Maybe a reference in the Manpage?
- Should there be a note about contributing new scripts? If so, what should the process be for that? (Issue, Pull Request, Mailing List, IRC?)

**Comment by Minoru** [comment]
This looks great! :+1:

> Should there be a reference to contrib/ in the main README? Users may have a hard time finding it. Maybe a reference in the Manpage?

I'd mention it at the end of Quickstart section in the HTML doc. That way, people learn about contrib/ *after* they got the basic setup going, but *before* they spent a ton of time reading the rest of the doc. If they are aware of contrib/ while reading the doc, they can look into contrib/ for examples of what they're reading about.

Manpage is a reference, I don't think contrib should be mentioned there.

> Should there be a note about contributing new scripts? If so, what should the process be for that? (Issue, Pull Request, Mailing List, IRC?)

I think the proposed readme already covers that: "otherwise, send a pull request". I'd change that to "GitHub pull request or a patch on the mailing list", but other than that, it looks fine to me.

**Comment by amritbrar** [comment]
> I'd mention it at the end of Quickstart section in the HTML doc. That way, people learn about contrib/ after they got the basic setup going, but before they spent a ton of time reading the rest of the doc.

https://newsboat.org/releases/2.21/docs/newsboat.html doesn't have "Quickstart" from what I can tell, do you mean at the end of `First Steps`?

**Comment by Minoru** [comment]
Yeah, sorry, I meant "First Steps".
