### ISSUE TITLE
open-goto

### ISSUE THREAD

**Issue by Sermak-GIT** [newsboat/newsboat#476]
The command open-search opens a prompt with the title "Search for: ". Is there a way to achieve the same for the goto command? Hitting the key chord ':' + 'g' + 'o' + 't' + 'o' + ' ' is tedious, while the prime-real-estate '/' button occupies a feature I never use. Being able to define aliases would help (e.g. :g instead of :goto), but this would still require 3 keys. Alternatively, having a key that opens a command line that already contains some text would be amazing

**Comment by Minoru** [comment]
Indeed, there is no way to do this at the moment. I'm definitely against introducing more snowflake commands like `open-search`, but I'm not sure what the alternative is. I guess in my ideal world, commands and operations will be unified, and if they need arguments, they'll either accept them on command like, or ask for them interactively. This way, we'll be able to create bindings that do our favourite search, or bind `/` to `goto` and answer its prompt.

**Comment by Minoru** [comment]
Answering questions from https://github.com/newsboat/newsboat/pull/478:

> You already have some inconsistencies (i.e. both a save command and a save operation, although they do slightly different things)

That's a good point. However, `:save` and `save` only differ in the interface: one wants the filename as a command-line argument, another asks for it interactively. A unified `save` command would do both: use an argument if it's provided, otherwise ask interactively.

This behaviour will be common to all commands, so it should be abstracted away. I think a command should only declare how many arguments it takes, and what interactive prompt to use for each. Then `FormAction` can use QNA to ask for missing arguments, and [`--execute`](https://newsboat.org/releases/2.15/docs/newsboat.html#_commandline_commands) (the third command-like interface in Newsboat) can outright fail if there are not enough arguments.

> Out of interest: How exactly do you envision unifying commands and operations? […] what would be the first step in this process of refactoring?

The first big step would be giving commands an entity. Right now, command handling looks like this:

1. user presses `:` to start the command line;
2. user enters some string and presses Enter;
3. the string gets passed to current form's `handle_cmdline`, where it is parsed and immediately acted upon;
4. if current form doesn't have a handler for this command (e.g. `set` or `quit` which are common for all dialogs), the command is forwarded to the base class (`FormAction::handle_cmdline`).

Very ad-hoc. This is in drastic contrast to operations, which have an `enum Operation` in `include/keymap.h` and use constants of that `enum` to represent different ops. We need the same for commands. I guess it can be something like this:

```c++
enum class CommandType {
    QUIT,
    SAVE,
}

struct Command {
    CommandType cmd;
    std::vector<std::string> args;
}
```

Before introducing this `struct`, though, we need to split parsing and handling. If you look at e.g. `ItemListFormAction::handle_cmdline`, you'll see a call to `utils::tokenize_quoted`, followed by an `if` ladder than handles different commands. So the actual steps here would be:
1. move bodies of `if`s to separate methods (and not just in `ItemListFormAction`, but in all children of `FormAction`);
2. move parsing (yep, that single `utils::tokenize_quoted` call) into a protected static method of `FormAction`;
3. introduce the aforementioned `struct`, changing the return type of the parsing method, and replacing `if` ladders with `switch`es.

The next big step would be re-using the code that handles similar operations and commands—e.g. `:save` and `save`. The goal is to have a single method that does the actual work for each command-operation pair, leaving the "interface" work (QNA for operations, command-line parsing for commands) up to `handle_operation()`/`handle_cmdline()`.

The next big step would be introducing the abstraction I mentioned in the beginning: for each command-operation pair, we'll declare the number of arguments, and a list of prompts. `handle_operation()` would use that for QNA. `handle_cmdline` would use that when checking the number of parsed tokens.

The final big step would be unifying `enum Operation` with `struct Command`, and turning `opdescs` array (in `src/keymap.cpp`) into a registry of all available commands. Update command-line parsing to handle all of them. Remove the word "operation" from the docs, because there is no difference between ops and commands any more.

Quite a chunk of work, and in a less-traveled part of the code to boot, but I'm confident this can be done even by someone who never seen Newsboat's internals before.

**Comment by dennisschagt** [comment]
I think this use case is now possible because of https://github.com/newsboat/newsboat/pull/1249.
For example, use config option:
```
bind-key / goto-title
```

It might still be useful to integrate "commands" and "operations".
@Minoru: Do you want to create a separate issue for the ideas introduced in https://github.com/newsboat/newsboat/issues/476#issuecomment-480580542?

**Comment by Minoru** [comment]
@dennisschagt Yep, good idea, thanks! I extracted that comment into #1258.

Since this issue has been addressed, I'm closing it.
