### ISSUE TITLE
Error: couldn't parse filter command ...

### ISSUE THREAD

**Issue by a-wilkinson** [newsboat/newsboat#479]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.15.0
System: FreeBSD 12.0-RELEASE-p2 (amd64)
Compiler: g++ 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)
ncurses: ncurses 5.9.20140222 (compiled with 5.9)
libcurl: libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 nghttp2/1.35.1 (compiled with 7.64.1)
SQLite: 3.26.0 (compiled with 3.27.1)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. Add the following URL into $HOME/.newsboat/urls

https://tools.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml

2.  Attempt a filter using the key binding 'F'

Type in:  IOS 

For a search string

I get the error:

_**Error: couldn't parse filter command!**_

  -Alex

**Comment by Minoru** [comment]
Hi! Newsboat returns this error because "IOS" is not a filter expression. You have to use `title ~= "IOS"` or something like that; see this section for details: https://newsboat.org/releases/2.15/docs/newsboat.html#_filter_language

If all you want is search in articles' titles and contents, use ordinary search instead: type slash (/), then your search phrase, then press Enter.

**Comment by a-wilkinson** [comment]
Ah, yes. Thanks!

  -Alex
