### ISSUE TITLE
`newsboat -x print-unread` doesn't report that another instance is running

### ISSUE THREAD

**Issue by FrostyX** [newsboat/newsboat#483]
**Newsboat version**:

newsboat 2.11.1

**Steps to reproduce the issue**:

1. Run `newsboat`
2. Open another terminal window
3. Run `newsboat -x print-unread`

It doesn't print anything, even though I have unread articles. It should at least print an error, that another instance is running and data can't be fetched from the database. **However**, I am able to manually open the database and get the number of unread articles, while `newsboat` is running, so I can't see any technical reason, why `print-unread` should not work.

    [jkadlcik@chromie ~]$ pidof newsboat 
    32504
    [jkadlcik@chromie ~]$ sqlite3 ~/.newsboat/cache.db
    sqlite> select count(*) from rss_item where unread=1;
    20

**Other info you think is relevant**:

This issue was submitted even for newsbeuter, I don't know why the OP didn't submit it here.
Please see https://github.com/akrennmair/newsbeuter/issues/608

**Comment by Minoru** [comment]
> It should at least print an error, that another instance is running and data can't be fetched from the database.

Agreed. I guess the existing message can be re-used ("Error: an instance of %s is already running (PID: %u)").

Note that Newsboat *does* indicate failure via the exit code, so you can work around this with something like `newsboat -x print-unread || echo "Failed to fetch unread articles count" >&2"`.

> I  am able to manually open the database and get the number of unread articles, while newsboat is running, so I can't see any technical reason, why print-unread should not work.

Unread articles count isn't just a number of articles with `unread` of 1. Killfiles "hide" articles, and those shouldn't be counted as unread. To apply killfile rules, Newsboat has to read its config, and then examine each item in the DB. So `print-unread` isn't something that can be trivially implemented outside of Newsboat.

If we do away with locking, counts might become inaccurate as another instance might modify the DB while `print-unread` is running. This is a last-resort solution.

**Comment by Minoru** [comment]
Forgot to say: thanks for the report! Even small things matter.

**Comment by FrostyX** [comment]
Thank you for the reply @Minoru,

> Unread articles count isn't just a number of articles with unread of 1. Killfiles "hide" articles, and those shouldn't be counted as unread. To apply killfile rules, Newsboat has to read its config, and then examine each item in the DB. So print-unread isn't something that can be trivially implemented outside of Newsboat.

Aha, I didn't know about killfiles (cool feature though, I will definitely need to try them). Now, I see, that it is not a matter of just one select, to get the unread count, but if we talk about fixing the `print-unread` feature, not implementing it from the outside, it shouldn't block anything, right?

> If we do away with locking, counts might become inaccurate as another instance might modify the DB while print-unread is running. 

Unfortunately, I don't know C++, so I can't check how the locking works, but theoretically, there IMHO shouldn't be a problem with an inaccurate count. Maybe you can hint me, what I am missing. IMHO sqlite supports multiple connections to a database (it should since I am able to run the unread count select, while the newsboat is running). When nothing is writing to a database, which is most of the time, `print-unread` should be able to read the correct unread count. When newsboat is refreshing the feeds and writing to the database, nothing can't read at that moment (which is IMHO sqlite feature, so no external locking mechanism should be required). I am not sure, whether such reading request would be on hold until the database is unlocked from writing, or rather immediately finished with an error, that newsboat is currently writing. Either way, `print-unread` should always print the correct count, and should work most of the time (except when feeds are being refreshed, which like tens of seconds in an hour, average?)

Am I missing something?

**Comment by Minoru** [comment]
I wanted to show you some actual code, and found that I was wrong about killfiles: `print-unread` doesn't take them into account. It's using [the very same query](https://github.com/newsboat/newsboat/blob/86097d60a143dd87e700586b2609a679ba7082dc/src/cache.cpp#L1006) you used. Now that's kinda embarrassing, I'm supposed to know this stuff :) Anyway, I consider this behaviour a bug, since Newsboat displays different counts in UI and the output of `print-unread`. There's now an issue about that: #484.

Your description of locking inside SQLite seem correct to me; each query runs in isolation and either succeeds or fails. But I now think that this argument of mine was quite weak. Newsboat doesn't use DB transactions, which might lead to concurrency problems, but I can't foresee any for `print-unread`.

Whoever ends up implementing will have to do the following:
* move `print-unread` implementation from `Controller::execute_commands` somewhere else;
* call that new function earlier in the `Controller::run`, somewhere before the locking;
* take care of a situation when there is no cache file yet.

And I think it makes more sense to implement #484 first.

**Comment by Minoru** [comment]
Turns out this bug was fixed a while ago, in f5ab30dc1657c9f88e76061bbb5c9424f27a4068, which is included in Newsboat 2.22.

The discussion about transactions was useful, but we're nowhere close to moving to that, so I'll just close this issue now.
