### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by ma1uta** [newsboat/newsboat#496]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.13.0 (https://packages.debian.org/buster/newsboat)
System: Linux 4.19.0-4-amd64 (x86_64)
Compiler: g++ 8.2.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.6 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.61.0)
SQLite: 3.27.2 (compiled with 3.25.1)
libxml2: compiled with 2.9.4

Hostname:
Linux servername 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

Steps to reproduce the issue:

1. start newsboat
2. waiting while it updates cache
3. segfault

[Log file](https://github.com/newsboat/newsboat/files/3098025/log.zip) (warning, large file, 3M)

**Comment by Minoru** [comment]
Thank you for the report! I re-uploaded the log to GitHub, because I've had enough links expire on me :)

Don't have any ideas from a quick glance at the log. Will take a closer look in the evening today.

**Comment by Minoru** [comment]
Looks like it's crashing after creating an RSS parser. No idea why. I don't have a setup to reproduce this, so I'll try to guide you to get more data.

A couple things you can try:
1. this might be fixed by https://github.com/newsboat/newsboat/pull/321. Can you compile from Git and check if that works?
2. can you run it under GDB to obtain the stacktrace? Type `gdb newsboat`, then `run`, wait for it to crash, then type `backtrace full`, and post the output.
3. it might be a concurrency bug. Can you remove `reload-threads 3` from your config, and try again?
4. very unlikely, but it might be some other setting. Can you remove everything but `urls-source`, `ocnews-url`, `ocnews-login`, and `ocnews-password` from your config, and try again?

Have you updated your ownCloud recently? What version are you running? Is it really ownCloud, or is it nextCloud?

**Comment by ma1uta** [comment]
I am using Nextcloud 15.0.7

Ok, I will try run it under gdb a little bit later.

**Comment by ma1uta** [comment]
Latest version from git works. I think that it is a #321.
