### ISSUE TITLE
Fork description

### ISSUE THREAD

**Issue by Bfgeshka** [newsboat/newsboat#5]
It is mentioned that newsboat is a fork of newsbeuter. But there's no mention of why it is forked and what is changed in readme.md or newsboat.org. No need to have full list of changes, but at least create an entry in readme for fundamental differences.

As newsbeuter user, I am interested in this product, but I have no idea what to expect from it and I believe that some people who discovered this project have same feeling about it.

**Comment by Minoru** [comment]
That's a good point; thanks! I've updated the README to make the difference more apparent.

I don't want to explicitly set any expectations because I don't have an explicit agenda myself. Looking at those two years when I maintained Newsbeuter, I guess one could say that my priorities are bugfixing and gradual modernization. Those are emergent, though; I didn't plan to concentrate on those things, they just *happened*. You can probably expect more of them in the near future (couple of years), then you'll have to re-calibrate depending on how Newsboat does.
