### ISSUE TITLE
Hide tilde on end of buffer

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [newsboat/newsboat#507]
I can't seem to find the option when using the internal pager and I'm wondering if the option exists.

**Comment by Minoru** [comment]
No, there is no such option. Is the tilde annoying?

**Comment by eyvindbjartiandersen** [comment]
Yes I'm very much annoyed by the tilde. In my Neovim I hide the tilde as well. It's not a clean look.

**Comment by Minoru** [comment]
I see. Turns out these symbols aren't displayed by Newsboat itself; they're added by STFL (see `wt_textview_draw()` in [widgets/wt_textview.c](http://svn.clifford.at/stfl/tags/stfl-0.24/widgets/wt_textview.c)). I don't see any `if`s surrounding that code, so it doesn't look we can affect if from Newsboat.

STFL is slated to be replaced, though (see #232), so one day, we'll be able to add a setting to hide/replace tildes. I'm re-labeling this issue to an enhancement request. Thanks for bringing this up!
