### ISSUE TITLE
multiple instances with different subscriptions?

### ISSUE THREAD

**Issue by prankousky** [newsboat/newsboat#523]
Hi,

I use `newsboat` for regular rss feeds, which works fine. However, for easier readability I'd like to run another separate instance that only displays my youtube subscriptions (which I have downloaded as an opml file).

Is this possible, if so, how? I'd like to keep my original config with my "actual" feeds (meaning blog posts etc.), but still be able to **only** browse YouTube subscriptions if I want to view some videos; this way I could avoid going on youtube in my browser, copy some video url, then feed it to `mpv`...

Thanks in advance for your help.

**Comment by Minoru** [comment]
Hi! Yes, this is indeed possible. Newsboat lets you specify the path to urls file, so you can have two: one for your "actual" feeds, another for YouTube. Here's how to achieve that:

1. Download the OPML file;
2. run `newsboat --import-from-opml=path_to_your_subscriptions.opml --url-file=~/.newsboat/youtube-urls`, which will parse the OPML file and put all the urls into ~/.newsboat/youtube-urls instead of the default ~/.newsboat/urls;
3. when you want to view your YouTube subscriptions, start Newsboat like this: `newsboat --url-file=~/.newsboat/youtube-urls --cache-file=~/.newsboat/youtube-cache.db`.

This will use the same ~/.newsboat/config for both instances, but separate urls files and separate caches.

If you want separate configs as well, just create them and use `--config-file=path` to specify what should be used when. Common parts can be put into a third file, and [`include`d](https://newsboat.org/releases/2.15/docs/newsboat.html#include) into the other two.

If you don't specify different caches for different instances, you'll run into a several limitations:
- only one instance at a time can work with a given cache file — you won't be able to run two simultaneously off the same cache file;
- if you didn't disable [`cleanup-on-quit`](https://newsboat.org/releases/2.15/docs/newsboat.html#cleanup-on-quit), instances will remove each other's data.

Naturally, if you omit the option, the default will be used. So your "actual" instance can be run just as `newsboat`, whereas the "YouTube" instance will need both `--url-file` and `--cache-file`.

Does this answer your question?

**Comment by prankousky** [comment]
Thank you!

I believe the opml file that youtube provided is not compatible. When I ran your first command, it did not create `~/.newsboat/youtube-urls`. I manually tried to create it by `grep`ing each URL from that opml file and manually writing it to `~/.newsboat/youtube-urls` (one URL per line).

When I then run `newsboat --url-file=~/.newsboat/youtube-urls --cache-file~/.newsboat/youtube-cache.db` I will get

```
Starte newsboat 2.15.0...
Fehler: Eine Instanz von newsboat läuft bereits (PID: 0)
```

(~= attempting to start newsboat, then not being able to because newsboat is supposedly running with PID 0). I have tried just running `newsboat --url-file=~/.newsboat/youtube-urls` without specifying the cache file, but this will only load my regular rss feeds.

My other rss feeds come from a remote ttrss instance (within my local network), not a url file. Might this cause this error?

**Comment by Minoru** [comment]
> My other rss feeds come from a remote ttrss instance (within my local network), not a url file. Might this cause this error?

Oh yes! Sorry, I didn't think of this possibility. You'll need a separate config then, one without `urls-source "ttrss" in it`, or one that re-defines that, e.g.:

```
include ~/.newsboat/config
urls-source "local"
```

Save that to e.g. ~/.newsboat/youtube-config, and run Newsboat with `--config-file=~/.newsboat/youtube-config` option.

This should also solve the "PID 0" problem.

I'll look into OPML incompatibility now.

**Comment by Minoru** [comment]
My command for OPML import didn't work because `--url-file` doesn't resolve the tilde into a path to the home directory. Same probably applies to `--config-file` and `--cache-file`. Use absolute paths for now, and I'll go fix this in the `master` branch. Sorry about the confusion I created!

**Comment by prankousky** [comment]
Awesome, almost there :) I added those lines and am able to start newsboat, but **only** when I run it like this `newsboat --config-file=/home/benn/.newsboat/youtube-config --url-file=/home/benn/.newsboat/youtube-urls --cache-file=/home/benn/.newsboat/youtube-cache.db`. When using `~` or `$HOME`, I will get the PID error again.

One last question: I added `macro y set browser "mpv %u"; open-in-browser ; set browser "elinks %u"` to the `youtube-config` (example taken from arch wiki). I assumed it would open `mpv` when I type `.y`, but it does not work. Do you have advice for this too?

**Comment by Minoru** [comment]
The tilde problem will be tracked in #524.

I should note that `$HOME` works for me with `--url-file`. You sure it doesn't for you? It's replaced by the shell, not Newsboat; what shell are you using?

> I assumed it would open mpv when I type `.y`

Should be a comma, not a dot: `,y`. Otherwise looks fine to me, but I didn't test it.

**Comment by prankousky** [comment]
My mistake. I am using different user profiles on this machine and perhaps ran it as the wrong user.  So I assume $HOME will work, but already made the alias using /home/<username>. Yes, when using `,y` it works. Thank you so much for your help. Finally no more youtube in the browser :+1:

**Comment by Minoru** [comment]
Cool, glad to be of help! ^_^
