### ISSUE TITLE
New article/feed highlighting doesn't work 

### ISSUE THREAD

**Issue by aelmahmoudy** [newsboat/newsboat#535]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat 2.13.0

Hello, this highlight setting used to work on newsbeuter, but it doesn't work on newsboat:
 
highlight feedlist "^.{4} N.*$" cyan default

**Comment by Minoru** [comment]
Hi! Thank you for the report; although in the future I'd appreciate a clear instruction of what "works" and "doesn't work" mean.

The problem was introduced in a8971bd8dd4709e785fb39bc01aba510625614c8: it adds an `<unread>` tag at the beginning of each unread item in the list, breaking the regex (the line no longer starts with four symbols and a space). I guess the correct way to fix this is to strip the tags from the line while highlighting it; but I'll need to make another code dive to make sure.

In the meantime, there are two ways to work around this:

1. remove `^` from the regex. Downside: it might start matching in the middle of feed titles. That can be remedied by renaming them with [a tilde tag](https://newsboat.org/releases/2.15/docs/newsboat.html#_tagging).

2. the commit that broke this also added a potential solution: use `color listnormal_unread cyan default`. The downside is that this works in all lists, not just feedlist.

I'm re-opening this, since the problem wasn't fixed yet.

**Comment by aelmahmoudy** [comment]
The second workaround is fine for me. Thanks
