### ISSUE TITLE
Unable to remap space in internal pager

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [newsboat/newsboat#546]
Is this not possible?. I'm able to remap space to mark-as-read for example, but when in the pager it does a pagedown.

**Comment by Minoru** [comment]
Yes, that binding is hard-coded—see `View::set_bindings` in src/view.cpp. It's probably a breaking change to make it un-bindable, because it'll make it possible to make the pager unusable with `unbind-key SPACE` or `unbind-key -a`. But we can probably make it re-bindable, i.e. if user hasn't bound SPACE to anything, bind it to pagedown, otherwise go with the user's binding. Patches to aforementioned method welcome.

(BTW, mark-as-read is not available in the pager. Open any article and press `?` to find out what operations there are and what keys they're bound to at the moment).

**Comment by dennisschagt** [comment]
This issue is fixed by PR #913.
