### ISSUE TITLE
Navigating filesystem in FileBrowser results in incorrect paths

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#547]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat r2.15-235-g3a1e0
System: Linux 4.19.0-5-amd64 (x86_64)
Compiler: g++ 8.3.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.64.0)
SQLite: 3.27.2 (compiled with 3.27.2)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:

1. Open Newsboat, navigate to any article, press `s` to save it. "FileBrowser" dialog is opened.

2. Press `Tab` to move focus from the input field to files list.

3. The cursor is on `..`. Press `Enter` to navigate up by the file hierarchy. In my place, I started in `/home/minoru`, so I'm now in `/home/`, and the path to file (at the bottom of the dialog) says `/home/article_title.txt`, which seems correct.

4. Use `Down` to scroll to some directory, and press `Enter`. I picked `minoru`, and thus moved to `/home/minoru`. However, the path have been updated to `/home/minoru//home/article_title.txt`.

5. Every time I change directories, the new dirpath is prepended to the current path.

**Other info you think is relevant**:

The same currently exists in DirBrowser (#531), because it copies a lot of FileBrowser's code.

**Comment by dennisschagt** [comment]
The issue can be reproduced by any combination of 2 (or more) directory changes.

- The first directory change puts the full directory path + the original filename in the `filenametext` stfl variable/field.
- A following change of directory results in the full text from that same `filenametext` to be appended to the new directory path (from first `/` but first character is `/` because of absolute path) .
