### ISSUE TITLE
terminate called after throwing an instance of 'newsbeuter::exception' what(): No such file or directory

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#56]
**Newsboat version (copy from `newsboat -v`)**: 2.10.1

Steps to reproduce the issue:

1. `error-log "/path/to-nonexistent-directory/error.log`
2. Start Newsboat.

Newsboat crashes with a message: `terminate called after throwing an instance of 'newsbeuter::exception' what(): No such file or directory`

**Other info you think is relevant**:

Originally reported on the IRC channel on October 18th, 2017. Recently appeared [here on the issue tracker](https://github.com/newsboat/newsboat/issues/49#issuecomment-343590421). As @noctux reported on IRC, Newsboat tries to write an error to the error-log, but since the file cannot be opened, the write throws, and since it's `newsbeuter::exception` and not `newsbeuter::configexception`, it isn't caught in `controller`, which leads to `terminate()` being called.

This is an edge case all right, but people are bound to run into it quite often if they migrate from Newsbeuter and delete their ~/.newsbeuter directories without checking if Newsboat works (or maybe they just `mv ~/.newsbeuter ~/.newsboat`.)

**Comment by noctux** [comment]
You can find a basic patch in my fork in the [fix-missing-file-segfault branch](https://github.com/noctux/newsboat/tree/fix-missing-file-segfault) in [commit a3c17d762f3aaf709bf350686ec0694a5b4fe612](https://github.com/noctux/newsboat/commit/a3c17d762f3aaf709bf350686ec0694a5b4fe612), which has been sitting there for some time, because I wanted to reason about whether that error reporting is sufficient and do some more testing, but have not made it yet.
So I just want to leave this here as a quick note, before someone else spends too much time on locating the flaw, it should be in that function.
If you are fine with it, I would be happy to propose it as a PR.

**Comment by Minoru** [comment]
I'd welcome such a PR, @noctux. Two points you can fix in advance:

* "failed to set error logfile" is too programmer-centric; users won't understand what's wrong and how can they fix it. Something like `strprintf::fmt("couldn't open %s: %s", cfg.get_configvalue("error-log"), e.what()` is better IMO.

* why not go one step further and run `utils::mkdir_parents` before opening the file? Of course, throwing a `newsbeuter::exception` if the function returns non-zero code.

**Comment by noctux** [comment]
OK, I'll do that then.

ad 1: I completely agree

ad 2: I guess the most common cause of that fault are typos in directory names. I personally do not want newsboat to for instance create the `.confg` directory based on the erroneous `error-log` setting `.confg/error.log` via makedir, but a clearly defined error message instead, telling me that the file is not accessible, to please check for typos and maybe suggesting to issue a `mkdir -p "$(basedir $folderpath)"` if I'm positive that the path is correct.

**Comment by Minoru** [comment]
Re 2nd point: yep, you're right. Let's give users good error message for now. (Though I guess they'll figure out what command to run by themselves—it's simple enough.)
