### ISSUE TITLE
Unexpected idle activity

### ISSUE THREAD

**Issue by Boruch-Baum** [newsboat/newsboat#563]
newsboat 2.13.0
System: Linux 4.14.0-3-amd64 (x86_64)
Compiler: g++ 8.2.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.37.0 librtmp/2.3 (compiled with 7.61.0)
SQLite: 3.27.2 (compiled with 3.25.1)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:

1. Open newsboat in a tmux window

2. Set tmux to notify of activity on another window

     set -g monitor-activity on
     set -g activity-action other

3. Go about your business in another tmux window

4. Within a few minutes, notice that tmux is indicating activity by newsboat.

**Comment by Minoru** [comment]
Hi! Thank you for the report.

If that happens exactly a minute later, it's probably us—[our main loop has a timeout of 60 seconds](https://github.com/newsboat/newsboat/blob/c89659a5a7b8e601896da90f3cc64f22129a411d/src/view.cpp#L222), after which it calls `FormAction::prepare`, which might update something. But for the feed list (the default screen, shown right after startup), that call [does nothing unless terminal width or sort order changed](https://github.com/newsboat/newsboat/blob/c89659a5a7b8e601896da90f3cc64f22129a411d/src/feedlistformaction.cpp#L78)—which probably doesn't happen in your case.

If you're trying to use activity monitoring to get notifications about new articles, check out notify-* settings. For example, Newsboat can beep when new articles arrive. This is more reliable than mere window updates.

Frankly, this is a very low-priority on my personal to-do list; e.g. I'd like to deal with i386 breakage first, and then there are a ton of more severe bugs. If someone would like to dig into this, I'd start with compiling [STFL examples](http://www.clifford.at/stfl/) and checking if they trigger this bug as well. If they do, the problem is with STFL or something further down the stack, which we can't control (but you can dig into and submit patches to). If examples don't trigger the bug, I'd start slashing code from our FeedListFormAction to see when it stops triggering the bug, and work backwards to pinpoint the line that does.

**Comment by Boruch-Baum** [comment]
On 2019-07-04 12:34, Alexander Batischev wrote:
>    Hi! Thank you for the report.
>
>    If that happens exactly a minute later, it's probably us—[1]our main
>    loop has a timeout of 60 seconds, after which it calls
>    FormAction::prepare, which might update something. But for the feed
>    list (the default screen, shown right after startup), that call [2]does
>    nothing unless terminal width or sort order changed—which probably
>    doesn't happen in your case.

Sounds like a simple fix, then. If newsboat is displaying the feed list,
don't call FormAction::prepare. Whatever cosmetic bells and whistles
there are to re-draw the display could be linked to some manual refresh
or some manual cursor or mouse movement within the window, instead of
being on a timer.

>    If you're trying to use activity monitoring to get notifications about
>    new articles

... No.

>    Frankly, this is a very low-priority on my personal to-do list

It shouldn't be.  From a security perspective, a program sitting idly in
background that shouldn't be doing anything ... shouldn't be doing
anything. Even if you trust newsboat to be benign, you're contributing
to people being complacent about any program x with the same behavior.
Security-wise, newsboat is in the class of programs that have network
access, so from a user's perspective activity not explicitly asked for
should be an alarm condition.

Even if you personally don't agree with what I wrote above, if recognize
the merit in it, this should not be low priority.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Minoru** [comment]
I mentally separate me-maintainer from me-developer. Me-maintainer has just a couple of responsibilities, but he *has* to take care of them: making high-level decisions, merging PRs, cutting releases, and tending to infrastructure like CI. Me-developer is a free gun who is only responsible for his PRs, and works on whatever he feels like—or doesn't work at all if he doesn't want to. The paragraph about "my personal to-do list" was written by me-developer. I should have made this more explicit; sorry about the confusion.

Now with my maintainer hat on: the PR that fixes this issue is going to have the same priority to me as any other non-security-critical contribution—i.e. I'll handle it chronologically with other contributions. "Security-critical" means "worthy of a CVE number". Maintainer hat off now.

You don't seem interested in working on this yourself, so I won't waste your and my time explaining how the main loop works, and what your fix will break. If you intend to look into this, drop a comment here and I'll answer any further questions.
