### ISSUE TITLE
Disable sort?

### ISSUE THREAD

**Issue by sooqua** [newsboat/newsboat#578]
**Newsboat version**: 2.15.0

Steps to reproduce the issue:
1. Go to https://newsboat.org/releases/2.15/docs/newsboat.html or `man newsboat`
2. Try to find out how to disable article sort
3. Realize there is no such option
4. Get sad

**Other info you think is relevant**:
For example I've added https://www.reddit.com/r/archlinux/top/.rss to my urls.
I've already specified "sorting" by using "/top/" in the url.
Why can't newsboat just display the articles in the same order as they appear on the rss feed?

**Comment by j605** [comment]
I see this was implemented of feeds long time ago, 86fc15c849ec4cade36fcae0dbe6e99d0e64c5b9. No idea why it wasn't done for `article-sort-order`. I am also doubtful if we need the `order` variable associated with articles as well or if there is an other way around it.

**Comment by Minoru** [comment]
@sooqua I understand what you want to achieve, and this is *technically* possible with RSS, but you'll have to build a special feed reader for this.

What you want is a browser: it'll fetch the whole feed every time, and display it as it is *right now*. This is precisely what Firefox does when you view the feed there (or used to do—I believe that functionality was removed recently).

"Real" feed readers, the ones where you subscribe to a feed, operate a bit differently: they treat the feed as a stream of updates, adding all new items to their local "historical record" of that feed.

I don't think these two approaches are compatible, because displaying the feed "as it is" requires the program to abandon history, while displaying "everything there ever been" requires it to order items in some way.

In those terms, Newsboat is a "real feed reader", not a "browser", and I intend to keep it that way.

Also in those terms, Newsboat is a "browser" for feed-list but a "real feed reader" for individual feeds, which is why we can disable sorting for feed-list but not for individual feeds.
