### ISSUE TITLE
Non-title format variable for set-tag/select-tag display.

### ISSUE THREAD

**Issue by Penguin-Guru** [newsboat/newsboat#588]
There is a variable "selecttag-title-format", but no "selecttag-format". Personally, I would like this to allow reference of (1) the number of feeds matching the tag that have at least one unread article and/or (2) the total number of unread articles associated with the tag. This seems really useful to me, but I'm a new user and so may be overlooking some things. Please let me know if so.

**Comment by Minoru** [comment]
Hi, thanks for filing this! So that new setting should be similar to [`articlelist-format`](https://newsboat.org/releases/2.16.1/docs/newsboat.html#articlelist-format) and [`feedlist-format`](https://newsboat.org/releases/2.16.1/docs/newsboat.html#feedlist-format) in that it's applied to each item in the tags list.

I think this might be a good first issue for a newcomer to tackle. Here's a few pointers:
1. the "select tag" dialog is drawn with src/selectformaction.cpp. The list is populated [in this loop](https://github.com/newsboat/newsboat/blob/01bb13982f9c285f93caba372d84e8599fe540ea/src/selectformaction.cpp#L104-L114);
2. to add custom placeholders like "%N", "%V" etc. we have an `FmtStrFormatter` class. It can be used [like this](https://github.com/newsboat/newsboat/blob/01bb13982f9c285f93caba372d84e8599fe540ea/src/selectformaction.cpp#L145-L147);
3. similar placeholders should have the same names across different `*-format` settings, so take a look at ["Format Strings" section of our docs](https://newsboat.org/releases/2.16.1/docs/newsboat.html#_format_strings) to see if something can be re-used;
4. to document the new setting, describe it in the aforementioned section, and also add a line to doc/configcommands.dsv.

I'll be happy to answer any further questions, be it here, on IRC (#newsboat on Freenode), or via the mailing list (newsboat@groups.google.com).

**Comment by Minoru** [comment]
Fixed by #590.
