### ISSUE TITLE
Cannot open anything in browser

### ISSUE THREAD

**Issue by AhabTheJudge** [newsboat/newsboat#599]
newsboat r2.16.1-dirty:

Steps to reproduce the issue:

1. Just typing 'o' to open in browser.

2. Tried setting browser to mpv with _m set browser "mpv %u"; open-in-browser_ as well.  Confirmed that opening link with mpv directly works.

**Other info you think is relevant**:
I'm a total Linux noob, so please forgive me if I'm just not understanding something simple.

**Comment by Minoru** [comment]
Hi!

Just in case: did you install Newsboat via Snap? If so, the only browser you can use is xdg-open; this is a limitation of Snap. Add `browser "xdg-open"` to your config, and `o` should work fine.

Otherwise: the default browser is `lynx`, which might not be installed. You can just change it to whatever you want using `browser` setting.

The `m` binding looks a bit incomplete. First of all, it never sets the browser back to what it was originally. Second, it should start with "macro" command:

```
macro m set browser "mpv %u"; open-in-browser; set browser "firefox"
```

Does that answer your question?

**Comment by AhabTheJudge** [comment]
Thank you for the quick response!  I think it does make sense.  So, if I
uninstall and install again without using snap, I should be able to use
other options like mpv?

Thanks again for your help

**Comment by Minoru** [comment]
You don't strictly *need* to uninstall the Snap—just be aware that in that case, you need to set `browser` to `xdg-open`, and then configure `xdg-open` to do what you want. Otherwise yes, re-installing from a package or compiling from source will let you configure the browser directly in Newsboat, and use macros as well.

Glad this was resolved quickly. I'm closing the issue now. Thanks for using Newsboat!

**Comment by ExceptionInTheRye** [comment]
Hi,

If I would like to open a URL on lynx and not be sent to an external GUI'ed browser, Firefox, for example. How can I achieve that?

Thanks.

**Comment by jinmiaoluo** [comment]
@ExceptionInTheRye 

Set `browser` to `lynx`

**Comment by Minoru** [comment]
Setting `browser` to anything other than `xdg-open` won't work in Snap, because Snap doesn't allow running external applications. @ExceptionInTheRye, I'm not sure how you're supposed to configure xdg-open for Snap; please ask on Snapcraft forums or any other of their support channels.

**Comment by tfranken90** [comment]
@Minoru Snaps can run external applications if the snapcraft.yaml has confinement set as classic rather than strict. I've been building my own snaps on debian, and it works without any problems.

It's possible to publish to the snapstore with classic confinement but requires [manual review](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460). Might be worth looking into since newsboat is really more suited for a classic confinement.

**Comment by Minoru** [comment]
@tfranken90, yeah, I should've said "our snap".

I'm doing an abysmal job at updating the snap, pushing out new ones only when I release a new version upstream. Ideally, I should push new ones every time a dependency gets updated in Ubuntu, but strict confinement allows me to avoid this and still think that the users are reasonably safe. With classic confinement, that comfort will be gone.

Snap is certainly a valuable distribution channel for Newsboat, we have about 300 installs currently, but from the developer side it's not too bright: I still don't receive emails about broken builds, and I still don't have a way to trigger rebuild of a particular version (so I can re-release 2.19 when a dep changes). Perhaps the responsible thing to do would be to give the snap back to Snapcrafters, who aren't experts at Newsboat but can at least take the proper care of the snap.

**Comment by iampi31415** [comment]
Using `browser "lynx"` I get lynx not found, does lynx need to be installed as a snap for this to work?

I do have it installed on CLI so it's strange.

**Comment by Minoru** [comment]
@iampi31415, it won't work for Snap. See https://newsboat.org/releases/2.39/docs/faq.html#_with_snap_i_cant_start_browserbookmarking_scriptexecfilterrun_program_from_macro

**Comment by iampi31415** [comment]
@Minoru np, thanks!
