### ISSUE TITLE
UTF-8 characters do not show in feed list

### ISSUE THREAD

**Issue by mrjovanovic** [newsboat/newsboat#606]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.13.0

Steps to reproduce the issue:

1. Add a UTF-8 character as a name for feed in `~/.config/urls`, for example:
```
http://www.sadace.hu/?feed-rss2 "Šađače"
```
2. In feed list, the item is listed as "aae"

**Comment by Minoru** [comment]
I can't check this particular feed because its domain doesn't resolve for me. Can you pick another one, please?

The `"Šađače"` tag doesn't change the title of the feed; it has to start with a tilde to do so. Can you try `"~Šađače"` instead?

**Comment by Minoru** [comment]
@mrjovanovic, ping?

**Comment by mrjovanovic** [comment]
Sorry about not answering sooner! I rarely sign into Github these days. Will make note to stop by more often. And to be clearer in my bug reports.

Anyway - Šađače was just an example that showcased what kind of characters don't show up at all. The feed doesn't actually exist. Basically, if the name of a feed in the config files contains any non-ASCII characters, they are simply not shown in newsboat (while being clearly seen in vim while editing the config, for example). Hope I made it clearer now..

**Comment by Minoru** [comment]
You could enable email notifications [by ticking "Email" checkbox in "Participating" section here](https://github.com/settings/notifications), to avoid constant checking of GitHub.

Regarding the bug, I'd like to point out once more that `"foo"` is just a tag; to be a title, it has to start with a tilde, e.g. `"~foo"`. Tags are displayed if you press `t`. Sorry if I'm explaining what you already know, but I want to be absolutely sure you're looking in the right place.

I don't have any idea what's going on, so please answer the following questions to give me some more facts:
1. Does Newsboat display non-ASCII in other places, e.g. in articles?
2. Can you please show the output of `locale`?
3. What Linux distro are you running? Or if it's a BSD, what kind, and what version?
4. Can you show the full output of `newsboat --version`?

**Comment by mrjovanovic** [comment]
Thank you kindly for this. It helped clear up a few things. I was wrong. UTF-8 do characters show up properly both in tags (after pressing `t`) and in names (when defined as `~foo`). Where they do not show up, however, is in the feed list, in case there is only a tag set, and no name. So perhaps this is a case of RTFM. Yet to answer your questions just in case:

1. Yes.
2. Sure:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
3. Debian 10 (buster)
4. Sure.
```
newsboat 2.13.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat 2.13.0
System: Linux 4.19.0-5-rt-amd64 (x86_64)
Compiler: g++ 8.2.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.61.0)
SQLite: 3.27.2 (compiled with 3.25.1)
libxml2: compiled with 2.9.4
```

**Comment by Minoru** [comment]
Cool! I happen to run Debian Buster as well, although with a non-RT kernel (but the same 4.19.0-5-amd64 version). I highly doubt that the kernel has anything to do with this.

I generated `en_US.UTF-8` locale, installed Newsboat 2.13.0 from the repos, and still can't reproduce this.

To make sure I'm not misunderstanding the setup, here's the steps I followed:
1. `mkdir ~/issue-606` to hold temporary data for this issue;
2. `echo 'https://hubicka.blogspot.com/feeds/posts/default "блог"' > ~/issue-606/urls`. That feed has a nice Unicode-y title of "Honza Hubička's Blog", and its tag is Cyrillic;
3. ran `LANG=en_US.UTF-8 newsboat --config-file=/dev/null --cache-file=$HOME/issue-606/cache.db --url-file=$HOME/issue-606/urls` (using /dev/null for a config to avoid any configuration differences between my setup and yours);
4. hit `r` to fetch the feed;
5. when reload finished, I observed this:
![Screenshot_2019-09-03_21-47-51](https://user-images.githubusercontent.com/118875/64200173-96ae5580-ce94-11e9-9855-d476d8447b4a.png)
6. pressed `t` to view tags, and observed this:
![Screenshot_2019-09-03_21-48-16](https://user-images.githubusercontent.com/118875/64200199-a5950800-ce94-11e9-833d-76fb9f6aaabe.png)

So, as far as I understand, I didn't reproduce the bug. Can you follow these exact steps, and see if the issue is still present?

> Where they do not show up, however, is in the feed list, in case there is only a tag set with UTF-8 characters, and no name. So perhaps this is a case of RTFM.

No, no, I think we're beyond RTFM now—I think the only relevant thing is a paragraph about title tags (`~foo`), which I retold above. This is either a bug, me misunderstanding your setup and experiences, or you misunderstanding Newsboat's behaviour. Whatever it is, please keep supplying me with facts, and I'm sure we'll get to the bottom of this ;)

**Comment by Minoru** [comment]
@mrjovanovic, did you get a chance to try out my suggestion?

**Comment by Minoru** [comment]
@mrjovanovic, ping.

**Comment by Minoru** [comment]
@mrjovanovic, ping.

**Comment by Minoru** [comment]
No response from the reporter for half a year, so closing. Please comment if you run into this, the issue can always be re-opened.

**Comment by nkosi23** [comment]
I am facing the same issue on FreeBSD (version 12.1). I am new to newsboat, this is a fresh install containing one feed only. 

As can be seen in the image below, the "é" accentuated French character is being replaced by 'e. Similarly the ° character is replaced by ^, and in essence it looks like all non-english characters are not being displayed properly:

![image](https://user-images.githubusercontent.com/6731436/103491146-8f4ce280-4e21-11eb-8821-0eac2f2fc6e6.png)

The output of `locale` is:

```
LANG=
LC_CTYPE="C"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
```

The feed being used is `https://www.conseil-constitutionnel.fr/flux/rss.xml`

As an aside, is it possible to change the language of the user interface?

**Comment by Minoru** [comment]
This is the expected behaviour with C locale: it means "default language" with "default encoding", which usually translates into "English" and ASCII. The simplest way to change it is `export LC_ALL=fr_FR.UTF-8`, or running Newsboat with `LC_ALL=fr_FR.UTF-8 newsboat`.
