### ISSUE TITLE
'o' followed rapidly by 'Up' mark all article of current feed read

### ISSUE THREAD

**Issue by ghost** [newsboat/newsboat#63]
Hello,

Newsboat version
```
newsboat 2.10.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT/X Consortium License.
Type `newsboat -vv' for more information.

newsboat 2.10.1
System: Linux 4.12.14-gentoo (x86_64)
Compiler: g++ 5.4.0
ncurses: ncurses 6.0.20150808 (compiled with 6.0)
libcurl: libcurl/7.56.1 OpenSSL/1.0.2m zlib/1.2.11 (compiled with 7.55.1)
SQLite: 3.19.3 (compiled with 3.19.3)
libxml2: compiled with 2.9.4
```
Steps to reproduce the issue:
* Enter a feed article list page, press 'o' to open it in browser then 'Up' (or 'Down' I suppose) to move the article focus rapidly.
* All the articles will be marked as read.

Config file:
```
proxy-type socks4
proxy 127.0.0.1:9050
use-proxy yes

articlelist-format "%f %D %t"
feedlist-format "%n %10u %t"
auto-reload yes
reload-time 15
notify-beep yes

browser "jailed-firefox.sh %u"
```

**Comment by Minoru** [comment]
You'll probably like `open-all-unread-in-browser`.

I'll try to reproduce the bug tomorrow; thank you for the report!

**Comment by Q3CPMA** [comment]
Thanks, but there's usually some noise in my feeds (e.g. phoronix, gentoo packages).

**Comment by Minoru** [comment]
Reproduced with a config consisting of a single line:
```
browser "sh -c 'sleep 0.2'"
```

Debug log shows that ^[[A (the Up key's escape sequence) is processed piece by piece by Newsboat's main loop, whereas it should've been handled by STFL. What I *guess* is happening is [we suspend STFL](https://github.com/newsboat/newsboat/blob/master/src/view.cpp#L366) while browser is running, and afterwards we just process whatever's left on the standard input.

We can probably add a little kludge that'll flush stdin before restoring back to Newsboat, but it'll be inconvenient for some fast-typing people if their workflow relies on this: they won't be able to type 'o', then a command to the browser (knowing that it'll finish right after that), and then a command to Newsboat. The risk is slight and justifiable IMHO. But that's a kludge.

Or we can learn to restore STFL in such a way that it'll process what's on the standard input instead of passing it right down to Newsboat.

**Comment by dennisschagt** [comment]
> Debug log shows that ^[[A (the Up key's escape sequence) is processed piece by piece by Newsboat's main loop, whereas it should've been handled by STFL. What I guess is happening is we suspend STFL while browser is running, and afterwards we just process whatever's left on the standard input.

The problem is indeed caused by suspending STFL ([permalink to a specific commit](https://github.com/newsboat/newsboat/blob/4b850932d242cb7c0126ae679ac858f7fdd88d9c/src/view.cpp#L419)).

From https://invisible-island.net/xterm/xterm.faq.html#xterm_arrows:
> VTxxx (VT100 and up) terminals may send different escape sequences for the cursor (arrow) keys depending on how they are set up. The choices are referred to as the normal and application modes. Initially, the terminal is in normal mode.

When suspending stfl, curses' [endwin()](https://github.com/dennisschagt/stfl/blob/d8ea471d46192fff5e726db2fe4d966b83bd0e0f/base.c#L673) is called which changes from "application" mode to "normal" mode.
In normal mode, the up arrow is transmitted as `^[[A` while in application mode it is transmitted as `^[OA`.

When running stfl/curses again, queued input is processed in the same way as before.
The problem is that curses does not process up arrows in `^[[A` format so it ignores it and emits the separate characters `escape`, `'['`, `'A'` (0x1B 0x5B 0x41).

[Helpful stackexchange answer](https://vi.stackexchange.com/a/15328/1142).
