### ISSUE TITLE
Feeds no longer updating on version 2.17

### ISSUE THREAD

**Issue by Aicaya** [newsboat/newsboat#650]
Updated Newsboat via `make` / `sudo make install` last night, and it never updated any feeds after that (neither automatically nor manually). New feeds are detected just fine, though, and no error messages show on the log file (error-log is set), so I can't tell why it's happening. Reverting back to 2.16.1 fixes it.

`newsboat -v` output:
```
newsboat 2.17.0
System: Linux 5.3.1-arch1-1-ARCH (x86_64)
Compiler: g++ 9.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2 (compiled with 7.66.0)
SQLite: 3.29.0 (compiled with 3.29.0)
libxml2: compiled with 2.9.9
```

Steps to reproduce:

1. Subscribe to a feed with a reliable schedule (podcasts and webcomics are good for this)
2. Wait until the feed is supposed to update (might take a few days, depending on their schedule)

Distro is Arch Linux, if it helps. Can't install the version on the repo because the package there is seemingly abandoned at this point.

**Comment by Minoru** [comment]
Hmm, works fine here on Debian. Can you please do the following:
1. add https://hnrss.org/frontpage (Hacker News, high-traffic tech "news" site) to your urls file;
2. start Newsboat, update that feed, quit Newsboat;
3. wait about half an hour, to make sure there is a new post in the feed;
4. run `newsboat --log-file=newsboat.log --log-level=6`;
5. update that particular feed;
6. quit Newsboat.

Then attach "newsboat.log" to a new comment here. Note that the file will contain some potentially private info:
1. your config;
2. dumps of all the screens you show.

If that's not okay, use a different (one-line?) urls file and a minimal config (see `--url-file` and `--config-file` options).

**Comment by Aicaya** [comment]
Did as requested. Here's the file: [newsboat.log](https://github.com/newsboat/newsboat/files/3644157/newsboat.log)

Just to confirm, the Hacker News feed didn't update on Newsboat despite the contents being different when I checked the link again.

**Comment by polyzen** [comment]
Feeds are updating for me. Just bumped the Arch repo package to 2.17.

**Comment by Aicaya** [comment]
Installed the Arch version (thanks for updating, polyzen). Gonna have to wait a day to see if feeds update since the next reliable feed won't update until tonight (I should note that the Hacker News feed from above hasn't updated on my side ever since installing the Arch version), but regardless of whether or not they do this still leaves some important questions.

If the feeds don't update with the Arch version: Why don't they update on my side? Is there a new dependency I'm not aware of? Installing it from the repo didn't bring anything new with it, and version 2.16.1 still works.

If the feeds *do* update, however: Why don't they update for me when installed with `sudo make install` but they do with version 2.16.1 (compiled/installed in the same manner)? The only possible differences on my side would be the prefix (/usr/local/, which shouldn't be an issue since everything I install manually goes there) and the cpu (unless polyzen also uses a first-gen ryzen).

**Comment by polyzen** [comment]
Intel(R) Core(TM) i5-3570K CPU

**Comment by Minoru** [comment]
Thanks for the logs, @Aicaya! I think what's happening is Newsboat trims the feed because of `max-items` setting; but it does it from the wrong end, removing the *newest* items rather than oldest.

I was able to reproduce this with Hacker News feed (which contains 20 items) and a simple config:
```
max-items 10
```

Now I need to figure out how to reproduce this reliably, so I can find the cause and fix it. Can't wait 20 minutes between tests, in hopes HN posts something new.

This is a critical bug, so adding it to the "bugfix release" milestone.

**Comment by Minoru** [comment]
Yup, reproduced it all right, and found the offending commit:

```
a80241ced3be843f04c0da2f2a4177eb76b3961c is the first bad commit
commit a80241ced3be843f04c0da2f2a4177eb76b3961c
Author: Alexander Batischev <eual.jp@gmail.com>
Date:   Fri Jul 19 21:54:01 2019 +0300

    Do not sort items in internalize_rssfeed

    We sort them later anyway.

 src/cache.cpp | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)
```

Reverting it fixes the problem. I'm going AFK now; I'll think tomorrow if reverting is the only option, or if we can still salvage something.

@Aicaya, temporary work-around is to comment out `max-items` in your config, or roll back to an earlier release.

**Comment by Aicaya** [comment]
Noted! I'll just comment it for now.

**Comment by Minoru** [comment]
I ended up reverting the commit entirely. Below is my reasoning, mostly for future me who gets puzzled over "why did I revert this instead of doing X?"

We're sorting the feed reverse-chronologically because we want to trim oldest items if `max-items` is set. Ties are broken by item IDs; the larger the ID, the newer the item. This is sufficient to establish ordering even if there are a lot of items published in the same second.

But not everybody is using `max-items`, and I hoped I'd be able to do the sorting on the application side and only when the user really needs it. However, this is impossible, because we don't read item ID into `RssItem`; thus, we can't break ties when we sort `RssFeed`.

I guess we could append that `ORDER BY` clause only when `max-items` is set, but that doesn't sit well with me; manipulating SQL queries as string won't end well, and we're already doing it. Probably not worth the 6%, or however much that particular change saved.

So I took the easy way out, and reverted the whole patch.
