### ISSUE TITLE
Regression: # inside string in config broken

### ISSUE THREAD

**Issue by The-Compiler** [newsboat/newsboat#652]
After upgrading from newsboat 2.15 to 2.17, it dislikes this line in my config:

```
highlight article "[-=+#_*~]{3,}.*" green default
```

as it apparently parses everything after `#` as a comment, even though it's inside a string:

```
Loading configuration...Error while processing command `highlight article "[-=+#_*~]{3,}.*" green default' (/home/florian/.config/newsboat/config line 31): too few parameters.
```

**Comment by Minoru** [comment]
I suspect this is caused by #584. I'll fix this and release 2.17.1, probably this weekend. Thank you for the report!

**Comment by brianbuccola** [comment]
FWIW, I'm getting the same error with this line:

```
highlight all "(https?|ftp)://[\-\.,/%~_:?&=\#a-zA-Z0-9]+" blue default bold
```

Note that `#` is escaped here, yet the error still occurs.

Assuming the issue gets fixed, should `#` be escaped, or not? In @The-Compiler's code, it's not escaped.

(I've had this line since back in the newsbeuter days. I can't remember if I wrote it myself or borrowed it from somewhere. Maybe I'll just change it to `"(https|ftp)://[^ ]+"` like in the docs example.)

**Comment by Minoru** [comment]
@brianbuccola if I'm reading [the POSIX regex spec](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04) correctly, `#` shouldn't be escaped, because:
1. it's not a special character;
2. backslash [loses its special meaning within square brackets](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_05), so your regex above will actually match on strings like `https://\`—which you most likely didn't indend it to do.

Since this is just a highlighting rule, I'd go with a simpler regex from our doc. It's not the end of the world if it highlights something that isn't really a URL.
