### ISSUE TITLE
Add a way to read URLs list from a program rather than a file

### ISSUE THREAD

**Issue by DmitryMake** [newsboat/newsboat#690]
Hello! I use newsboat for getting rss feed from my gitlab account history via token. And I also like to keep my dot files in git. Can you add a feature which allows to include data from encrypted files, something like `urls-source` via gpg2?
Thanks for newsboat!

**Comment by polyzen** [comment]
Alternatively you could use a dotfiles manager that supports encrypted data.

**Comment by Minoru** [comment]
It's also not clear how this should work with `edit-urls` command. Newsboat has to have a way to both read and *write* the urls file.

Since the intent here is to encrypt the urls file while it's "in rest" inside the Git repo, I think @polyzen's suggestion is the best approach, so I'm closing the issue.
