### ISSUE TITLE
Mark read before quit

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#698]
There is an option: `delete-read-articles-on-quit`. Is it possible to add another option to mark all unread as read on quit?

**Comment by Minoru** [comment]
Hi! I think such an option would be redundant, because the same result can be achieved by invoking `mark-all-feeds-read` (default key: `C`) before quitting. That's three keystrokes (`Shift`+`c`, `q`), but with [macros](https://newsboat.org/releases/2.17.1/docs/newsboat.html#_macro_support) you can lower that to two (`,q`):

```
macro q mark-all-feeds-read; quit
```

(untested)

Would that work for you, @anishmittal2020?

**Comment by anishmittal2020** [comment]
Thanks Minoru. It will be redundant in the sense that the suggested method achieves the same goal, the only difference is that if we could set this in our configuration, then this step would happen automatically and we don't have to execute it manually. 

This use case can be useful for a particular types of feeds such as the one that contains latest news.

**Comment by Minoru** [comment]
Can you please try my suggestion? It *does* mark articles as read, automatically. You just have to press `,q` instead of the ordinary `q`. You can even un-bind the latter to force yourself out of the old habit. (You can't bind a macro to a single key, though; I do plan to rework keybinds someday, and remove this limitation).

> This use case can be useful for a particular types of feeds such as the one that contains latest news.

Yeah, I figured that's the use-case, but then you should realize that `delete-read-articles-on-quit` option affects *all* the feeds. Same for `mark-all-feeds-read` operation. So this option is markedly different from what the option you want.

If you need this only for certain feeds, the only way right now is to invoke `mark-feed-read` (default key: `A`) before quitting the feed with `q`. This can be turned into a macro as well.

I really don't want to turn this into a config option, because this stuff ought to be possible with keybinds. Unfortunately it *isn't* at the moment, but eventually it will be.

**Comment by anishmittal2020** [comment]
Thanks for the suggestion. Should I close this issue?

**Comment by Minoru** [comment]
Yeah, I guess it can be closed now.

**Comment by anishmittal2020** [comment]
@Minoru I get this error, based on your suggestion

```
Starting newsboat 2.17.1...
Loading configuration...Error while processing command `macro q mark-all-feeds-read; quit' (/home/nikhil/.newsboat/Config/Config-ShortCache.txt line 15): `mark-all-feeds-read;' is not a valid key command
```

**Comment by Minoru** [comment]
@anishmittal2020, if you haven't resolved this yourself yet: there should be a space before the semicolon. I told you it was untested :) Edited my earlier comment as well, in case someone else reads it.
