### ISSUE TITLE
Add support for Feedbin

### ISSUE THREAD

**Issue by nielsk** [newsboat/newsboat#716]
It would be great if there would be [Feedbin](https://feedbin.com/)-support. 
Their API-documentation can be found on github: https://github.com/feedbin/feedbin-api

**Comment by glottisfaun0000** [comment]
any update on this?

**Comment by jamesbvaughan** [comment]
I'm interested in working on this. I haven't contributed to newsboat before though, so I may be slow.

**Comment by Minoru** [comment]
Cool! Take your time. Start with reading include/remoteapi.h — that's what you need to implement in order to add support. It looks like Feedbin API is a custom one and relies on JSON, so you can take inspiration from other JSON-based API implementations:

- freshrssapi
- minifluxapi
- ttrssapi

You can also look at commits that introduced those APIs to see how to plug yours into the system.

It'd be especially nice if you could create something like contrib/miniflux/docker-compose.yml to help with testing this.

Please ask questions if you get stuck on something! As you can see, the main blocker here was lack of people willing to do the work, but now that you're here, I'd do everything I can to help you succeed.

Incidentally, do you use Feedbin yourself? Can I expect that you'd be around to fix bugs with this API when they pop up? This is *not* a hard prerequisite for merging, but it'd be nice if you could help support the feature once it's in.

**Comment by jamesbvaughan** [comment]
Thanks for the support!

I spent some time on this last night and just put up a draft PR: https://github.com/newsboat/newsboat/pull/2650

There's a bit more work to do before it'll really be ready for review.

> It'd be especially nice if you could create something like contrib/miniflux/docker-compose.yml to help with testing this.

Oh that is nice. I looked into this for Feedbin and it doesn't seem like it would be as straightforward unfortunately. While Feedbin is technically open source, it doesn't seem like they have prioritized making it self-hostable. The Feedbin readme links to this repo for an example of running Feedbin via docker-compose: https://github.com/angristan/feedbin-docker

But that repo and compose file are quite a bit more complicated than the miniflux `docker-compose.yml`.

> Incidentally, do you use Feedbin yourself? Can I expect that you'd be around to fix bugs with this API when they pop up? This is not a hard prerequisite for merging, but it'd be nice if you could help support the feature once it's in.

I do! But only very recently. I actually used newsboat with a local URL list as my primary reader years ago, and then switched to just using Feedly for a few years. I finally got fed up with Feedly for a bunch of reasons and saw some folks I trust recommending Feedbin, so I switched over to it. I've been happy with it so far and expect to stick with it.
