### ISSUE TITLE
Podboat shows speed as 0.0kb/s if actual speed is higer than 10MB/s

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#727]
**Newsboat version**: 2.18.0

Caused by [check in poddlthread.cpp](https://github.com/newsboat/newsboat/blob/f80387f9c4a496258d6839bc472c8a0dc6b9e58f/src/poddlthread.cpp#L182-L183).

Steps to reproduce the issue:

1. Add a download to the podboat download queue

2. Start the download

3. Observe that a speed of 0.0kb/s is shown if the actual download speed rises above 10MB/s

**Other info you think is relevant**:
I expect the check was added to make sure that the speed fits in the download speed field.
The following image shows that the speed would not fit if another digit would be added:
![image](https://user-images.githubusercontent.com/4629607/72987613-0e9cfe00-3deb-11ea-9678-1776ac9fa60d.png)

**Comment by dennisschagt** [comment]
Possible solutions:
- Show speed in mb/s (always or only when above a specific threshold)
- Remove one digit behind the decimal point
- Widen the field by a digit

I prefer the first option but anything else seems fine with me as well.
@Minoru Do you have a preference (or even another solution)?

**Comment by Minoru** [comment]
Thanks for the report!

I believe that:
* possible speeds range from a few KB/s (e.g. old ADSL, bad 3G, really crappy Wi-Fi) to a few GB/s (fiber to the home, eventually 5G); and
* people generally have a hard time making sense of large numbers like "123456.78 KB/s" instead of "120.56 MB/s".

So I agree that the first option is the best. I think it should have a "ladder" like this:
1. speeds less than 1 MB/s are displayed in kilobytes per second;
2. speeds less than 1 GB/s are displayed in megabytes per second;
3. everything else is displayed in gigabytes per second.

This might also be a good opportunity to fix the names: "kb" is nonsense, kilobytes are written as "KB".
