### ISSUE TITLE
Articles don't get loaded if there is already one with the same title

### ISSUE THREAD

**Issue by Brn9hrd7** [newsboat/newsboat#740]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.18.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

newsboat ist Freie Software und steht unter der MIT-Lizenz. („newsboat -vv“ zeigt den vollständigen Lizenztext an.)
Es wird die unter der MIT-Lizenz stehende Bibliothek JSON für Modernes C++ verwendet: https://github.com/nlohmann/json

newsboat 2.18.0
System: Linux 5.4.17-30-tkg-pds (x86_64)
Compiler: g++ 9.2.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.67.0)
SQLite: 3.31.1 (compiled with 3.30.1)
libxml2: compiled with 2.9.10
```

I just noticed that one Article(probably more than one in the last couple of days) today didn't get loaded because there was already an Article with the exact same title(within the same feed, but with a different timestamp). I assume that newsboat only checks if there is an Article with the same title & same feed url in the database, but without checking if the timestamp is the same.

**Comment by Minoru** [comment]
Hi!

> I assume that newsboat only checks if there is an Article with the same title

Normally it doesn't, because standards require each item to have a unique identifier. However, some feeds break the standard, so Newsboat [tries to generate the ID from whatever is available, including the title](https://github.com/newsboat/newsboat/blob/6bdf75ddbf5f833c03efc67db9997584d3785d92/src/rssparser.cpp#L539). If you can show the URL of the feed in question, I can take a look to see if there's IDs in there.

**Comment by Brn9hrd7** [comment]
It happened with this URL: [https://www.mindfactory.de/xml/rss/mindstar_artikel.xml](https://www.mindfactory.de/xml/rss/mindstar_artikel.xml)
Basically it's a feed with special deals from an online shop. It looks like there is a guid set, but it's just the link to the product, so if the same product is on sale in the future, it won't add a new "Article" because the guid is the same...

**Comment by Minoru** [comment]
Yup, looks like you're right. The feed is conformant to the spec, but is practically broken.

Id' email the site owner and explain the situation, if that's possible. They might not care, though, and might decide to take the feed down instead of fixing it.

What *you* can do is: write a script that reads RSS on standard input, adjusts the `<guid>` field (e.g. adding a date in there, and setting `isPermalink` to `false`), then prints out the modified RSS onto standard output. Then use it with `filter:` in the urls file.

**Comment by Brn9hrd7** [comment]
Thanks for the suggestion! I'll try writing the script to do that.
