### ISSUE TITLE
pipe-to command should not word wrap

### ISSUE THREAD

**Issue by diamond-lizard** [newsboat/newsboat#833]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.13.0 - https://newsboat.org/

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
macro x pipe-to "$HOME/bin/newsboat-url-to-xclip-in"
```

Steps to reproduce the issue:

1. Open an article with

2. Type the keystroke to filter the article through the pipe-to command

3. newsboat will word wrap metadata like the "Title:" line (for example, long titles will be wrapped on to the following line)

**Other info you think is relevant**:

None of pipe-to's output should be word wrapped, as this makes pipe-to's output unnecessarily difficult to process with an external script.

pipe-to should just leave everything in the original article as is.

**Comment by Minoru** [comment]
Yep, makes sense, but I have to wonder why this gets asked [11 years after `pipe-to` was introduced](https://github.com/newsboat/newsboat/commit/3eedc78d0b2a66d8102316c6ae37834a739f0637). Either there is a use-case that I fail to see, or no-one is actually using this.

If latter is true, I'm fine with breaking compatibility, but if former, I'd rather introduce a new operation or an option for the existing one. It's not clear to me how to proceed here.

**Comment by herrsimon** [comment]
As a new user of newsboat I perceived the wrapping as problematic rather quickly: I'm monitoring new research articles via feeds and would like to use pipe-to in order to parse a relevant feed item (i.e. article) and then add it to a read later list. Therefore, like diamond-lizard writes, parsing would be much easier if no wrapping would occur. 
Header lines (Title, Author etc.) can of course be unwrapped again straightforwardly inside the script, but what's really annoying is that there is no way to properly unwrap the summary or content field again as one can not differentiate between a linebreak introduced by wrapping and one which was there before.

I think it would be very useful to introduce a configuration option to set the maximum textwidth and also disable wrapping entirely.

**Comment by jacanchaplais** [comment]
I'd like to weight in saying that I'm also a new user with the same use case, and this has equally been an issue for me.

**Comment by Minoru** [comment]
So I looked at the code, and it turns out `pipe-to` wraps text at 80 characters *unless* `text-width` is set to a non-zero value, in which case that value dictates the wrap limit. So you can effectively disable the wrapping by setting a very high limit:

```
macro x set text-width 100500 ; pipe-to less ; set text-width 0
```

Instead of introducing a new setting, I'd recommend using this pattern. Also, in the next major version I'll make it so `text-width` applies to everything consistently.
