### ISSUE TITLE
'2528809:2528809:0324/184939.865127:ERROR:broker_posix.cc(43)] Invalid node channel message' when using Chromium

### ISSUE THREAD

**Issue by mipesom** [newsboat/newsboat#835]
**Since I switched from Firefox (cause of up to 20 sec freezes) to Chromium, opening an article with key 'o' opens the article, but then newsboat writes "_2528809:2528809:0324/184939.865127:ERROR:broker_posix.cc(43)] Invalid node channel message_" in between the entries.**

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.18.0
System: Linux 5.4.24-1-MANJARO (x86_64)
Compiler: g++ 9.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.1)
libcurl: libcurl/7.69.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.67.0)
SQLite: 3.31.1 (compiled with 3.30.1)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload  	        yes
reload-time		180
notify-program 	        notify-send
notify-always	        false
browser 		chromium
```

Steps to reproduce the issue:

1. Type 'o' on any feed entry with chromium as browser

2.

3.

**Other info you think is relevant**:
YouTube feeds seem NOT to be affected by this? 🤔

**Comment by dennisschagt** [comment]
> opening an article with key 'o' opens the article, but then newsboat writes …

That error is not written by Newsboat.
It is probably written by Chromium (I've seen similar errors before when starting Chromium on its own).

It might be useful for Newsboat to always refresh the screen after the browser process has ended.
I'm not sure if the current behaviour is somehow the expected behaviour (I can understand that seeing output from STDERR adds some value but it currently does break Newsboat's rendering).

Either way, you can work around it with either of the following options:
- Press `CTRL+L` [to redraw the screen](https://newsboat.org/releases/2.19/docs/newsboat.html#redraw) (temporary solution, just to make sure that the above explanation is correct)
- Update the Newsboat `browser` setting to redirect output from Chromium to `/dev/null`, e.g.:
  `browser "/usr/bin/env bash -c 'nohup chromium %u &>/dev/null & disown -a'"`
  Explained at https://github.com/newsboat/newsboat/blob/1702561e32733b3aea2e1488c7d100a055e9979c/doc/faq.asciidoc#user-content-browser-script (will probably be updated by @Minoru, see #825)

**Comment by mipesom** [comment]
A system update with following restart seems to have fixed it.

**Comment by mipesom** [comment]
The error just came back and nothing worked except using the workaround `browser "/usr/bin/env bash -c 'nohup chromium %u &>/dev/null & disown -a'"`
