### ISSUE TITLE
Read full article

### ISSUE THREAD

**Issue by caywin25** [newsboat/newsboat#860]
Hello,

I don't know if the question has been asked before or not. I know I can read the article by opening the RSS feed in the browser.
But would it be possible to implement the reading of the complete article in newsboat directly?

Thank you

**Comment by Minoru** [comment]
Hi! For some feeds, it's possible if you set [`download-full-page`](https://newsboat.org/releases/2.19/docs/newsboat.html#download-full-page). This doesn't always work, though, since the article might be formatted in a way that's too complex for Newsboat to handle, or it might require JS to render.

Does that answer your question?

**Comment by Minoru** [comment]
Cool! I'll close the issue, then.
