### ISSUE TITLE
Rust no longer supports "-Zno-landing-pads" (used in Test Coverage build)

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#916]
The `-Zno-landing-pads` flag is longer supported: https://github.com/rust-lang/rust/commit/bf459752d41a93eb6df0e9513de4ef807883a80c.

I've tried specifying `-Cpanic=abort` but that failed [with error](https://travis-ci.com/github/newsboat/newsboat/jobs/326216626#L953-L957):
```
error: building tests with panic=abort is not supported without `-Zpanic_abort_tests`
```

Additionally adding `-Zpanic_abort_tests` still failed but [at a later point](https://travis-ci.com/github/newsboat/newsboat/jobs/326220787#L1478-L1496):
```
error: the crate `libnewsboat` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`
```

I don't really know why we specify `-Zno-landing-pads` in our Test Coverage job so I have no idea if we can just drop it.

**Comment by Minoru** [comment]
> I don't really know why we specify -Zno-landing-pads in our Test Coverage job

To tell the truth, neither am I. I simply copied all those flags from the README for grcov, the tool we're using to gather coverage information.

The issue was already reported to grcov (https://github.com/mozilla/grcov/issues/427), so let's just wait for them to update their README. In the meantime, I'll change the CI job to use an older Nightly that works.
