### ISSUE TITLE
How to view all articles from multiple feeds

### ISSUE THREAD

**Issue by madacol** [newsboat/newsboat#918]
I'd like to list in chronological order all articles from all the feeds that appears in a query feed.

So basically in the **query feed** view instead of listing feeds, can it list the articles of those feeds in chronological order?

Is this possible?

**Comment by Minoru** [comment]
Hi! I'm a bit confused because the title and the body of the issue seem to ask two different questions. I'll try to answer both.

> How to view all articles from multiple feeds

Write a [filter](https://newsboat.org/releases/2.19/docs/newsboat.html#_filter_language) that selects all of those feeds, and use it for the query.

> n the query feed view instead of listing feeds, can it list the articles of those feeds in chronological order?

Query feeds list articles just like any other feed does. Perhaps you were thrown off by the fact that query feeds also mention the title of the article's original feed?

With that said, changing the order in a query feed works the same as in any other feed: you press `g` or `G` (or whatever you bound `sort` and `rev-sort` to), and pick the order. For chronological order, pick `(d)ate`.

Does that answer your question(s)?

**Comment by madacol** [comment]
Sorry, I'm probably confused with the terminology.

To be more precise about my use case, I have all my YouTube channels' feed under a common tag called **videos**

When I select that tag (pressing **t**, and selecting the tag **videos**) each channel appear as a single entry, so I have to enter a channel in order to open its videos.
What I would like instead, is that all the videos (from all the channels) appear directly when entering to the tag **videos**.

**Comment by madacol** [comment]
Ok I just learned that a **query feeds** does what I need!

It involves modifying the `urls` file to add an entry for the `video` tag like this:  `"query:Videos Articles:tags # \"videos\""`

---

Now I would like to suggest a keyboard binding that aggregates all feeds in the current **feed list**. Maybe like some kind of **view mode**:

- list feeds - (how it currently works)
- list articles aggregated from current filtered feeds, just like a **query feed** applied to the current filter (if any)

**Comment by Minoru** [comment]
Glad you've found the solution!

I'm not too keen on displaying articles in the feed list, because It makes everything else very confusing. Couple examples offhand:
1. filters now have to execute in the "article" context, even though the user is technically looking at the feedlist;
2. it's unclear what `show-read-feeds` setting should do while in this "article view" mode;
3. it's unclear what keybinds Newsboat should use in this mode. Feedlist keybinds probably don't make sense, but not all of articlelist's do as well. For example, what should `next-feed` and `prev-feed` do?

Newsboat enforces a pretty clear progression through the dialogs: first feedlist, then articlelist, then articleview. Users that want a "river of news" can utilize query feeds, or press `n` in the article view, but that's about it. I understand that this might not be enough for some users, but supporting every possible use-case in Newsboat will just make it over-complicated for everybody.

Thus, no, I don't want this feature in Newsboat.

If you'd like to help out with development, take a look at "good first issue" label, though I'd appreciate help with any of the other ones as well. I'm happy to answer questions and mentor.

**Comment by madacol** [comment]
What about a **command** to generate a **Quey Feed** on-the-fly with current feed list.
Does that make sense?

**Comment by Minoru** [comment]
Can you please file a separate issue about that, and describe it in terms of a use-case rather than "here's a feature to implement"? Like, how would you use this, what would the steps be, what problem does it solve, how it compares to the stuff Newsboat already has?
