### ISSUE TITLE
build fails on ubuntu 20.04

### ISSUE THREAD

**Issue by muralikodali** [newsboat/newsboat#933]
build fails on ubuntu 20.04 with following errors: 

```
/bin/ld: ./libboat.a(utils.o): in function `newsboat::utils::translit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/murali/Downloads/newsboat-r2.19/src/utils.cpp:312: undefined reference to `libiconv_open'
/bin/ld: /home/murali/Downloads/newsboat-r2.19/src/utils.cpp:343: undefined reference to `libiconv_close'
/bin/ld: /home/murali/Downloads/newsboat-r2.19/src/utils.cpp:317: undefined reference to `libiconv_open'
/bin/ld: ./libboat.a(utils.o): in function `newsboat::utils::convert_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/murali/Downloads/newsboat-r2.19/src/utils.cpp:360: undefined reference to `libiconv_open'
/bin/ld: /home/murali/Downloads/newsboat-r2.19/src/utils.cpp:391: undefined reference to `libiconv'
/bin/ld: /home/murali/Downloads/newsboat-r2.19/src/utils.cpp:419: undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
make: *** [Makefile:111: newsboat] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Minoru** [comment]
Thanks for the report! This is interesting. We didn't test 2.19 with Ubuntu 20.04 (because Ubuntu haven't been released at that point), but [we do that for master branch now, and everything compiles fine](https://cirrus-ci.com/task/5498975044239360). @muralikodali, please post:
1. the whole output of `make all`;
2. output of `uname -a`;
3. output of `g++ --version` and `clang++ version` (one of them might fail, it's fine).

**Comment by muralikodali** [comment]
i have attached the following logs : 
(excluding rust compile output that escaped redirection)

[clang++.log](https://github.com/newsboat/newsboat/files/4616819/clang%2B%2B.log)
[g++.log](https://github.com/newsboat/newsboat/files/4616820/g%2B%2B.log)
[make.log](https://github.com/newsboat/newsboat/files/4616821/make.log)
[make_endoutput.log](https://github.com/newsboat/newsboat/files/4616822/make_endoutput.log)
[uname.log](https://github.com/newsboat/newsboat/files/4616823/uname.log)

**Comment by Minoru** [comment]
Thanks! Only two things stand out to me:
1. linking is done with `-Wl,-Bsymbolic-functions`;
2. some of the libraries appear to be installed to /usr/local/stow.

If I do `LDFLAGS=-Wl,-Bsymbolic-functions make all` in our Ubuntu 20.04 Docker image, it builds fine, so that's probably not it.

I'm not familiar with [GNU Stow](https://www.gnu.org/software/stow/), but its idea seem to be similar to Nix and GNU Guix: install each package into its own "root", and create virtual environment by symlinking the necessary packages into the virtual root. I guess this *could* interfere with linking, but e.g. NixOS didn't have problems packaging Newsboat 2.19. @muralikodali, can you provide a step-by-step build of how to set up Stow and compile Newsboat with it? I'll try to do the same in our Docker container to see if I can reproduce the issue.

**Comment by muralikodali** [comment]
I have installed newsboat v2.19 with nix package manager on my system without any error. My problem is compiling it on ubuntu 20.04.

GNU stow is the program that provide symlinks to all folders and files at their appropriate places i.e; contents of package lib folder lib directory (/usr/local/lib), executables in bin directory to /usr/local/bin and share folder leading symlinks to /usr/local/share/applications and man folder /usr/local/man folder.

It  is bit easier to manage things with GNU stow as we can replicate the same thing on mulitple machines easily . I back up my stow folder regularly. whenever there is some problem to system, i  will copy back stow folder and use my favourite programs installed ( most of them compiled from source). This is how stow helps me in managing packages.

I have successfully installed newsboat's previous version in ubuntu 18.04 in stow folder. After upgrade to ubuntu 20.04 , compilation of newsboat is giving error.

**Installation steps**: 

./config.sh
make prefix=/usr/local/stow/newsboat

if the make step succeeds, then we go for sudo make install

**Comment by Minoru** [comment]
> I have successfully installed newsboat's previous version in ubuntu 18.04 in stow folder.

That's reassuring, and might help me debug this.

> Installation steps:

…don't include steps to install and configure Stow. I hope you understand that in order to fix this, I need to reproduce the problem. We know that Newsboat *does* compile in a minimal Ubuntu 20.04 install (our Docker container), and *doesn't* compile in your setup. Thus, the next step is to figure out how those setups are different. It's not that I'm against Stow, or Nix, or Guix, or any other thing I'm not currently running; I am just looking for things that are different from the setup I know works. I sure can read Stow's documentation and set it up myself, but that might still not match your setup close enough.

Please provide the steps. Help me help you.

**Comment by muralikodali** [comment]
download gnu stow from the below link : 
[https://ftp.gnu.org/gnu/stow/stow-latest.tar.gz](stow)
extract and cd in to stow folder.
./configure 
make 
sudo make install
the above command installs stow to /usr/local/bin and creates stow directory in /usr/local.

while compiling other programs, we have to  build with configure prefix=/usr/local/stow/newsboat
our program will be installed in stow directory.
next go to stow directory, i.e; /usr/local/stow and stow the directory with following command.
stow newboat ; creates symlinks and bin file appears in our path
to unstow (delink), stow -D newsboat

**Comment by Minoru** [comment]
What about Newsboat's dependencies?

**Comment by muralikodali** [comment]
following packages are installed from ubuntu repos : 
gcc
sqlite3
libcurl
pkg-config
libxml2
asciidocotor

following packages are installed from the links provided in newboat github page  : 
stfl - Version 0.24
json-c - Version 3.0.1

**Comment by Minoru** [comment]
There are multiple curl libraries in Ubuntu; which one did you install?

> json-c - Version 3.0.1

You probably mis-copied the version string, because [I can't find that release](https://github.com/json-c/json-c/releases).

**Comment by muralikodali** [comment]
libcurl4 (openssl flavour)
json-c-0.13.1-20180305

**Comment by Minoru** [comment]
Okay, got it! What about Rust? How do you install it, what version?

**Comment by Minoru** [comment]
Also:
1. have you installed libiconv? (You shouldn't, but if you did, I'd expect it to interfere)
2. have you done anything to libc: installed it from some place other than Ubuntu repo, compiled your own, replaced glibc with musl or anything else?

**Comment by muralikodali** [comment]
rust is not is not installed from system packages. installed in a separate directory outside and sourced in to shell environment.
cargo 1.42.0
iconv (GNU libiconv 1.16) - compiled on my own
gcc installed from os packages

**Comment by muralikodali** [comment]
issue is solved. 
As suggested by you, problem is from GNU libiconv. i have unstowed GNU libiconv and built newsboat with system package.
Thank you very much for the troubleshooting.

**Comment by Minoru** [comment]
Oh, okay. Should've asked this earlier, but I didn't expect anyone on Linux to install it. Glad the issue is resolved! (Re-tagging as "invalid" since the problem wasn't with Newsboat itself.)

Just for my edification, can you tell me why you had it installed? Does some software require it specifically, and can't work with iconv implementation from libc?

**Comment by muralikodali** [comment]
i have installed it on ubuntu 18.04 for some shell scripts in data conversion. At that time system package is lagging behind GNU version. I continued that package in recent upgrade also.

**Comment by Minoru** [comment]
Got it. Thanks!
