### ISSUE TITLE
When downloading a podcast from TT-RSS, newsboat takes the first enclosure rather than the podcast

### ISSUE THREAD

**Issue by nihilazo** [newsboat/newsboat#941]
**Newsboat version**: newsboat 2.19.0

When enqueueing a podcast from a tinytinyrss server that contains multiple media enclosures (such as a podcast logo), newsboat will enqueue and download the first media enclosure in the feed, instead of the podcast.

**Comment by Minoru** [comment]
Thank you for the report! I did not reproduce this, but looking at [the code](https://github.com/newsboat/newsboat/blob/09cbfa67c11a7da2ff97a3532de13637e2440e36/src/ttrssapi.cpp#L417-L430), it's easy to see that you're right.

I believe this is a good first issue for a Newsboat contributor:
1. the above link shows which part needs modification;
2. our "native" RSS and Atom parsers don't exhibit this bug because they choose the last enclosure that looks like a podcast. You can look at rss/atomparser.cpp for inspiration. Just port the code from there to TtrssApi;
3. test that it actually works (@nihilazo, could you provide a URL of the feed where the first enclosure is an image, and the second is a podcast?).

**Comment by arjbholu** [comment]
Hi,

Can I take up this issue?

**Comment by nihilazo** [comment]
an example would be the feed for the no such thing as a fish podcast: https://audioboom.com/channels/2399216.rss

**Comment by chux0519** [comment]
I think i've fixed this issue.

![newsboat-ttrss-after](https://user-images.githubusercontent.com/14276970/85943745-8e179600-b964-11ea-8dfe-2a004cf6236a.png)
