### ISSUE TITLE
Add a way to migrate feeds from one db to other db

### ISSUE THREAD

**Issue by klartext** [newsboat/newsboat#985]
I'm looking for an option, that allows migrating feeds from one urlfile/databasefile to a different urlfile/databasefile.

Option should move all data of a feed from one database to another database.

Without such an Option:
Changing the urlfiles is easy, but the old data of the moved feed is in the old db-file. So changing the database-file means split of data. When "cleanup-on-quit" is set in the old database, then removing the url there even yields to loss od the data.
So the feed must then be hold in parallel in the old and the new database, which contradicts the migration.

With such an option:
Migrating the data to the new database copies all feed data from old db to new db, before removing it from the old db.
But it also must be guaranteed, that the url is moved from the old urlfile to the new urlfile, because if thats not done and "cleanup-on-quit" is active, then the new database removes that data on the next quit.

**Comment by Minoru** [comment]
Isn't `cleanup-on-quit` the option you're looking for? Suppose you want to split a feed with URL https://example.com/news.atom to a separate urlfile/databasefile pair:

1. Copy your existing database file to a new location.
2. Create a new url file and put "https://example.com/news.atom" into it.
3. `cleanup-on-quit` is enabled by default, so no need to create a new config -- an empty one will do.
4. Run newsboat on your new database, url file, and empty config: `newsboat --config-file=/dev/null --cache-file=path/to/new/database --url-file=path/to/new/urls`.
5. Quit Newsboat and wait for it to remove all the feeds except https://example.com/news.atom.

Does that suit your use-case, @klartext?

(Tagging as question for now because this doesn't seem to require any new features.)

**Comment by klartext** [comment]
> Isn't `cleanup-on-quit` the option you're looking for? Suppose you want to split a feed with URL https://example.com/news.atom to a separate urlfile/databasefile pair:
> 
>     1. Copy your existing database file to a new location.
> 
>     2. Create a new url file and put "https://example.com/news.atom" into it.
> 
>     3. `cleanup-on-quit` is enabled by default, so no need to create a new config -- an empty one will do.
> 
>     4. Run newsboat on your new database, url file, and empty config: `newsboat --config-file=/dev/null --cache-file=path/to/new/database --url-file=path/to/new/urls`.
> 
>     5. Quit Newsboat and wait for it to remove all the feeds except https://example.com/news.atom.
> 
> 
> Does that suit your use-case, @klartext?
> 
> (Tagging as question for now because this doesn't seem to require any new features.)

Thanks for the idea. This could work only under ceratin circumstances:
enough free space on the disk to copy the database. (Would work here).

But it would not work, if I decide to move some feeds later from db A to db B. And that's the case here. The former main db just had so many entries, that I forgot some to move. Now, how to just move one certain feed from the old db A to already existing and used db B (with different set of feeds), without loss of the already gathered data?
In this situation we are right back to this the issue.

**Comment by klartext** [comment]
What about a one-database-file-per-feed, at least as possible option?
This would likely speed up the startup (issue for that exists).
And it could also solve the migration issue.

**Comment by klartext** [comment]
> What about a one-database-file-per-feed, at least as possible option?
> This would likely speed up the startup (issue for that exists).
> And it could also solve the migration issue.

It would also allow feeds to be used in more than one url-file, where then url-files would work like database-views on the feeds.

**Comment by Minoru** [comment]
> But it would not work, if I decide to move some feeds later from db A to db B.

You're right! I didn't consider this.

I guess it's time to ask what is the problem you're solving. Why are you splitting caches? Is it because of slow startup, or is there something else going on? If the startup got faster (constant time, under a second), would that make migration unnecessary?

> What about a one-database-file-per-feed, at least as possible option?

No. Import-export is a rarely-used feature, and it's not worth the complexity of per-feed databases.

> This would likely speed up the startup

Newsboat will still have to read all those small databases, so I don't see how it will speed anything up.

> It would also allow feeds to be used in more than one url-file, where then url-files would work like database-views on the feeds.

If you need this, please describe a use-case and we can think about possible solutions.

**Comment by klartext** [comment]
> > But it would not work, if I decide to move some feeds later from db A to db B.
> 
> You're right! I didn't consider this.
> 
> I guess it's time to ask what is the problem you're solving. Why are you splitting caches? Is it because of slow startup, or is there something else going on? If the startup got faster (constant time, under a second), would that make migration unnecessary?

Advantages of splitting up caches:
```
1) faster loading of a certain db
2) sepereated topics - one main topic for per db-file, so less clutter with feeds of other topics
3) smaller db-files 'per topic'
4) easier to exchange data, because of seperation (not all data to all recipients)
x) add other items...
```

**Comment by Minoru** [comment]
Yeah, I see how splitting a database could have some advantages, but I am wondering what problem you're facing that made you open this issue in the first place. It's really pointless to discuss solutions if we don't have a clear understanding of what we're even solving.

**Comment by klartext** [comment]
I already mentioned: I created some databases out of one database, and later wanted to migrate some feeds from one to the other database.

**Comment by klartext** [comment]
> I already mentioned: I created some databases out of one database, and later wanted to migrate some feeds from one to the other database.

...and I wanted to pick the old data, thats why migrating the feed instead of just adding it anew.

**Comment by Minoru** [comment]
This tells me *what* you did, but I'm asking *why* you did it. What problem were you solving?

**Comment by klartext** [comment]
I mentioned why already.
But just imagine, someone else had - without previous reason, just because of decision in the first place - more than one database, which is supported by newsboat (why? is it used only by me?), then migrating might also sometimes come up there.
If you don't want to support it, say it.

**Comment by Minoru** [comment]
I don't want to implement something I don't understand, and since I can't seem to get you to answer my questions, I'm giving up on this issue.

If you want to build some tools for your specific problem, take a look at the database schema in src/cache.cpp. That file also has SQL queries that Newsboat runs to store and load data -- that can give you an idea of how things hang together.
