### ISSUE TITLE
Fail to build for aarch64/armv7 with GCC10

### ISSUE THREAD

**Issue by ggardet** [newsboat/newsboat#994]
**Newsboat version: 2.19

Steps to reproduce the issue:

1. Try to compile for Arm (aarch64, armv7) with GCC10
2. See the build error:
```
[  102s] ./3rd-party/json.hpp:8494:24: error: comparison is always true due to limited range of data type [-Werror=type-limits]
[  102s]  8494 |             if ('\x00' <= c and c <= '\x1F')
[  102s]       |                 ~~~~~~~^~~~
```

**Comment by ggardet** [comment]
It looks like related to https://github.com/nlohmann/json/issues/1939

**Comment by Minoru** [comment]
Hey, thanks for the report! Seems like this is fixed in json.hpp 3.8.0, which is not released yet. I'll update it in this repo when it's released.

In the meantime, your options are:

1. add `-Wno-error=type-limits` to `CXXFLAGS` environment variable to suppress the warning;
2. download a newer json.hpp file where the bug is fixed and either put it into 3rd-party directory in Newsboat's tree, or store it elsewhere and point the compiler at it via `CXXFLAGS`.

Since there's nothing left to do here, I'll close the issue.

**Comment by Minoru** [comment]
json.hpp 3.8.0 [is out now](https://github.com/nlohmann/json/releases/tag/v3.8.0) and [I've updated our copy](https://github.com/newsboat/newsboat/commit/1f13f3376b0b022f568123c405c2a82cef5638f1).
